import {useCallback,useEffect,useRef,useState} from 'react';
import {AppState,Image,Modal,Pressable,ScrollView,StyleSheet,Text,TextInput,View} from 'react-native';
import {RoyalContentPanel,RoyalExplanationPanel} from '@/components/ui/RoyalPanels';
import {RoyalBackButton,ROYAL_FONT} from '@/components/ui/RoyalSurface';
import {kaigoCourse,kaigoAtomicKnowledge,kaigoDailyPlan,kaigoLanguageSupplements} from '@/data/kaigo';
import {kaigoDepthFigures} from '@/data/kaigo/depth-figures';
import {kaigoFigures} from '@/data/kaigo/figures';
import {kaigoCatalog,kaigoTopics,searchCatalog,validSelection,type StudySelection,type TopicId} from '@/data/kaigo/catalog';
import {illustrationFor} from '@/data/kaigo/lesson-illustrations';
import type {KnowledgeProbe,LanguageTask,Lesson,MockForm,RubyToken,TransferStep} from '@/data/kaigo/types';
import {answerExam,canAdvancePractice,canRevealPractice,createExamSession,examReview,examStorageKey,publicQuestion,restoreExamSession,scoreQuestions,submitExam,tickExam,type Answers,type ExamSession} from '@/services/kaigo-session';
import {loadKaigoState,saveKaigoState} from '@/services/kaigo-storage';

const revision='test-content-v1';
function Body({children}:{children:React.ReactNode}){return <Text style={s.body}>{children}</Text>;}
function Ja({children}:{children:React.ReactNode}){return <Text selectable style={s.ja}>{children}</Text>;}
function Button({title,onPress,disabled=false,selected=false,testID}:{title:string;onPress:()=>void;disabled?:boolean;selected?:boolean;testID?:string}){return <Pressable accessibilityRole="button" accessibilityLabel={title} accessibilityState={{disabled,selected}} disabled={disabled} onPress={onPress} testID={testID} style={({pressed})=>[s.button,selected&&{backgroundColor:'#395477',borderColor:'#e4be71'},disabled&&s.disabled,pressed&&s.pressed]}><Text style={s.buttonText}>{title}</Text></Pressable>;}
function Ruby({tokens,fallback}:{tokens?:RubyToken[];fallback:string}){return tokens?.length?<View style={s.rubyRow}>{tokens.map((t,i)=>t.text==='\n'?<View key={i} style={{width:'100%'}}/>:<View key={i} style={s.rubyWord}><Text style={s.rubyKana}>{t.readingKana??' '}</Text><Text style={s.rubyText}>{t.text}</Text></View>)}</View>:<Ja>{fallback}</Ja>;}
function useStored<T>(key:string,initial:T,restore:(raw:string|null)=>T){
 const [value,setValue]=useState(initial),[ready,setReady]=useState(false),[error,setError]=useState(false);const current=useRef(initial),loaded=useRef(false),restoreRef=useRef(restore);restoreRef.current=restore;
 useEffect(()=>{let live=true;void loadKaigoState(key).then(raw=>{if(live){const next=restoreRef.current(raw);current.current=next;setValue(next);loaded.current=true;setReady(true);}}).catch(()=>{if(live)setError(true);});return()=>{live=false;};},[key]);
 const update=useCallback((action:T|((old:T)=>T))=>{if(!loaded.current)return;const next=typeof action==='function'?(action as (old:T)=>T)(current.current):action;current.current=next;setValue(next);void saveKaigoState(key,next).then(()=>setError(false)).catch(()=>setError(true));},[key]);
 const retry=()=>{if(!loaded.current){void loadKaigoState(key).then(raw=>{const next=restoreRef.current(raw);current.current=next;setValue(next);loaded.current=true;setReady(true);setError(false);}).catch(()=>setError(true));}else void saveKaigoState(key,current.current).then(()=>setError(false)).catch(()=>setError(true));};
 return {value,update,ready,error,retry,current};
}
function SaveStatus({error,retry}:{error:boolean;retry:()=>void}){return error?<View><Body>Chưa lưu được tiến trình.</Body><Button title="Thử lưu lại" onPress={retry}/></View>:null;}

type PracticeState={attempt:string;revealed:boolean;checked:boolean[];complete:boolean};
const blankPractice:PracticeState={attempt:'',revealed:false,checked:[],complete:false};
function Practice({step,storageKey,onDone}:{step:TransferStep;storageKey:string;onDone?:()=>void}){
 const st=useStored<PracticeState>(storageKey,blankPractice,raw=>{try{const p=JSON.parse(raw??'null') as PracticeState;if(p&&typeof p.attempt==='string'&&typeof p.revealed==='boolean'&&typeof p.complete==='boolean'&&Array.isArray(p.checked)&&p.checked.length<=step.meaningsVi.length&&p.checked.every(x=>typeof x==='boolean'))return p;}catch{}return blankPractice;});
 const p=st.value,npc=kaigoCourse.npcs.find(n=>n.id===step.npcId);const advance=canAdvancePractice(p.attempt,p.revealed,p.checked,step.meaningsVi.length);
 return <RoyalContentPanel style={s.panel}>
  <Text style={s.small}>Nói với {npc?.nameJa} · {npc?.roleVi}</Text>
  {!!step.promptJa&&<Ja>{step.promptJa}</Ja>}{!!step.promptMeaningVi&&<Body>{step.promptMeaningVi}</Body>}<Body>{step.promptVi}</Body>
  <TextInput accessibilityLabel="Câu trả lời tiếng Nhật" testID="kaigo-practice-input" multiline editable={st.ready} value={p.attempt} onChangeText={attempt=>st.update({attempt,revealed:false,checked:[],complete:false})} placeholder="Viết câu tiếng Nhật của bạn" placeholderTextColor="#62708a" style={s.input}/>
  {!p.revealed&&<Button title="Đối chiếu ý" disabled={!st.ready||!canRevealPractice(p.attempt)} testID="kaigo-reveal" onPress={()=>st.update({...p,revealed:true,checked:step.meaningsVi.map(()=>false)})}/>}
  {p.revealed&&<View><Body>Tự đối chiếu từng ý trong câu của bạn:</Body>{step.meaningsVi.map((meaning,i)=><Pressable key={i} accessibilityRole="checkbox" accessibilityState={{checked:!!p.checked[i]}} onPress={()=>st.update({...p,checked:step.meaningsVi.map((_,j)=>j===i?!p.checked[j]:!!p.checked[j]),complete:false})} style={s.check}><Body>{p.checked[i]?'☑':'☐'}{meaning}</Body></Pressable>)}
   {!!step.modelJa&&<View><Text style={s.small}>Một cách nói tham khảo</Text><Ja>{step.modelJa}</Ja>{!!step.modelVi&&<Body>{step.modelVi}</Body>}</View>}
   {step.alternativesJa.filter(x=>x!==step.modelJa).map((x,i)=><Ja key={i}>{x}</Ja>)}
   <Body>Nếu thiếu ý hoặc thêm thông tin chưa xác nhận, sửa câu rồi đối chiếu lại.</Body>
   <Button title="Lưu tự kiểm và xem phản hồi" disabled={!advance} testID="kaigo-advance-practice" onPress={()=>st.update({...p,complete:true})}/>
  </View>}
  {p.complete&&advance&&<View>{!!step.replyJa&&<View><Text style={s.small}>Phản hồi của {npc?.nameJa}</Text><Ja>{step.replyJa}</Ja><Body>{step.replyVi}</Body></View>}<Body>Đã lưu lần luyện và tự kiểm.</Body>{onDone&&<Button title="Lượt tiếp theo" testID="kaigo-next-turn" onPress={onDone}/>}</View>}
  <SaveStatus error={st.error} retry={st.retry}/>
 </RoyalContentPanel>;
}
function Dialogue({lesson}:{lesson:Lesson}){
 const players=lesson.dialogue.filter(t=>t.speaker==='player');const state=useStored<{index:number}>(`@japan_app_kaigo_dialogue:${revision}:${lesson.practiceRevision??lesson.contentRevision}:${lesson.id}`,{index:0},raw=>{try{const p=JSON.parse(raw??'null');if(Number.isInteger(p?.index)&&p.index>=0&&p.index<players.length)return p;}catch{}return {index:0};});const t=players[state.value.index],pos=lesson.dialogue.indexOf(t),before=lesson.dialogue[pos-1],after=lesson.dialogue[pos+1];
 const step:TransferStep={id:t.id,npcId:t.npcId,promptJa:before?.speaker==='npc'?before.textJa:'',promptMeaningVi:before?.speaker==='npc'?before.meaningVi:'',promptVi:state.value.index===0?lesson.contextVi:'Tiếp tục cuộc trao đổi bằng dữ kiện đã nhận.',modelJa:t.textJa,modelVi:t.meaningVi,meaningsVi:t.meaningsVi,alternativesJa:t.alternativesJa,replyJa:after?.speaker==='npc'?after.textJa:'',replyVi:after?.speaker==='npc'?after.meaningVi:''};
 return <View><RoyalExplanationPanel style={s.panel}><Text style={s.light}>Lượt {state.value.index+1}/{players.length} · {lesson.playerRoleVi}</Text></RoyalExplanationPanel><Practice key={t.id} step={step} storageKey={`@japan_app_kaigo_practice:${revision}:${lesson.practiceRevision??lesson.contentRevision}:${t.id}`} onDone={state.value.index+1<players.length?()=>state.update({index:state.value.index+1}):undefined}/><View style={s.row}><Button title="Lượt trước" disabled={!state.ready||state.value.index===0} onPress={()=>state.update({index:state.value.index-1})}/><Button title="Luyện lại từ đầu" disabled={!state.ready} onPress={()=>state.update({index:0})}/></View><SaveStatus error={state.error} retry={state.retry}/></View>;
}
function Transfer({lesson}:{lesson:Lesson}){const [chosen,setChosen]=useState<string|null>(null),[index,setIndex]=useState(0);const v=lesson.transfers.find(v=>v.id===chosen);return <View><RoyalExplanationPanel style={s.panel}><Text style={s.light}>Chọn một tình huống cho lần luyện này.</Text></RoyalExplanationPanel>{!v?lesson.transfers.map(v=><Button key={v.id} title={v.titleVi} onPress={()=>{setChosen(v.id);setIndex(0);}}/>):<View><RoyalExplanationPanel style={s.panel}><Text style={s.light}>{v.contextVi}</Text><Text style={s.light}>{v.boundaryVi}</Text><Text style={s.light}>Bước {index+1}/{v.steps.length}</Text></RoyalExplanationPanel><Practice key={v.steps[index].id} step={v.steps[index]} storageKey={`@japan_app_kaigo_transfer:${revision}:${lesson.practiceRevision??lesson.contentRevision}:${v.steps[index].id}`} onDone={index+1<v.steps.length?()=>setIndex(index+1):undefined}/><Button title="Chọn tình huống khác" onPress={()=>setChosen(null)}/></View>}</View>;}
type CheckState={answers:Answers;submitted:boolean};
function LessonCheck({lesson}:{lesson:Lesson}){const initial:CheckState={answers:{},submitted:false};const st=useStored<CheckState>(`@japan_app_kaigo_check:${revision}:${lesson.practiceRevision??lesson.contentRevision}:${lesson.id}`,initial,raw=>{try{const p=JSON.parse(raw??'null') as CheckState;if(p&&typeof p.submitted==='boolean'&&p.answers&&typeof p.answers==='object'&&!Array.isArray(p.answers)&&Object.entries(p.answers).every(([id,a])=>lesson.questions.some(q=>q.id===id&&Number.isInteger(a)&&a>=0&&a<q.optionsJa.length)))return p;}catch{}return initial;});const {answers,submitted}=st.value;
 return <View><RoyalContentPanel style={s.panel}><Ja>{lesson.readingJa}</Ja><Body>{lesson.readingVi}</Body></RoyalContentPanel>{lesson.questions.map((q,i)=><RoyalContentPanel key={q.id} style={s.panel}><Body>Câu {i+1}</Body><Ja>{q.promptJa}</Ja>{q.promptVi&&<Body>{q.promptVi}</Body>}{q.optionsJa.map((o,j)=><Pressable accessibilityRole="radio" accessibilityState={{selected:answers[q.id]===j,disabled:submitted}} key={j} disabled={!st.ready||submitted} onPress={()=>st.update({answers:{...answers,[q.id]:j},submitted:false})} style={[s.option,answers[q.id]===j&&s.selected]}><Ja>{j+1}. {o}</Ja></Pressable>)}{submitted&&<View><Body>{answers[q.id]===q.correctIndex?'Đúng':answers[q.id]===undefined?'Chưa trả lời':'Cần ôn lại'} · Đáp án {q.correctIndex+1}</Body>{q.rationalesVi.map((r,j)=><Body key={j}>{j+1}. {r}</Body>)}</View>}</RoyalContentPanel>)}{!submitted?<Button title="Nộp 5 câu và xem giải thích" disabled={!st.ready} testID="kaigo-submit-check" onPress={()=>st.update({...st.value,submitted:true})}/>:<View><RoyalExplanationPanel style={s.panel}><Text style={s.light}>Kết quả: {scoreQuestions(lesson.questions,answers)}/{lesson.questions.length}</Text></RoyalExplanationPanel><Button title="Làm lại 5 câu" onPress={()=>st.update(initial)}/></View>}<SaveStatus error={st.error} retry={st.retry}/></View>;
}
function RetrievalCard({probe,lesson}:{probe:KnowledgeProbe|LanguageTask;lesson:Lesson}){
 const st=useStored<{attempt:string;revealed:boolean}>(`@japan_app_kaigo_knowledge:${revision}:${probe.stateRevision??lesson.knowledgeRevision??lesson.contentRevision}:${probe.id}`,{attempt:'',revealed:false},raw=>{try{const p=JSON.parse(raw??'null');if(p&&typeof p.attempt==='string'&&typeof p.revealed==='boolean'&&(!p.revealed||p.attempt.trim()))return p;}catch{}return {attempt:'',revealed:false};});
 return <RoyalContentPanel style={s.panel}>{'textJa' in probe&&<View>{probe.furigana&&<Text style={s.heading}>{probe.titleVi}</Text>}<Ruby tokens={probe.furigana} fallback={probe.textJa}/></View>}<Body>{probe.promptVi}</Body><TextInput testID={`kaigo-probe-${probe.id}`} accessibilityLabel="Giải thích bằng lời của bạn" multiline editable={st.ready} value={st.value.attempt} onChangeText={attempt=>st.update({attempt,revealed:false})} style={s.input}/><Button title="Đối chiếu ý kiến thức" disabled={!st.ready||!st.value.attempt.trim()} onPress={()=>st.update({...st.value,revealed:true})}/>{st.value.revealed&&<View><Body>{probe.expectedVi}</Body><Text style={s.small}>Tự đối chiếu: sửa ý thiếu hoặc suy quá dữ kiện. Câu trả lời được lưu để tiếp tục ôn.</Text></View>}<SaveStatus error={st.error} retry={st.retry}/></RoyalContentPanel>;
}
function KnowledgeFigure({figure}:{figure:{key:string;captionVi:string}}){const [open,setOpen]=useState(false);return <View><Image testID={`kaigo-depth-figure-${figure.key}`} accessibilityLabel={figure.captionVi} source={kaigoDepthFigures[figure.key]} resizeMode="contain" style={{width:'100%',aspectRatio:800/660,marginVertical:10}}/><Body>{figure.captionVi}</Body><Button title="Phóng to sơ đồ" onPress={()=>setOpen(true)}/><Modal visible={open} transparent animationType="none" onRequestClose={()=>setOpen(false)}><View style={s.modalBackdrop}><View style={[s.modalCard,{maxWidth:900,maxHeight:'90%'}]}><Button title="Đóng sơ đồ" onPress={()=>setOpen(false)}/><Body>Vuốt ngang để xem các phần của sơ đồ.</Body><ScrollView><ScrollView horizontal testID="kaigo-depth-zoom-scroll"><Image testID="kaigo-depth-zoom" accessibilityLabel={figure.captionVi} source={kaigoDepthFigures[figure.key]} resizeMode="contain" style={{width:800,height:660}}/></ScrollView><Body>{figure.captionVi}</Body></ScrollView></View></View></Modal></View>;}
function LessonIllustration({parentDay,title}:{parentDay:number;title:string}){const f=illustrationFor(parentDay,title);return <RoyalContentPanel style={s.panel}><Image testID={`kaigo-lesson-illustration-${f.key}`} accessibilityLabel={f.captionVi} source={f.source} resizeMode="cover" style={{width:'100%',aspectRatio:f.aspectRatio,borderRadius:10,marginVertical:6}}/><Body>{f.captionVi}</Body><Text style={s.small}>Minh hoạ tình huống mới · đọc cùng phần kiến thức của bài.</Text></RoyalContentPanel>;}
function Knowledge({lesson}:{lesson:Lesson}){return <View><LessonIllustration parentDay={lesson.day} title={lesson.titleVi}/>{!!lesson.knowledgeTitleVi&&<RoyalExplanationPanel style={s.panel}><Text style={[s.heading,s.light]}>{lesson.knowledgeTitleVi}</Text><Text style={s.light}>{lesson.knowledgeDepthUnits?.length?'12 phút: 3 nối ý nền · 4 đọc các mục sâu bên dưới · 3 giải thích một ca mới · 2 ôn cơ chế. Không cộng mọi câu ôn vào hôm nay.':'7 phút đọc và kết nối · 5 phút tự giải thích. Chọn một câu về cơ chế và một câu tình huống; câu khác để ôn tiếp.'}</Text></RoyalExplanationPanel>}{!!lesson.knowledgeSummaryJa&&<RoyalContentPanel style={s.panel}><Ja>{lesson.knowledgeSummaryJa}</Ja></RoyalContentPanel>}{lesson.knowledgeSectionsVi.map((t,i)=><RoyalContentPanel key={i} style={s.panel}><Body>{t}</Body></RoyalContentPanel>)}{lesson.knowledgeDepthUnits?.map(u=><View key={u.id} testID={`kaigo-depth-${u.id}`}><RoyalContentPanel style={s.panel}><Text style={s.heading}>{u.titleVi}</Text><Body>{u.knowledgeVi}</Body><Text style={s.small}>Cách làm và điểm kiểm</Text><Body>{u.methodVi}</Body><Text style={s.small}>Lỗi dễ nhầm</Text><Body>{u.mistakesVi}</Body>{u.figures.map(f=><KnowledgeFigure key={f.key} figure={f}/>)}<Text style={s.small}>{u.limitsVi}</Text></RoyalContentPanel><RetrievalCard probe={u.probe} lesson={lesson}/></View>)}{lesson.knowledgeProbes?.map(p=><RetrievalCard key={p.id} probe={p} lesson={lesson}/>)}{lesson.contrast&&<RoyalContentPanel style={s.panel}><Body>{lesson.contrast.case}</Body><Body>{lesson.contrast.correctPrinciple}</Body><Body>{lesson.contrast.overreachToAvoid}</Body></RoyalContentPanel>}{lesson.retrieval&&<RetrievalCard probe={{id:lesson.id+'-retrieval',...lesson.retrieval}} lesson={lesson}/>}</View>;}
function AtomicStudy({day,onParent}:{day:number;onParent:(id:string)=>void}){
 const session=kaigoAtomicKnowledge.days.find(d=>d.day===day);
 if(!session)return null;
 return <View><RoyalExplanationPanel style={s.panel}><Text style={[s.heading,s.light]}>Ngày {day} · Kiến thức chi tiết</Text><Text style={s.light}>{session.studyPlanVi}</Text></RoyalExplanationPanel>{session.unitIds.map(id=>{
  const u=kaigoAtomicKnowledge.units.find(u=>u.id===id);
  if(!u)return null;
  const parent=kaigoCourse.lessons.find(l=>l.day===u.parentDay);
  if(!parent)return null;
  return <View key={u.id} testID={u.id}><LessonIllustration parentDay={u.parentDay} title={u.titleVi}/><RoyalContentPanel style={s.panel}><Text style={s.heading}>{u.titleVi}</Text>{u.points.map(p=><View key={p.id} testID={p.id}><Body>{p.explanationVi}</Body></View>)}<Text style={s.small}>{u.limitsVi}</Text><Button title={`Xem bài liên quan · Ngày ${parent.day}`} onPress={()=>onParent(parent.id)}/></RoyalContentPanel><RetrievalCard probe={{...u.probe,stateRevision:u.contentRevision}} lesson={parent}/></View>;
 })}</View>;
}
function LanguageSupplementStudy({day,onParent}:{day:number;onParent:(id:string)=>void}){
 const session=kaigoLanguageSupplements.days.find(d=>d.day===day),group=kaigoLanguageSupplements.groups.find(g=>g.id===session?.groupId),parent=kaigoCourse.lessons.find(l=>l.day===group?.parentDay);
 if(!session||!group||!parent)return null;
 return <View><RoyalExplanationPanel style={s.panel}><Text style={[s.heading,s.light]}>Ngày {day} · {group.titleVi}</Text><Text style={s.light}>{session.studyPlanVi}</Text></RoyalExplanationPanel><LessonIllustration parentDay={group.parentDay} title={group.titleVi}/><RoyalContentPanel style={s.panel}>{group.notesVi.map((note,i)=><Body key={i}>{note}</Body>)}<Button title={`Xem bài liên quan · Ngày ${parent.day}`} onPress={()=>onParent(parent.id)}/></RoyalContentPanel>{group.tasks.map(t=><RetrievalCard key={t.id} probe={t} lesson={parent}/>)}{!!group.referenceTermIds.length&&<RoyalExplanationPanel style={s.panel}><Text style={s.light}>Kho từ để tra cứu; chọn tối đa 8 từ cần ôn hôm nay, không học thuộc toàn bộ trong một buổi.</Text></RoyalExplanationPanel>}{group.referenceTermIds.map(id=>{const t=kaigoCourse.terms.find(t=>t.id===id);return t?<RoyalContentPanel key={id} style={s.panel}><Ja>{t.termJa}</Ja><Body>{t.readingJa} · {t.meaningVi}</Body></RoyalContentPanel>:null;})}</View>;
}
function RelatedStudy({day,onSelect}:{day:number;onSelect:(next:StudySelection)=>void}){const [open,setOpen]=useState(false);const entries=kaigoCatalog.filter(e=>e.parentDay===day&&(e.kind==='atomic'||e.kind==='language'));if(!entries.length)return null;return <View><Button title={`${open?'Đóng':'Ôn'} ${entries.length} buổi liên quan`} testID="kaigo-related-toggle" onPress={()=>setOpen(!open)}/>{open&&entries.map(e=><RoyalContentPanel key={e.day} style={s.panel}><Body>Ngày {e.day} · {e.typeVi}</Body><Text style={s.heading}>{e.titleVi}</Text><Button title="Mở buổi liên quan" testID={`kaigo-related-${e.day}`} onPress={()=>onSelect({kind:e.kind,id:e.id})}/></RoyalContentPanel>)}</View>;}
function LessonStudy({lesson,onRelated}:{lesson:Lesson;onRelated:(next:StudySelection)=>void}){const [tab,setTab]=useState(0);const tabs=['Kiến thức','Từ và cách nói','Luyện thoại','Chuyển giao','5 câu kiểm tra',...(lesson.languageTasks?.length?['Đọc và hiểu']:[])];return <View><RoyalExplanationPanel style={s.panel}><Text style={[s.heading,s.light]}>Ngày {lesson.day} · {lesson.titleVi}</Text><Text style={s.light}>{lesson.studyPlanVi??'30 phút dự kiến · có thể tiếp tục phần chưa xong.'}</Text></RoyalExplanationPanel><View style={s.wrap}>{tabs.map((title,i)=><Button key={title} title={title} onPress={()=>setTab(i)}/>)}</View>{tab===0&&<Knowledge lesson={lesson}/>}{tab===1&&<View>{lesson.activeTermIds&&<RoyalExplanationPanel style={s.panel}><Text style={s.light}>4 phút: ưu tiên tối đa 8 từ đầu. Kho từ theo tuần phía dưới dùng nhận diện/tra cứu; không phải học thuộc tất cả hôm nay.</Text></RoyalExplanationPanel>}{[...kaigoCourse.terms.filter(t=>lesson.termIds.includes(t.id??'')).sort((a,b)=>Number(lesson.activeTermIds?.includes(b.id??''))-Number(lesson.activeTermIds?.includes(a.id??''))),...lesson.inlineNotes].map((t,i)=><RoyalContentPanel key={i} style={s.panel}><Ja>{t.termJa}</Ja><Body>{t.readingJa} · {t.meaningVi}</Body></RoyalContentPanel>)}{lesson.expressions.map((x,i)=><RoyalContentPanel key={i} style={s.panel}><Ja>{x.textJa}</Ja><Body>{x.meaningVi}</Body></RoyalContentPanel>)}</View>}{tab===2&&<Dialogue lesson={lesson}/>}{tab===3&&<Transfer lesson={lesson}/>}{tab===4&&<LessonCheck lesson={lesson}/>} {tab===5&&<View><RoyalExplanationPanel style={s.panel}><Text style={s.light}>2 phút đọc một thẻ ngắn và tự giải thích theo dữ kiện. Nếu chưa xong, giữ phần còn lại để ôn tiếp.</Text></RoyalExplanationPanel>{lesson.languageTasks?.map(t=><RetrievalCard key={t.id} probe={t} lesson={lesson}/>)}</View>}<RelatedStudy day={lesson.day} onSelect={onRelated}/></View>;}

function MockExam({form,active}:{form:MockForm;active:boolean}){
 const st=useStored<ExamSession>(examStorageKey(form),createExamSession(form),raw=>restoreExamSession(raw,form));const [confirm,setConfirm]=useState(false);const session=st.value;const {ready,update}=st;
 useEffect(()=>{if(!ready||!active||session.status!=='active')return;let visible=AppState.currentState==='active',last=Date.now();const advance=()=>{const now=Date.now();if(visible)update(s=>tickExam(s,Math.max(0,now-last),now));last=now;};const timer=setInterval(advance,1000);const subscription=AppState.addEventListener('change',next=>{advance();visible=next==='active';last=Date.now();});return()=>{clearInterval(timer);subscription.remove();advance();};},[active,ready,session.status,update]);
 const review=examReview(session,form);const current=form.questions[session.currentQuestion],q=publicQuestion(current);const seconds=Math.ceil(session.remainingMs/1000);
 return <View><RoyalExplanationPanel style={s.panel}><Text style={[s.heading,s.light]}>{form.titleVi}</Text><Text style={s.light}>{review?'Đã nộp':`Còn ${Math.floor(seconds/60)}:${String(seconds%60).padStart(2,'0')} · Câu ${session.currentQuestion+1}/${form.questions.length}`}</Text></RoyalExplanationPanel><SaveStatus error={st.error} retry={st.retry}/>
 {review?<View><RoyalExplanationPanel style={s.panel}><Text style={s.light}>Điểm luyện tập: {review.score}/{review.total}. Đây là điểm thô của app, không quy đổi thành kết quả thi chính thức.</Text></RoyalExplanationPanel>{review.questions.map((x,i)=><RoyalContentPanel key={x.id} style={s.panel}><Body>Câu {i+1} · {session.answers[x.id]===x.correctIndex?'Đúng':session.answers[x.id]===undefined?'Bỏ trống':'Sai'} · Đáp án {x.correctIndex+1}</Body>{!!x.passageJa&&<Ruby tokens={x.furigana.passage} fallback={x.passageJa}/>}<Ruby tokens={x.furigana.prompt} fallback={x.promptJa}/>{!!x.figureKey&&<Image source={kaigoFigures[x.figureKey]} resizeMode="contain" style={s.figure}/>}{!!x.figureDescriptionJa&&<Ruby tokens={x.furigana.figureDescription} fallback={x.figureDescriptionJa}/>}<Body>{x.figureDescriptionVi}</Body><Body>{x.passageVi}</Body><Body>{x.promptVi}</Body>{x.optionsJa.map((o,j)=><View key={j}><Body>{j+1}.</Body><Ruby tokens={x.furigana.options[j]} fallback={o}/><Body>{x.optionsVi[j]}</Body><Body>{x.rationalesVi[j]}</Body></View>)}</RoyalContentPanel>)}<Button title="Làm lại đề này" onPress={()=>st.update(createExamSession(form))}/></View>:<View>
 <RoyalContentPanel style={s.panel}>{!!q.passageJa&&<Ruby tokens={q.furigana.passage} fallback={q.passageJa}/>}{!!q.figureKey&&<Image accessibilityLabel={q.figureDescriptionJa} source={kaigoFigures[q.figureKey]} resizeMode="contain" style={s.figure}/>}{!!q.figureDescriptionJa&&<Ruby tokens={q.furigana.figureDescription} fallback={q.figureDescriptionJa}/>}<Ruby tokens={q.furigana.prompt} fallback={q.promptJa}/>{q.optionsJa.map((o,i)=><Pressable key={i} accessibilityRole="radio" accessibilityState={{selected:session.answers[q.id]===i}} disabled={!st.ready} testID={`kaigo-option-${i}`} onPress={()=>st.update(s=>answerExam(s,current,i))} style={[s.option,session.answers[q.id]===i&&s.selected]}><Body>{i+1}.</Body><Ruby tokens={q.furigana.options[i]} fallback={o}/></Pressable>)}</RoyalContentPanel>
 <View style={s.row}><Button title="Câu trước" disabled={!st.ready||session.currentQuestion===0} onPress={()=>st.update(s=>({...s,currentQuestion:s.currentQuestion-1}))}/><Button title="Câu sau" disabled={!st.ready||session.currentQuestion===form.questions.length-1} onPress={()=>st.update(s=>({...s,currentQuestion:s.currentQuestion+1}))}/></View>
 <View style={s.wrap}>{form.questions.map((x,i)=><Button key={x.id} title={`${i+1}${session.answers[x.id]!==undefined?' ✓':''}`} disabled={!st.ready} onPress={()=>st.update(s=>({...s,currentQuestion:i}))}/>)}</View><Button title="Nộp bài" testID="kaigo-submit-exam" disabled={!st.ready} onPress={()=>setConfirm(true)}/>
 </View>}
 <Modal visible={confirm&&!review} transparent animationType="none" onRequestClose={()=>setConfirm(false)}><View style={s.modalBackdrop}><View style={s.modalCard}><Body>Đã trả lời {Object.keys(session.answers).length}/{form.questions.length} câu. Nộp bài và kết thúc lượt này?</Body><Button title="Tiếp tục làm bài" onPress={()=>setConfirm(false)}/><Button title="Xác nhận nộp bài" testID="kaigo-confirm-submit" onPress={()=>{st.update(s=>submitExam(s));setConfirm(false);}}/></View></View></Modal>
 </View>;
}
type CatalogPreferences={view:'calendar'|'topics'|'mocks'|'extras';query:string;topic:TopicId|null;page:number};
function CourseCatalog({onSelect,last,ready,state,setState}:{onSelect:(next:StudySelection)=>void;last:StudySelection|null;ready:boolean;state:CatalogPreferences;setState:React.Dispatch<React.SetStateAction<CatalogPreferences>>}){
 const {view,query,topic,page}=state,setView=(view:CatalogPreferences['view'])=>setState(s=>({...s,view})),setQuery=(query:string)=>setState(s=>({...s,query})),setTopic=(topic:TopicId|null)=>setState(s=>({...s,topic})),setPage=(page:number)=>setState(s=>({...s,page}));
 const entries=searchCatalog(kaigoCatalog.filter(e=>view!=='topics'||!topic||e.topicId===topic),query),pages=Math.max(1,Math.ceil(entries.length/12)),current=Math.min(page,pages-1),slice=entries.slice(current*12,current*12+12);
 const lastEntry=last&&kaigoCatalog.find(e=>e.kind===last.kind&&e.id===last.id),lastTitle=lastEntry?.titleVi??(last?.kind==='mock'?kaigoCourse.mocks.find(m=>m.id===last.id)?.titleVi:kaigoCourse.candidates.find(l=>l.id===last?.id)?.titleVi);
 const changeView=(next:typeof view)=>{setView(next);setPage(0);setQuery('');};
 const pager=<View style={s.row}><Button title="Trang trước" testID="kaigo-catalog-prev" disabled={current===0} onPress={()=>setPage(current-1)}/><Button title="Trang sau" testID="kaigo-catalog-next" disabled={current===pages-1} onPress={()=>setPage(current+1)}/><Text style={s.light}>Trang {current+1}/{pages}</Text></View>;
 return <View><RoyalExplanationPanel style={[s.panel,{paddingVertical:14}]}><Text style={s.light}>30 phút/buổi: tự trả lời, đối chiếu rồi ôn ý còn yếu. Nội dung chờ duyệt chuyên môn và bản ngữ.</Text></RoyalExplanationPanel>
 {last&&lastTitle&&<RoyalContentPanel style={s.panel}><Text style={s.small}>Bài mở gần nhất{lastEntry?` · Ngày ${lastEntry.day}`:''}</Text><Text style={s.heading}>{lastTitle}</Text><Button title="Mở lại bài gần nhất" testID="kaigo-resume-study" disabled={!ready} onPress={()=>onSelect(last)}/></RoyalContentPanel>}
 <View style={s.wrap}>{([{id:'calendar',title:'Học theo lịch'},{id:'topics',title:'Ôn theo chủ đề'},{id:'mocks',title:'Thi thử'},{id:'extras',title:'Tình huống bổ sung'}] as const).map(x=><Button key={x.id} title={x.title} selected={view===x.id} testID={`kaigo-catalog-${x.id}`} onPress={()=>changeView(x.id)}/>)}</View>
 {(view==='calendar'||view==='topics')&&<View><RoyalContentPanel style={s.panel}><Text style={s.heading}>{view==='calendar'?'Lịch học đúng thứ tự':'Chọn chủ đề cần ôn'}</Text><Body>{kaigoDailyPlan.totalDays} buổi × 30 phút. Tìm tên bài hoặc số ngày.</Body><TextInput accessibilityLabel="Tìm bài theo tên, chủ đề hoặc số ngày" testID="kaigo-catalog-search" value={query} onChangeText={q=>{setQuery(q);setPage(0);}} placeholder="Tên bài, chủ đề hoặc số ngày" placeholderTextColor="#62708a" style={[s.input,{minHeight:48}]}/>{!!query&&<Button title="Xóa tìm kiếm" onPress={()=>{setQuery('');setPage(0);}}/>}</RoyalContentPanel>
 {view==='topics'&&<View><View style={s.wrap}><Button title="Tất cả chủ đề" selected={!topic} onPress={()=>{setTopic(null);setPage(0);}}/>{kaigoTopics.map(t=><Button key={t.id} title={t.titleVi} testID={`kaigo-topic-${t.id}`} selected={topic===t.id} onPress={()=>{setTopic(t.id);setPage(0);}}/>)}</View>{topic&&<RoyalExplanationPanel style={s.panel}><Text style={s.light}>{kaigoTopics.find(t=>t.id===topic)?.guideVi}</Text></RoyalExplanationPanel>}</View>}
 <Text style={s.light}>{entries.length} buổi{entries.length?` · đang xem ${current*12+1}–${Math.min((current+1)*12,entries.length)}`:''}</Text>{entries.length>0&&pager}{!entries.length&&<RoyalContentPanel style={s.panel}><Body>Chưa có bài khớp. Thử số ngày hoặc một từ trong tên chủ đề.</Body><Button title="Xem toàn bộ lịch" onPress={()=>{setTopic(null);setQuery('');setPage(0);setView('calendar');}}/></RoyalContentPanel>}
 {slice.map(e=><View key={e.day} testID={`kaigo-catalog-entry-${e.day}`}><RoyalContentPanel style={s.panel}><Text style={s.small}>Ngày {e.day} · 30 phút · {e.typeVi}</Text><Text style={s.heading}>{e.titleVi}</Text>{e.practiceTitleVi&&<Text style={s.small}>Thực hành: {e.practiceTitleVi}</Text>}<Body>{kaigoTopics.find(t=>t.id===e.topicId)?.titleVi}</Body>{e.kind!=='lesson'&&e.kind!=='mock'&&<Text style={s.small}>Nối bài nền ngày {e.parentDay}</Text>}<Button title={e.kind==='mock'?'Mở đề thi thử':e.kind==='atomic'?'Mở kiến thức chi tiết':e.kind==='language'?'Mở đọc hiểu tình huống':'Mở bài học'} testID={e.testID} onPress={()=>onSelect({kind:e.kind,id:e.id})}/></RoyalContentPanel></View>)}{entries.length>0&&<View style={s.row}><Button title="12 buổi trước" testID="kaigo-catalog-bottom-prev" disabled={current===0} onPress={()=>setPage(current-1)}/><Button title="12 buổi tiếp" testID="kaigo-catalog-bottom-next" disabled={current===pages-1} onPress={()=>setPage(current+1)}/></View>}</View>}
 {view==='mocks'&&<View><RoyalExplanationPanel style={s.panel}><Text style={[s.heading,s.light]}>12 đề thi thử · 360 câu</Text><Text style={s.light}>6 đề kỹ năng: 45 câu, 60 phút/đề. Khi luyện 30 phút/ngày, rời đề rồi tiếp tục cùng lượt đã lưu. 6 đề tiếng Nhật: 15 câu, 30 phút/đề. Sau lượt thi, dành một buổi riêng chữa câu sai hoặc bỏ trống và chọn chủ đề cần ôn.</Text></RoyalExplanationPanel>{kaigoCourse.mocks.map(m=><RoyalContentPanel key={m.id} style={s.panel}><Text style={s.heading}>{m.id.endsWith('-01')?m.titleVi+' · Đề 1':m.titleVi}</Text><Body>{m.questions.length} câu · {m.durationMs/60000} phút</Body><Button title="Mở đề" testID={`kaigo-mock-${m.id}`} onPress={()=>onSelect({kind:'mock',id:m.id})}/></RoyalContentPanel>)}</View>}
 {view==='extras'&&<View><RoyalExplanationPanel style={s.panel}><Text style={s.light}>8 tình huống để luyện thêm theo nhu cầu. Chọn một nhánh trong buổi ôn, không cộng tất cả vào 30 phút hôm nay.</Text></RoyalExplanationPanel>{kaigoCourse.candidates.map(l=><RoyalContentPanel key={l.id} style={s.panel}><Text style={s.heading}>{l.titleVi}</Text><Button title="Mở tình huống bổ sung" testID={`kaigo-candidate-${l.id}`} onPress={()=>onSelect({kind:'lesson',id:l.id})}/></RoyalContentPanel>)}</View>}
 </View>;
}
export function KaigoCourse({onBack,active=true}:{onBack:()=>void;active?:boolean}){
 const [selection,setSelection]=useState<StudySelection|null>(null),[catalog,setCatalog]=useState<CatalogPreferences>({view:'calendar',query:'',topic:null,page:0});
 const last=useStored<StudySelection|null>('@japan_app_kaigo_catalog:last-opened:v1',null,raw=>{try{const x=JSON.parse(raw??'null');return validSelection(x)?{kind:x.kind,id:x.id}:null;}catch{return null;}});
 const select=(next:StudySelection)=>{if(validSelection(next)){setSelection(next);last.update(next);}};
 const lesson=selection?.kind==='lesson'?[...kaigoCourse.lessons,...kaigoCourse.candidates].find(l=>l.id===selection.id):undefined,mock=selection?.kind==='mock'?kaigoCourse.mocks.find(m=>m.id===selection.id):undefined;
 return <View style={s.root}><View style={s.header}><RoyalBackButton onPress={()=>selection?setSelection(null):onBack()}/><View style={s.headerText}><Text style={s.title}>介護</Text><Text style={s.subtitle}>Bản kiểm tra nội bộ · {kaigoDailyPlan.totalDays} ngày dự kiến · 30 phút/ngày</Text></View></View><ScrollView key={selection?selection.kind+':'+selection.id:'catalog'} testID="kaigo-course-scroll" keyboardShouldPersistTaps="handled" contentContainerStyle={s.content}>
 {lesson?<LessonStudy key={lesson.id} lesson={lesson} onRelated={select}/>:mock?<MockExam key={mock.id} form={mock} active={active}/>:selection?.kind==='language'?<LanguageSupplementStudy key={selection.id} day={Number(selection.id)} onParent={id=>select({kind:'lesson',id})}/>:selection?.kind==='atomic'?<AtomicStudy key={selection.id} day={Number(selection.id)} onParent={id=>select({kind:'lesson',id})}/>:<View><CourseCatalog onSelect={select} last={last.value} ready={last.ready} state={catalog} setState={setCatalog}/><SaveStatus error={last.error} retry={last.retry}/></View>}
 </ScrollView></View>;
}
const s=StyleSheet.create({root:{flex:1},header:{flexDirection:'row',gap:14,paddingHorizontal:18,paddingTop:10,paddingBottom:12},headerText:{flex:1},title:{fontFamily:ROYAL_FONT.heading,fontSize:26,color:'#fff3cf'},subtitle:{fontFamily:ROYAL_FONT.body,fontSize:15,color:'#fffdf7'},content:{padding:18,paddingBottom:40,gap:10},heading:{fontFamily:ROYAL_FONT.heading,fontSize:20,color:'#142335',lineHeight:28,marginVertical:8},panel:{paddingHorizontal:26,paddingVertical:24,marginBottom:14},body:{fontFamily:ROYAL_FONT.body,color:'#26364c',fontSize:16,lineHeight:25,marginVertical:5},small:{fontFamily:ROYAL_FONT.body,color:'#43536b',fontSize:14,lineHeight:22,marginVertical:5},ja:{fontFamily:ROYAL_FONT.body,color:'#142335',fontSize:20,lineHeight:32,marginVertical:6},light:{fontFamily:ROYAL_FONT.body,fontSize:16,lineHeight:25,color:'#fff3cf'},button:{backgroundColor:'#1b3153',borderColor:'#c99c51',borderWidth:1,borderRadius:10,paddingHorizontal:14,paddingVertical:12,marginVertical:5,alignItems:'center',justifyContent:'center'},buttonText:{fontFamily:ROYAL_FONT.body,color:'#fff3cf',fontSize:16,lineHeight:23,textAlign:'center'},disabled:{opacity:.45},pressed:{opacity:.7},row:{flexDirection:'row',flexWrap:'wrap',gap:12},wrap:{flexDirection:'row',flexWrap:'wrap',gap:8,marginBottom:10},input:{position:'relative',fontFamily:ROYAL_FONT.body,color:'#142335',backgroundColor:'#fffdf4',borderColor:'#61718b',borderWidth:1,borderRadius:8,padding:12,minHeight:95,fontSize:18,lineHeight:28,textAlignVertical:'top',marginVertical:10},check:{paddingVertical:6},option:{borderWidth:1,borderColor:'#8792a3',borderRadius:8,padding:12,marginVertical:6},selected:{borderColor:'#c08e25',borderWidth:2,backgroundColor:'#fff0c4'},rubyRow:{flexDirection:'row',flexWrap:'wrap',alignItems:'flex-end',marginVertical:4},rubyWord:{alignItems:'center',paddingHorizontal:1},rubyKana:{fontFamily:ROYAL_FONT.body,fontSize:10,lineHeight:15,color:'#43536b'},rubyText:{fontFamily:ROYAL_FONT.body,fontSize:20,lineHeight:30,color:'#142335'},figure:{width:'100%',aspectRatio:800/420,maxHeight:260,marginVertical:10},modalBackdrop:{flex:1,backgroundColor:'rgba(0,0,0,.65)',alignItems:'center',justifyContent:'center',padding:20},modalCard:{maxWidth:480,width:'100%',padding:24,borderRadius:14,backgroundColor:'#fff6df'}});
