import { router, useLocalSearchParams } from 'expo-router';
import { useEffect, useRef } from 'react';
import { Animated, Easing, Pressable, StyleSheet, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';

export function EducationWelcome() {
  const params=useLocalSearchParams<{mode?:string}>(); const returning=params.mode==='login';
  const enter=useRef(new Animated.Value(0)).current; const ring=useRef(new Animated.Value(0)).current;
  useEffect(()=>{const a=Animated.parallel([Animated.timing(enter,{toValue:1,duration:850,easing:Easing.out(Easing.back(1.2)),useNativeDriver:true}),Animated.loop(Animated.timing(ring,{toValue:1,duration:1800,easing:Easing.linear,useNativeDriver:true}))]);a.start();const timer=setTimeout(()=>router.replace('/portal/education/dashboard'),2600);return()=>{clearTimeout(timer);a.stop();};},[enter,ring]);
  return <View style={s.screen}><SafeAreaView style={s.safe}><View style={s.petals}><Text style={s.petal}>✦</Text><Text style={s.petal2}>✦</Text><Text style={s.petal3}>✦</Text></View><Animated.View style={[s.ring,{transform:[{rotate:ring.interpolate({inputRange:[0,1],outputRange:['0deg','360deg']})}]}]} /><Animated.View style={[s.card,{opacity:enter,transform:[{translateY:enter.interpolate({inputRange:[0,1],outputRange:[35,0]})},{scale:enter.interpolate({inputRange:[0,1],outputRange:[0.86,1]})}]}]}><Text style={s.eyebrow}>{returning?'おかえりなさい':'ご登録ありがとうございます'}</Text><Text style={s.title}>{returning?'またお会いできて嬉しいです':'ようこそ、教育管理ワークスペースへ'}</Text><Text style={s.message}>{returning?'今日も学生一人ひとりの学びを、一緒に支えていきましょう。':'決済が完了しました。授業に必要な教材と機能をすべてご利用いただけます。'}</Text><Pressable onPress={()=>router.replace('/portal/education/dashboard')} style={s.button}><Text style={s.buttonText}>ワークスペースを開く　›</Text></Pressable><Text style={s.auto}>まもなく自動的に移動します</Text></Animated.View></SafeAreaView></View>;
}
const s=StyleSheet.create({screen:{flex:1,backgroundColor:'#eaf7f8'},safe:{flex:1,alignItems:'center',justifyContent:'center',padding:22},petals:{...StyleSheet.absoluteFillObject},petal:{position:'absolute',left:'14%',top:'21%',color:'#f2a8b7',fontSize:27},petal2:{position:'absolute',right:'17%',top:'27%',color:'#80c7cf',fontSize:19},petal3:{position:'absolute',left:'23%',bottom:'20%',color:'#eec36e',fontSize:16},ring:{position:'absolute',width:310,height:310,borderRadius:155,borderWidth:2,borderStyle:'dashed',borderColor:'rgba(75,166,177,0.25)'},card:{width:'100%',maxWidth:520,padding:34,borderRadius:28,borderBottomWidth:8,borderBottomColor:'#348d98',alignItems:'center',backgroundColor:'#e8e2d6',shadowColor:'#245b63',shadowOpacity:.16,shadowRadius:20,shadowOffset:{width:0,height:10}},eyebrow:{color:'#33838e',fontSize:16,fontWeight:'900'},title:{marginTop:8,color:'#194852',fontSize:27,lineHeight:36,fontWeight:'900',textAlign:'center'},message:{marginTop:12,color:'#607a80',fontSize:15,lineHeight:24,fontWeight:'700',textAlign:'center'},button:{minHeight:53,marginTop:21,paddingHorizontal:23,borderRadius:15,borderBottomWidth:5,borderBottomColor:'#28737d',alignItems:'center',justifyContent:'center',backgroundColor:'#4aa5b0'},buttonText:{color:'#fff',fontSize:16,fontWeight:'900'},auto:{marginTop:12,color:'#718589',fontSize:13,fontWeight:'700'}});
