import { router } from 'expo-router';
import { useState } from 'react';
import { Alert, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { useRoyalPositioning } from '@/components/ui/RoyalPositioning';
import { RoyalBackButton } from '@/components/ui/RoyalSurface';

const PARTICIPANTS=['佐藤先生','グエン・アン','チャン・リン','レ・フン','ホアン・ナム'];
const TOOLS=[['↖','選択'],['／','直線'],['✎','ペン'],['Ｕ','下線'],['▰','蛍光'],['○','図形'],['語','語句解説'],['消','消しゴム'],['↶','元に戻す'],['＋','その他']];
const MATERIALS=['第14課 スライド','第10課 復習','建設専門語彙'];

export function OnlineClassroom(){
 const {width}=useRoyalPositioning(); const wide=width>=900;
 const [tool,setTool]=useState('選択'); const [color,setColor]=useState('#e45469'); const [mic,setMic]=useState(true); const [camera,setCamera]=useState(true);
 const [videos,setVideos]=useState(true); const [materials,setMaterials]=useState(wide); const [presenting,setPresenting]=useState(false); const [tools,setTools]=useState(true);
 return <View style={s.screen}><SafeAreaView style={s.safe} edges={['top','left','right']}>
  <View style={s.header}>
   <RoyalBackButton onPress={()=>router.back()} />
   <View style={s.classInfo}><Text style={s.classTitle}>N5 基礎クラス A</Text><Text style={s.classLesson}>第14課・て形と依頼表現</Text></View>
   <View style={s.live}><View style={s.liveDot}/><Text style={s.liveText}>授業中 00:42:18</Text></View>
  </View>
  <View style={s.quickBar}>
   <Pressable onPress={()=>setVideos(!videos)} style={s.quickButton}><Text style={s.quickText}>{videos?'▾':'▸'} 参加者</Text></Pressable>
   <Pressable onPress={()=>setMaterials(!materials)} style={s.quickButton}><Text style={s.quickText}>本 教材</Text></Pressable>
   <Pressable onPress={()=>setTools(!tools)} style={s.quickButton}><Text style={s.quickText}>✎ 注釈</Text></Pressable>
   <Pressable onPress={()=>setPresenting(!presenting)} style={[s.quickButton,presenting&&s.quickActive]}><Text style={[s.quickText,presenting&&s.quickActiveText]}>{presenting?'■ 提示中':'▶ 提示モード'}</Text></Pressable>
   <Pressable onPress={()=>Alert.alert('画面表示','ホワイトボードを全画面で表示します。')} style={s.quickButton}><Text style={s.quickText}>⛶ 全画面</Text></Pressable>
  </View>
  {videos?<ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={s.videoRow}>{PARTICIPANTS.map((name,i)=><View key={name} style={[s.videoTile,i===0&&s.teacherVideo]}><View style={s.face}><Text style={s.faceText}>{name.slice(0,1)}</Text></View><Text style={s.videoName}>{name}</Text><Text style={s.videoState}>{i===2?'マイクOFF':'● 接続中'}</Text>{i===0?<Text style={s.teacherMark}>教師</Text>:null}</View>)}<Pressable style={s.moreVideo}><Text style={s.moreNumber}>＋2</Text><Text style={s.moreText}>参加者一覧</Text></Pressable></ScrollView>:null}
  <View style={[s.workspace,wide&&s.workspaceWide]}>
   {materials?<View style={[s.sidePanel,!wide&&s.sidePanelMobile]}><View style={s.sideHeader}><Text style={s.sideTitle}>開いている教材</Text>{!wide?<Pressable onPress={()=>setMaterials(false)}><Text style={s.close}>×</Text></Pressable>:null}</View>{MATERIALS.map((x,i)=><Pressable key={x} style={[s.material,i===0&&s.materialActive]}><Text style={s.materialIcon}>{i===2?'専':'本'}</Text><Text style={s.materialText}>{x}</Text></Pressable>)}<Pressable style={s.addMaterial}><Text style={s.addMaterialText}>＋ 教材を追加</Text></Pressable></View>:null}
   {tools&&wide?<View style={s.toolDock}>{TOOLS.map(([icon,label])=><Pressable key={label} onPress={()=>setTool(label)} style={[s.dockTool,tool===label&&s.toolActive]}><Text style={[s.dockIcon,tool===label&&s.toolIconActive]}>{icon}</Text><Text style={[s.dockLabel,tool===label&&s.toolLabelActive]}>{label}</Text></Pressable>)}</View>:null}
   <View style={s.boardShell}>
    <View style={s.boardTop}><Text style={s.boardPage}>第14課　Vてください</Text><View style={s.boardTopRight}><Text style={s.saved}>✓ 保存済み</Text><Text style={s.boardPageNumber}>3 / 18</Text></View></View>
    <View style={s.board}>
     <Text style={s.boardHeading}>依頼・指示を伝える</Text><View style={s.rule}/><Text style={s.boardPattern}>Vて形 ＋ ください</Text>
     <View style={s.example}><Text style={s.exampleJa}>ここに 名前を 書いてください。</Text><View style={[s.underline,{backgroundColor:color}]}/><Text style={s.exampleNote}>相手に丁寧に行動を依頼する表現</Text></View>
     <View style={s.examples}><Text style={s.smallExample}>ドアを 開けてください。</Text><Text style={s.smallExample}>もう一度 言ってください。</Text><Text style={s.smallExample}>この ボタンを 押してください。</Text></View>
     <View style={s.annotation}><Text style={s.annotationTitle}>語句解説</Text><Text style={s.annotationText}>名前（なまえ）＝ 人を区別するための呼び方</Text></View>
    </View>
    <View style={s.pageControls}><Pressable style={s.pageButton}><Text style={s.pageButtonText}>‹ 前へ</Text></Pressable><Text style={s.zoom}>−　100%　＋　画面に合わせる</Text><Pressable style={s.pageButton}><Text style={s.pageButtonText}>次へ ›</Text></Pressable></View>
   </View>
  </View>
  {tools&&!wide?<ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={s.mobileTools}>{TOOLS.map(([icon,label])=><Pressable key={label} onPress={()=>setTool(label)} style={[s.mobileTool,tool===label&&s.toolActive]}><Text style={[s.toolIcon,tool===label&&s.toolIconActive]}>{icon}</Text><Text style={[s.toolLabel,tool===label&&s.toolLabelActive]}>{label}</Text></Pressable>)}<View style={s.colors}>{['#e45469','#f2c84b','#39a96b','#3f86d9','#222'].map(c=><Pressable key={c} onPress={()=>setColor(c)} style={[s.color,{backgroundColor:c},color===c&&s.colorActive]}/>)}</View></ScrollView>:null}
  <View style={s.meetingControls}><Pressable onPress={()=>setMic(!mic)} style={[s.meetingButton,!mic&&s.meetingOff]}><Text style={s.meetingText}>{mic?'音':'×'} マイク</Text></Pressable><Pressable onPress={()=>setCamera(!camera)} style={[s.meetingButton,!camera&&s.meetingOff]}><Text style={s.meetingText}>{camera?'映':'×'} カメラ</Text></Pressable><Pressable onPress={()=>Alert.alert('参加者','参加者、挙手、出席状況を表示します。')} style={s.meetingButton}><Text style={s.meetingText}>人 参加者</Text></Pressable><Pressable onPress={()=>Alert.alert('授業を終了','全員の接続を終了し、出席・ホワイトボード・課題状況を保存します。')} style={s.endButton}><Text style={s.endText}>授業終了</Text></Pressable></View>
 </SafeAreaView></View>
}
const s=StyleSheet.create({
 screen:{flex:1,backgroundColor:'#132229'},safe:{flex:1},header:{minHeight:64,paddingHorizontal:14,flexDirection:'row',alignItems:'center',backgroundColor:'#1f333b'},headerButton:{minHeight:48,minWidth:70,justifyContent:'center'},headerButtonText:{color:'#e2f0f4',fontSize:15,fontWeight:'900'},classInfo:{flex:1,alignItems:'center'},classTitle:{color:'#fff',fontSize:18,fontWeight:'900'},classLesson:{marginTop:3,color:'#b9ccd3',fontSize:13,fontWeight:'700'},live:{paddingHorizontal:11,paddingVertical:9,flexDirection:'row',alignItems:'center',borderRadius:11,backgroundColor:'#30474f'},liveDot:{width:9,height:9,marginRight:7,borderRadius:5,backgroundColor:'#39c77d'},liveText:{color:'#dcf8e9',fontSize:12,fontWeight:'900'},
 quickBar:{minHeight:50,paddingHorizontal:8,flexDirection:'row',alignItems:'center',gap:6,backgroundColor:'#263c44'},quickButton:{minHeight:38,paddingHorizontal:11,borderRadius:9,alignItems:'center',justifyContent:'center',backgroundColor:'#344d56'},quickText:{color:'#e2edf0',fontSize:12,fontWeight:'900'},quickActive:{backgroundColor:'#dfeef4'},quickActiveText:{color:'#245c70'},
 videoRow:{padding:8,gap:8,backgroundColor:'#172a31'},videoTile:{width:148,height:90,overflow:'hidden',borderRadius:11,borderWidth:1,borderColor:'#40565f',alignItems:'center',justifyContent:'center',backgroundColor:'#2d4149'},teacherVideo:{borderWidth:2,borderColor:'#4ecb84'},face:{width:40,height:40,borderRadius:20,alignItems:'center',justifyContent:'center',backgroundColor:'#69828c'},faceText:{color:'#fff',fontSize:17,fontWeight:'900'},videoName:{position:'absolute',left:8,bottom:7,color:'#fff',fontSize:12,fontWeight:'900'},videoState:{position:'absolute',right:7,bottom:7,color:'#9de6bd',fontSize:10,fontWeight:'800'},teacherMark:{position:'absolute',right:6,top:6,paddingHorizontal:7,paddingVertical:3,overflow:'hidden',borderRadius:6,color:'#fff',backgroundColor:'#31a66d',fontSize:10,fontWeight:'900'},moreVideo:{width:98,height:90,borderRadius:11,alignItems:'center',justifyContent:'center',backgroundColor:'#293c44'},moreNumber:{color:'#fff',fontSize:21,fontWeight:'900'},moreText:{marginTop:4,color:'#bacbd1',fontSize:11,fontWeight:'800'},
 workspace:{minHeight:0,flex:1,padding:6},workspaceWide:{flexDirection:'row',gap:7},sidePanel:{width:210,padding:13,borderRadius:12,backgroundColor:'#203239'},sidePanelMobile:{position:'absolute',zIndex:5,left:8,top:8,bottom:8,width:245,shadowColor:'#000',shadowOpacity:.35,shadowRadius:15},sideHeader:{marginBottom:11,flexDirection:'row',justifyContent:'space-between'},sideTitle:{color:'#d6e5e9',fontSize:15,fontWeight:'900'},close:{color:'#fff',fontSize:24,fontWeight:'900'},material:{minHeight:58,marginBottom:9,padding:9,flexDirection:'row',alignItems:'center',borderRadius:10,backgroundColor:'#2b4048'},materialActive:{borderWidth:2,borderColor:'#48b8d7',backgroundColor:'#294c59'},materialIcon:{width:32,height:32,marginRight:9,paddingTop:7,overflow:'hidden',borderRadius:8,color:'#e5f3f7',backgroundColor:'#46616b',fontSize:12,fontWeight:'900',textAlign:'center'},materialText:{flex:1,color:'#eef6f8',fontSize:13,lineHeight:19,fontWeight:'800'},addMaterial:{paddingVertical:12,borderRadius:9,borderWidth:1,borderStyle:'dashed',borderColor:'#6c8791'},addMaterialText:{color:'#c0d1d7',fontSize:13,fontWeight:'800',textAlign:'center'},
 toolDock:{width:82,padding:5,gap:5,borderRadius:12,backgroundColor:'#203239'},dockTool:{minHeight:55,borderRadius:9,alignItems:'center',justifyContent:'center',backgroundColor:'#2b4149'},toolActive:{borderWidth:2,borderColor:'#50b7d2',backgroundColor:'#315b69'},dockIcon:{color:'#d0e0e5',fontSize:18,fontWeight:'900'},dockLabel:{marginTop:3,color:'#b6c9d0',fontSize:10,fontWeight:'800'},toolIconActive:{color:'#fff'},toolLabelActive:{color:'#fff'},
 boardShell:{minWidth:0,flex:1,overflow:'hidden',borderRadius:13,backgroundColor:'#dfe5e7'},boardTop:{minHeight:46,paddingHorizontal:14,flexDirection:'row',alignItems:'center',justifyContent:'space-between',backgroundColor:'#f4f6f6'},boardPage:{color:'#314b56',fontSize:15,fontWeight:'900'},boardTopRight:{flexDirection:'row',alignItems:'center',gap:12},saved:{color:'#2d875a',fontSize:12,fontWeight:'900'},boardPageNumber:{color:'#63777f',fontSize:13,fontWeight:'800'},board:{flex:1,padding:22,backgroundColor:'#e8e2d6'},boardHeading:{color:'#243f4a',fontSize:26,fontWeight:'900'},rule:{width:68,height:5,marginTop:9,borderRadius:3,backgroundColor:'#4aaac7'},boardPattern:{marginTop:17,color:'#286b83',fontSize:29,fontWeight:'900'},example:{marginTop:20,padding:18,borderRadius:13,backgroundColor:'#eef7fa'},exampleJa:{color:'#203c47',fontSize:23,lineHeight:31,fontWeight:'900'},underline:{width:250,maxWidth:'90%',height:6,marginTop:7,borderRadius:3},exampleNote:{marginTop:11,color:'#4e6974',fontSize:15,lineHeight:22,fontWeight:'700'},examples:{marginTop:17,gap:10},smallExample:{color:'#304f5b',fontSize:18,lineHeight:25,fontWeight:'800'},annotation:{position:'absolute',right:20,bottom:18,maxWidth:'55%',padding:13,borderRadius:12,borderWidth:2,borderColor:'#efbc3e',backgroundColor:'#fff8d9'},annotationTitle:{color:'#806617',fontSize:14,fontWeight:'900'},annotationText:{marginTop:4,color:'#594915',fontSize:14,lineHeight:21,fontWeight:'800'},pageControls:{minHeight:48,paddingHorizontal:11,flexDirection:'row',alignItems:'center',justifyContent:'space-between'},pageButton:{minHeight:36,paddingHorizontal:13,borderRadius:8,alignItems:'center',justifyContent:'center',backgroundColor:'#c4d0d4'},pageButtonText:{color:'#314e59',fontSize:13,fontWeight:'900'},zoom:{color:'#455f69',fontSize:12,fontWeight:'800'},
 mobileTools:{padding:7,gap:6,backgroundColor:'#203239'},mobileTool:{width:68,height:60,borderRadius:10,alignItems:'center',justifyContent:'center',backgroundColor:'#2b4149'},toolIcon:{color:'#d0e0e5',fontSize:18,fontWeight:'900'},toolLabel:{marginTop:4,color:'#b6c9d0',fontSize:11,fontWeight:'800'},colors:{paddingHorizontal:8,flexDirection:'row',alignItems:'center',gap:7},color:{width:28,height:28,borderRadius:14},colorActive:{borderWidth:3,borderColor:'#fff'},
 meetingControls:{minHeight:62,padding:8,flexDirection:'row',justifyContent:'center',gap:8,backgroundColor:'#203239'},meetingButton:{minHeight:44,paddingHorizontal:14,borderRadius:10,alignItems:'center',justifyContent:'center',backgroundColor:'#344c55'},meetingOff:{backgroundColor:'#88434b'},meetingText:{color:'#fff',fontSize:13,fontWeight:'900'},endButton:{minHeight:44,paddingHorizontal:18,borderRadius:10,alignItems:'center',justifyContent:'center',backgroundColor:'#c94c5d'},endText:{color:'#fff',fontSize:13,fontWeight:'900'}
});
