"""Editorial concept inventory. No source prose or images are redistributed."""
import json,hashlib,html
from pathlib import Path
R=Path(__file__).resolve().parents[1]
rt=json.loads((R/'src/data/kaigo/atomic-supplements.json').read_text())
points={p['id']:p['explanationVi'] for u in rt['units'] for p in u['points']}
days={i:d['day'] for d in rt['days'] for i in d['unitIds']}
rows=[]
def atoms(page,kind,key,n,concepts,qualification=None):
    pid=f'kaigo-atomic-{key}-{n}';assert pid in points
    for concept in concepts.split(';'):
        rows.append(dict(id=f'foundation-atom-{len(rows)+1:03}',printedPage=page,pdfPage=page+2,kind=kind,conceptVi=concept.strip(),runtimePointId=pid,runtimeField='points[].explanationVi',runtimeDay=days['kaigo-atomic-'+key],appEquivalentVi=points[pid],visualPageChecked=True,status='meaning-linked-qualified' if qualification else 'meaning-linked-ai-editorial',qualificationVi=qualification,humanReviewed=False))
atoms(10,'prose','dignity',9,'Chuyên môn chăm sóc hỗ trợ đời sống khi cao tuổi hoặc khuyết tật')
atoms(10,'prose','dignity',1,'Từng người có giá trị cá nhân;Cần chăm sóc vẫn giữ nhân quyền;Người dùng làm chủ cách sống')
atoms(10,'prose','dignity',6,'Cách sống tùy thói quen và giá trị cá nhân;Không lấy giá trị nhân viên làm chuẩn')
atoms(11,'caption-and-prose','dignity',6,'Có nhiều cách sống trong cộng đồng')
atoms(11,'prose','dignity',2,'QOL xét sự hài lòng;QOL xét hạnh phúc;QOL xét ý nghĩa sống;QOL gồm sự phong phú tinh thần')
atoms(12,'prose','dignity',3,'Bình thường hóa bảo vệ nhân quyền;Đời sống không bị định kiến khuyết tật;Cùng sống trong cộng đồng theo cách riêng')
atoms(12,'prose','dignity',10,'Hỗ trợ giữa người có và không có khuyết tật')
atoms(12,'prose','dignity',4,'Tự lựa chọn cách sống;Tự lập về thể chất;Tự lập trong quyết định;Quyết định phù hợp giá trị sống trước đây')
atoms(13,'prose-and-dialogue-meaning','dignity',4,'Hỗ trợ theo khả năng còn lại;Tôn trọng yêu cầu riêng;Giúp tăng việc tự làm;Ví dụ hình chọn trang phục thuộc quyết định người dùng')
atoms(14,'prose','dignity',6,'Văn hóa quốc gia ảnh hưởng cách sống;Phong tục ảnh hưởng cách sống;Khả năng làm việc nhà liên quan đời sống')
atoms(14,'figure-label','dignity',7,'Thức dậy;Thay đồ;Ăn uống;Đi dạo;Uống trà;Tắm;Đi ngủ;Buổi sáng và buổi tối thể hiện nhịp ngày')
atoms(14,'prose','dignity',7,'Rửa mặt;Bài tiết;Giải trí trong nhịp sinh hoạt')
atoms(14,'prose','dignity',5,'Nhịp sống khác nhau;Sức khỏe liên quan sinh hoạt;Nơi ở liên quan sinh hoạt;Gia đình liên quan sinh hoạt;Cộng đồng và xã hội liên quan sinh hoạt')
atoms(14,'prose-and-callout','dignity',8,'Chăm sóc nâng đỡ cách sống riêng;Khơi gợi động lực khi cần trợ giúp;Luôn xét an toàn;Người chăm sóc hỗ trợ đời sống hàng ngày','Giảm chủ động là khả năng cần tìm hiểu, không kết luận mọi người cần chăm sóc đều tiêu cực.')
atoms(16,'prose','risk-observation',1,'Nhận biết thay đổi qua quan sát')
atoms(16,'prose','team-roles',4,'Phối hợp nhiều nghề vì cuộc sống người dùng mong muốn')
atoms(16,'prose','dignity',9,'Sử dụng khả năng còn lại để hỗ trợ','Nâng đỡ sinh hoạt nhằm duy trì khả năng; không hứa mọi tình trạng sẽ không xấu đi.')
atoms(16,'prose','privacy-abuse',1,'Riêng tư khi tắm;Riêng tư khi bài tiết;Che cơ thể để giảm xấu hổ;Tuổi là thông tin cá nhân;Địa chỉ là thông tin cá nhân;Bệnh sử là thông tin cá nhân')
atoms(16,'prose','privacy-abuse',6,'Chia sẻ thông tin cần căn cứ và phạm vi;Internet và mạng xã hội là kênh cần bảo vệ riêng tư','Đồng ý không phải căn cứ duy nhất trong mọi tình huống; áp dụng quy trình và căn cứ phù hợp, không cản thông báo bắt buộc.')
atoms(17,'prose','privacy-abuse',2,'Hạn chế thân thể tước tự do')
atoms(17,'prose','privacy-abuse',5,'Hạn chế vận động làm giảm chức năng cơ thể;Ép buộc có thể làm tình trạng người sa sút trí tuệ khó hơn','Không suy chắc tiến triển bệnh từ một hành vi; nêu nguy cơ suy giảm chức năng và tăng bất an, lú lẫn/BPSD.')
atoms(17,'figure-caption','privacy-abuse',2,'Buộc cơ thể hoặc tay chân;Rào giường ngăn tự xuống;Khóa phòng;Đai ngăn đứng dậy;Thuốc quá mức để khống chế')
atoms(18,'prose','privacy-abuse',8,'Lạm dụng xâm hại nhân quyền')
atoms(18,'figure-caption','privacy-abuse',7,'Bạo lực gây hại thân thể;Lời hoặc hành vi gây tổn thương tâm lý;Lời hoặc hành vi gây sợ;Bỏ cung cấp bữa ăn;Bỏ chăm sóc cần thiết;Chiếm lợi tài sản;Xâm hại tình dục')
atoms(19,'figure-label','team-roles',4,'Người dùng ở trung tâm nhóm;Người chăm sóc;Care manager;Nhân viên công tác xã hội;Nhóm đời sống và chăm sóc')
atoms(19,'figure-label','team-roles',1,'Bác sĩ;Điều dưỡng;Nhóm y tế')
atoms(19,'figure-label','team-roles',5,'Nha sĩ')
atoms(19,'figure-label','team-roles',2,'PT;OT;ST;Nhóm phục hồi chức năng')
atoms(19,'figure-label','team-roles',3,'Chuyên gia quản lý dinh dưỡng;Nhân viên nấu ăn;Nhóm ăn uống và dinh dưỡng')
atoms(19,'figure-relation','team-roles',4,'Các nghề phối hợp quanh người dùng;Mỗi nghề phát huy chuyên môn riêng')
atoms(20,'prose-and-caption','team-roles',1,'Bác sĩ chẩn đoán;Bác sĩ điều trị;Điều dưỡng chăm sóc theo chuyên môn;Điều dưỡng phối hợp khám chữa bệnh;Người chăm sóc không tự thực hiện nhiệm vụ y tế ngoài phạm vi','Nguồn nêu nguyên tắc chung; không biến thành kết luận pháp lý rằng mọi việc có yếu tố y tế luôn cấm trong mọi hoàn cảnh.')
atoms(20,'prose-and-caption','team-roles',2,'PT phục hồi vận động đi bộ;OT hỗ trợ hoạt động sinh hoạt;ST hỗ trợ nói;ST hỗ trợ nuốt')
atoms(21,'prose-and-caption','team-roles',7,'Chuyên gia dinh dưỡng xây thực đơn;Cân bằng dinh dưỡng;Năng lượng theo nhu cầu;Dạng bữa ăn theo nhu cầu')
atoms(21,'prose-and-caption','team-roles',4,'Care manager tư vấn điều phối dịch vụ;Công tác xã hội tư vấn điều phối')
atoms(21,'prose','team-roles',8,'Lập kế hoạch hỗ trợ dùng dịch vụ')
atoms(21,'caption','team-roles',6,'Thảo luận cùng người dùng;Liên hệ và điều chỉnh với gia đình')
atoms(22,'prose-and-figure-label','care-process',4,'Dịch vụ trợ giúp tại nhà;Dịch vụ chăm sóc trong ngày;Cơ sở phúc lợi chăm sóc người cao tuổi;Nhà dưỡng lão đặc biệt')
atoms(22,'figure-arrow','care-process',1,'Nhân viên tới nhà người dùng;Người dùng từ nhà tới và về cơ sở ban ngày;Người dùng sống tại cơ sở cư trú')
atoms(23,'prose','care-process',5,'Quy trình là tư duy tổ chức hỗ trợ từng người;Mục đích là cách sống mong muốn;Kế hoạch cho từng cá nhân;Ghi mục tiêu cụ thể;Ghi nội dung hỗ trợ cụ thể')
atoms(23,'figure-caption-and-arrow','care-process',2,'Thu thập thông tin;Phân tích vấn đề sinh hoạt;Lập kế hoạch;Thực hiện theo kế hoạch')
atoms(23,'figure-caption-and-arrow','care-process',3,'Đánh giá sự phù hợp;Đánh giá mục tiêu đạt hay chưa')
atoms(23,'figure-arrow','care-process',5,'Đánh giá quay lại bước xem xét thông tin và điều chỉnh')
atoms(24,'prose-and-dialogue-meaning','risk-observation',1,'Tương tác để hiểu tình trạng;Quan sát lời nói;Quan sát hành động;So với thường ngày')
atoms(24,'prose-and-callout','risk-observation',4,'Ghi dữ kiện quan sát;Chia sẻ dữ kiện cho nhóm;Cảm giác nóng khác số nhiệt độ thực đo;Quan sát phục vụ điều chỉnh sinh hoạt')
atoms(25,'figure-caption','risk-observation',2,'Khả năng hôm nay khác việc thường làm;Dép tuột hoặc trơn;Gấu quần dài gây vấp;Dụng cụ hỏng;Kiểm dụng cụ trước dùng')
atoms(25,'prose','risk-observation',6,'Nguy cơ khi di chuyển hoặc chuyển vị trí;Nguy cơ theo tuổi cao hoặc khuyết tật cần đánh giá')
atoms(26,'figure-caption','risk-observation',2,'Sàn ướt gây trượt;Dây điện gây vấp')
atoms(26,'prose','risk-observation',3,'Quản lý rủi ro dự đoán và phòng tai nạn;Ghi chính xác để phòng lặp;Suýt xảy ra vẫn cần xem xét')
atoms(26,'figure-event-and-arrow','risk-observation',5,'Ca chuyển giường sang xe lăn suýt ngã;Kiểm nguyên nhân;Phanh chưa cài nếu đã xác minh;Ghi nguyên nhân xác minh;Tổ chức kiểm phanh lần sau;Chia sẻ biện pháp cho nhóm')
atoms(27,'prose','infection-chain',1,'Virus là nhóm tác nhân;Vi khuẩn là nhóm tác nhân;Nấm là nhóm tác nhân;Ký sinh trùng là nhóm tác nhân;Sốt cần báo;Nôn cần báo;Tiêu chảy cần báo;Đau bụng cần báo;Phát ban cần báo;Sắc mặt thay đổi cần báo')
atoms(27,'prose-and-callout','infection-chain',11,'Sinh hoạt tập thể tăng cơ hội lây;Sức đề kháng yếu tăng nguy cơ;Khỏe mạnh không loại trừ nhiễm','Thay cách hiểu hình khỏe/ốm tuyệt đối bằng nguy cơ tương đối; không bỏ phòng ngừa khi khỏe.')
atoms(27,'prose','infection-chain',2,'Tác nhân liên hệ nguồn và đường tới cơ thể có thể nhiễm')
atoms(28,'figure-label','infection-chain',7,'Nguồn có vi sinh vật;Chất bài tiết có thể mang nguồn;Tay là phương tiện đường truyền;Đồ vật là phương tiện đường truyền;Thức ăn là phương tiện đường truyền;Người là túc chủ;Động vật là túc chủ')
atoms(28,'figure-arrow','infection-chain',2,'Loại hoặc giảm nguồn;Chặn đường lây;Hỗ trợ sức khỏe túc chủ;Mục tiêu cắt chuỗi lây')
atoms(28,'prose','infection-chain',6,'Tránh đưa tác nhân vào;Tránh mang tác nhân ra;Tránh lan bên trong')
atoms(28,'figure-caption','infection-chain',3,'Giọt bắn;Cúm là ví dụ giọt bắn;Không khí;Lao là ví dụ không khí;Sởi là ví dụ không khí;Tiếp xúc;Noro là ví dụ tiếp xúc;O157 là ví dụ tiếp xúc','Ví dụ học không thay phân tích tác nhân, nhiều đường lây và hướng dẫn hiện hành.')
atoms(29,'figure-caption-and-prose','infection-chain',8,'Máu;Nước bọt;Dịch mũi;Chất nôn;Nước tiểu;Phân;Da tổn thương;Niêm mạc;Xét nguy cơ cả khi chưa có chẩn đoán')
atoms(29,'prose','infection-chain',4,'Không tiếp xúc tay trần với vật liệu có nguy cơ;PPE theo phơi nhiễm','Không sao chép yêu cầu đeo găng cho mọi việc; phòng ngừa chuẩn theo nguy cơ thực tế.')
atoms(29,'figure-label','infection-chain',9,'Kính bảo hộ;Tạp dề nhựa;Mũ')
atoms(29,'figure-label','infection-chain',4,'Găng;Khẩu trang')
atoms(30,'figure-caption','infection-chain',5,'Khẩu trang che mũi;Khẩu trang che miệng và cằm;Tháo giữ mặt bẩn trong;Vứt nơi quy định;Găng không thay vệ sinh tay')
atoms(30,'prose','infection-chain',10,'Thay găng theo lần chăm sóc;Vệ sinh tay sau tháo')
atoms(31,'figure-region','hand-coverage',1,'Đầu ngón;Vùng móng;Kẽ ngón;Mu tay;Gốc ngón cái;Cổ tay;Hai mặt và cả hai tay')
atoms(31,'prose','hand-coverage',2,'Rửa bằng xà phòng và nước chảy')
atoms(31,'prose','hand-coverage',3,'Chà với dung dịch phù hợp')
atoms(32,'figure-action','hand-coverage',2,'Làm ướt;Lấy xà phòng đủ phủ;Tạo bọt')
atoms(32,'figure-action','hand-coverage',5,'Lòng tay chà lòng tay;Lòng tay chà mu tay;Đổi bên')
atoms(32,'figure-action','hand-coverage',6,'Đan ngón chà kẽ;Cả hai tay')
atoms(32,'figure-action','hand-coverage',7,'Bao và chà ngón cái;Đầu ngón chà lòng tay đối diện;Đổi bên đầu ngón và ngón cái')
atoms(32,'figure-action','hand-coverage',8,'Chà cổ tay;Xả kỹ nước;Lau bằng khăn giấy;Làm khô hoàn toàn')
atoms(32,'callout','hand-coverage',9,'Nhẫn có thể giữ hoặc che bẩn;Đồng hồ có thể giữ hoặc che bẩn','Chuẩn bị theo chính sách cơ sở; không xem rửa quanh đồ trang sức là đủ.')
atoms(33,'figure-action','hand-coverage',3,'Bẩn nhìn thấy phải rửa trước')
atoms(33,'figure-action','hand-coverage',9,'Khum tay nhận dung dịch;Dùng đủ lượng theo sản phẩm')
atoms(33,'figure-action','hand-coverage',5,'Chà hai lòng tay;Chà mu tay và đổi bên')
atoms(33,'figure-action','hand-coverage',6,'Chà mặt sau ngón;Chà kẽ bằng đan ngón')
atoms(33,'figure-action','hand-coverage',7,'Chà đầu ngón và móng;Bao ngón cái rồi chà xoay;Thực hiện hai tay')
atoms(33,'figure-action','hand-coverage',8,'Chà cổ tay;Chà tới khô;Không xả dung dịch chà tay')
atoms(34,'prose-and-figure-contrast','body-mechanics',9,'Sức khỏe nhân viên ảnh hưởng hỗ trợ;Phòng đau lưng;Tư thế làm việc ảnh hưởng tải lưng','Cơ học không bảo đảm ngăn mọi đau lưng; cần phối hợp dụng cụ, tổ chức và sức khỏe.')
atoms(35,'prose','body-mechanics',11,'An toàn người dùng và giảm tải người hỗ trợ;Cơ học cơ thể xét liên hệ xương và cơ')
atoms(35,'definition-and-figure','body-mechanics',1,'Chân đế nối vùng tiếp xúc nền;Hai bàn chân tạo vùng nâng đỡ;Mở rộng chân đế;Hạ trọng tâm')
atoms(35,'callout','body-mechanics',6,'Điểm gậy trên nền có thể mở chân đế','Tăng vùng nâng đỡ không bảo đảm không ngã.')
atoms(36,'figure-contrast','body-mechanics',2,'Công việc gần thân giảm tải;Không chỉ dùng cơ lưng;Dùng cơ đùi;Dùng cơ hông hoặc mông')
atoms(37,'figure-contrast-and-callout','body-mechanics',7,'Thu gọn tay chân phù hợp;Cơ thể được hỗ trợ gọn hơn;Chuyển trọng tâm ngang;Dùng toàn thân cho dịch chuyển','Không buộc hoặc ép khớp; không coi thu gọn thân luôn giảm chân đế đứng trong mọi tư thế.')
atoms(37,'figure-contrast-and-callout','body-mechanics',4,'So sánh kéo và đẩy trong một phương án;Ma sát cần được xét','Nguồn khái quát kéo giảm ma sát: không dạy là định luật. Cần xét bề mặt, lực, thiết bị; không kéo lê da.')
atoms(38,'figure-contrast','body-mechanics',3,'Hướng mũi chân theo di chuyển;Tránh xoắn thân dưới tải')
atoms(38,'figure-and-callout','body-mechanics',8,'Điểm tựa;Nguyên lý đòn bẩy;Lực và khoảng cách ảnh hưởng mô-men','Không dùng nguyên lý làm chỉ dẫn tự chọn điểm tì hay chuyển người.')
atoms(39,'prose-and-figure-label','body-mechanics',9,'Xét khả năng còn lại người dùng;Máy nâng;Tấm trượt;Cơ học cơ thể;Vận động vừa sức;Dinh dưỡng;Nghỉ ngơi')
atoms(39,'prose-and-figure-caption','body-mechanics',10,'Giữ nhịp ăn;Giữ nhịp ngủ;Cách giảm căng thẳng phù hợp bản thân;Trao đổi người có kinh nghiệm;Trao đổi bạn hoặc đồng nghiệp;Không giữ mọi bất an một mình')
atoms(40,'prose','disaster',1,'Động đất;Bão;Hỏa hoạn;Hệ phối hợp cơ sở và cộng đồng')
atoms(40,'caption-and-prose','disaster',5,'Chuẩn bị lúc bình thường;Giảm lúng túng;Diễn tập ứng phó;Phân công hỗ trợ')
atoms(40,'unlabelled-figure-concept','disaster',4,'Nước;Thực phẩm;Đèn;Radio;Pin;Đồ sơ cứu;Vật tư theo nhu cầu;Đồ giữ ấm;Quần áo;Vệ sinh;Bảo vệ đầu','Các nhóm xác định ở mức chức năng; hình không ghi tên từng vật, nên không kết luận nhận diện mọi vật đã hoàn tất.')
open_items=[dict(printedPage=31,pdfPage=33,kind='figure-legend',status='requires-detailed-visual-region-check',conceptVi='Đối chiếu ranh giới từng vùng màu với hai cấp bỏ sót trong chú giải; nội dung đã dạy đủ vùng nhưng chưa chứng minh phân loại từng vùng màu.'),dict(printedPage=40,pdfPage=42,kind='unlabelled-figure',status='requires-object-by-object-confirmation',conceptVi='Xác minh từng vật không có nhãn trong hình chuẩn bị thảm họa; không tự gán tên cho các vật nhỏ chưa rõ.')]
report=dict(version=1,date='2026-10-09',sourceSha256='997bf386ba8344e19c644c3cbd6ae2d40760bfb32ed882db999ad8e17068aa54',scopePrintedPages=list(range(10,41)),visualPagesChecked=list(range(10,41)),nonTeachingPages=[15],atoms=rows,counts=dict(identifiedAtoms=len(rows),meaningLinked=len(rows),qualified=sum(bool(x['qualificationVi']) for x in rows),openVisualItems=len(open_items)),openItems=open_items,fullScopeAtomInventoryCertified=False,wholeDocumentCoveragePercent=None,allSourceKnowledgeFullyCovered=False,humanReviewed=False,domainReviewed=False,releaseReady=False,runtimeSha256=hashlib.sha256((R/'src/data/kaigo/atomic-supplements.json').read_bytes()).hexdigest(),sourceNotesVi='Mô tả khái niệm do biên tập lại; nhãn chung giữ đúng nghĩa. Không sao chép câu nguồn, bố cục hay hình nguồn. Liên kết là đánh giá nghĩa ở mức AI, chưa chứng nhận chuyên môn.')
(R/'docs/ssw-workspace/kaigo/reviews/foundation-source-atoms-2026-10-09.json').write_text(json.dumps(report,ensure_ascii=False,indent=2)+'\n')
print(json.dumps(report['counts']))
