"""Excretion source concepts mapped to new authored explanations; not a transcript."""
import json,hashlib
from pathlib import Path
R=Path(__file__).resolve().parents[1]
rt=json.loads((R/'src/data/kaigo/atomic-supplements.json').read_text())
points={p['id']:p['explanationVi'] for u in rt['units'] for p in u['points']}
days={i:d['day'] for d in rt['days'] for i in d['unitIds']}; rows=[]
def atoms(page,kind,key,n,concepts,qualification=None):
 pid=f'kaigo-atomic-{key}-{n}';assert pid in points
 for c in concepts.split(';'):
  rows.append(dict(id=f'excretion-atom-{len(rows)+1:03}',printedPage=page,pdfPage=page+2,kind=kind,conceptVi=c.strip(),runtimePointId=pid,runtimeDay=days['kaigo-atomic-'+key],appEquivalentVi=points[pid],visualPageChecked=True,qualificationVi=qualification,humanReviewed=False))
atoms(152,'prose','digestive',6,'Thải phần không cần giữ;Nước tiểu;Phân;Mồ hôi;Cacbon điôxit;Duy trì sức khỏe;Quan sát chất thải;Lý do cần hỗ trợ')
atoms(152,'emotional-callout','continence-types',10,'Xấu hổ;Hiểu cảm xúc;Cách hỗ trợ')
atoms(153,'mechanism-and-figure','urination-volume',1,'Thận;Niệu quản;Bàng quang;Niệu đạo;Đường tạo chứa thải;Đại não;Thân não;Tủy sống;Điều tiết tiểu tiện')
atoms(153,'figure-callout','urination-volume',2,'Khoảng 500ml;Khoảng 200–300ml;Cảm giác muốn tiểu','Mốc minh họa, không điều kiện được hỗ trợ.')
atoms(153,'figure-callout','urination-volume',3,'Niệu đạo nam dài hơn nữ;Tuyến tiền liệt quanh đoạn niệu đạo;Ví dụ nữ')
atoms(153,'figure-callout','urination-volume',5,'Lọc chất cần thải trong máu;Tạo nước tiểu;Chứa tạm')
atoms(154,'mechanism','digestive',7,'Phân tích tụ;Muốn đại tiện;Tín hiệu giảm khi trì hoãn')
atoms(154,'anatomy-label-and-relation','swallow-stages',2,'Khoang miệng;Nhai;Nước bọt;Chuẩn bị thức ăn')
atoms(154,'anatomy-label-and-relation','digestive',1,'Thực quản;Chuyển thức ăn;Dạ dày;Nhu động;Dịch tiêu hóa')
atoms(154,'anatomy-label-and-relation','digestive',2,'Ruột non;Hấp thu dinh dưỡng;Hấp thu nước;Đại tràng;Hình thành phân')
atoms(154,'anatomy-label-and-relation','digestive',3,'Đại tràng lên;Đại tràng ngang;Đại tràng xuống;Sigma;Trực tràng')
atoms(154,'anatomy-label-and-relation','digestive',4,'Hậu môn;Thải phân')
atoms(155,'posture-figure','digestive',8,'Thân hướng trước;Gót nhấc;Trực tràng;Hậu môn;Tư thế và đường thoát phân','Nhận diện mẫu, không yêu cầu mọi người nhón gót hoặc rặn.')
atoms(155,'reference-table','urine-reference',1,'1000–1500ml/ngày;Hơn 2000–3000ml/ngày;Đa niệu;300–500ml hoặc ít hơn;Thiểu niệu','Mốc học, không tự chẩn đoán.')
atoms(155,'reference-table','urine-reference',2,'4–6 lần/ngày;8 lần trở lên ban ngày;2 lần trở lên ban đêm;Số lần khác lượng')
atoms(155,'reference-table','urine-reference',3,'Vàng nhạt;Trong;Đục;Nâu sẫm;Đỏ')
atoms(155,'reference-table','urine-reference',5,'Không nhận thấy mùi;Amôniắc mạnh')
atoms(155,'prose','urine-reference',4,'Môi trường;Bệnh;Ảnh hưởng lượng và số lần')
atoms(156,'reference-table-and-prose','urine-reference',6,'1–2 lần/ngày;Nâu đậm;Ít hơn thường ngày;Thức ăn;Bệnh;Hình dạng;Số lần;Biết mẫu bình thường cá nhân','Không lấy nhịp sách làm chuẩn mọi người.')
atoms(156,'reference-table','urine-reference',7,'Phân đỏ;Phân đen;Phân nhạt trắng')
atoms(157,'device-table','continence-types',1,'Ghế bô;Có nhu cầu;Không tới nhà vệ sinh;Ban đêm;Bô tại giường;Nằm tại giường;Sức khỏe yếu;Khó ngồi')
atoms(157,'device-label','toilet-environment',6,'Bình tiểu kiểu nữ;Bình tiểu kiểu nam;Chọn theo cơ thể và thiết bị')
atoms(157,'device-table','continence-types',2,'Tã;Miếng thấm;Rò tiểu;Rò phân;Khó dùng nhà vệ sinh;Khó dùng ghế bô','Không mặc định dùng tã thay đánh giá nguyên nhân.')
atoms(158,'definition-and-table','continence-types',3,'Rò ngoài ý muốn;Áp lực bụng;Ho;Hắt hơi;Tiểu gấp;Không trì hoãn kịp','Không coi nhãn dịch căng thẳng là căng thẳng tâm lý.')
atoms(158,'mechanism-table','continence-types',4,'Tràn;Ứ nước tiểu;Cản đường thoát;Tuyến tiền liệt;Rò ít;Phản xạ;Tổn thương tủy;Không cảm thấy mót','Nhận diện mô tả, không chẩn đoán.')
atoms(158,'mechanism-table','continence-types',5,'Chức năng;Chưa hoàn thành thao tác;Khó định hướng;Không tìm được nhà vệ sinh')
atoms(158,'definition-and-table','continence-types',6,'Táo bón;Giảm số lần;Giảm lượng;Kéo dài so với cá nhân;Chức năng;Thực thể;Tổn thương gây cản trở','U và viêm là ví dụ nguyên nhân cản trở, không phải mọi trường hợp đều tắc.')
atoms(159,'care-bullets','continence-types',8,'Thói quen đều;Nước phù hợp;Chất xơ;Vận động;Báo khi chưa cải thiện')
atoms(159,'definition-and-care','continence-types',7,'Phân mềm;Nhiều nước;Mất nước;Da kích ứng;Tiêu chảy mới xuất hiện;Báo chuyên môn')
atoms(159,'care-bullets','continence-types',9,'Uống khi an toàn;Nhiệt độ dễ chịu;Lựa chọn đồ uống;Nước trắng;Đồ uống thể thao;Làm sạch quanh hậu môn','Hai loại đồ uống là ví dụ nguồn, không công thức bù dịch. App dạy chọn theo kế hoạch.')
atoms(159,'callout-and-prose','continence-types',10,'Căng thẳng tâm lý;Lắng nghe phàn nàn;Quan sát nước tiểu;Quan sát phân;Bất thường sức khỏe;Báo kịp thời')
atoms(160,'sequence-label-and-arrow','toilet-environment',1,'Nhận biết nhu cầu;Tới nhà vệ sinh;Kéo quần xuống;Chuẩn bị tư thế;Bài tiết;Làm sạch;Kéo quần lên;Rời nhà vệ sinh;Quan hệ trước sau;Nhiều chức năng phối hợp')
atoms(160,'dignity-prose','continence-types',10,'Gánh nặng tinh thần;Giữ phẩm giá')
atoms(161,'care-bullets','toilet-environment',4,'Giữ thói quen;Mùi;Phương pháp;Dụng cụ;Vệ sinh')
atoms(161,'care-bullets','continence-types',10,'Xấu hổ khi được giúp')
atoms(161,'ppe-bullets','toilet-environment',7,'Găng;Tạp dề dùng một lần;Phòng lây nhiễm')
atoms(161,'environment-label-and-callout','toilet-environment',8,'Tay vịn chữ L;Điểm bám khi đứng;Tay vịn di động;Nâng hạ;Cửa lùa;Xe lăn tiếp cận;Nút gọi;Gọi khi khó;Gọi khi xong')
atoms(162,'example-prose-and-figure','toilet-environment',3,'Ví dụ liệt trái;Dẫn tới nơi;Bám tay khỏe;Hỗ trợ phía yếu;Kéo quần;Kéo đồ lót','Mẫu không thay đánh giá chuyển người.')
atoms(163,'example-figure-and-callout','toilet-environment',9,'Bám khi ngồi xuống;Ngồi vững;Tự kéo quần tới mức có thể;Chuẩn bị khi ngồi giảm tải đứng')
atoms(163,'example-numbered-prose','toilet-environment',10,'Nhân viên rời phòng;Đóng cửa;Tín hiệu kết thúc;Quay lại hỗ trợ','Chỉ thực hiện riêng tư cùng giám sát theo đánh giá an toàn.')
atoms(164,'example-figure-and-callout','toilet-environment',9,'Bám khi đứng;Chân khỏe lùi phù hợp;Đứng vững;Tự chỉnh quần;Kiểm đồ lót và quần')
atoms(165,'bedpan-example-prose-and-figure','toilet-environment',11,'Vật dụng;Rèm;Độ cao làm việc;Chống thấm;Gập gối;Nâng hông nếu được phép;Hạ quần;Vùng hứng giữa bô;Ổn định;Khăn che;Nâng đầu giường;Quan hệ tư thế và áp lực bụng','Không hướng dẫn rặn hoặc nâng người chưa đào tạo.')
atoms(165,'bedpan-example-prose','toilet-environment',12,'Làm sạch;Lấy bô ra')
atoms(166,'bedpan-example-prose','toilet-environment',12,'Kiểm da;Nghiêng an toàn;Lấy chống thấm;Mặc lại;Chỉnh đồ;Trả độ cao;Kiểm sức khỏe;Dọn vật dụng')
atoms(166,'urinal-example-figure-and-caption','toilet-environment',6,'Ví dụ nghiêng;Đệm lưng;Đặt bình tiểu;Vật liệu dẫn dòng;Giảm bắn','Hình khác theo cơ thể; theo thiết bị, không mặc định giới tính quyết định dụng cụ.')
atoms(167,'diaper-example-prose','diaper-fit',4,'Kiểm sức khỏe;Giải thích;Đồng ý;Vật dụng;Độ cao giường;Nghiêng;Chống thấm;Nằm ngửa;Nâng hông có điều kiện;Hạ quần;Mở tã')
atoms(167,'diaper-example-prose-and-callout','diaper-fit',5,'Rửa vùng sinh dục;Nước ấm;Kiểm nhiệt;Nhạy nhiệt;Hướng niệu đạo tới hậu môn;Ngăn đưa chất bẩn ngược;Nếp da')
atoms(168,'diaper-example-prose','diaper-fit',5,'Lau khô')
atoms(168,'diaper-example-prose-figure-footnote','diaper-fit',6,'Nghiêng;Cuộn tã;Mặt bẩn vào trong;Tã mới;Đổi tư thế;Lấy tã bẩn;Tháo găng;Chú thích giản lược để học','Không áp dụng lớp tã bẩn-sạch tiếp xúc như quy trình chống nhiễm.')
atoms(169,'diaper-example-prose-and-callout','diaper-fit',2,'Dán vừa;2–3 ngón minh họa;Vùng bụng;Vùng đùi;Siết gây ngứa','Theo sản phẩm và da; không áp số ngón mọi tã.')
atoms(169,'diaper-example-prose-and-callout','diaper-fit',3,'Mặc lại theo khả năng;Chỉnh quần áo;Chỉnh ga;Nếp nhăn;Khó chịu;Tì đè;Thông thoáng;Kiểm sức khỏe;Dọn vật dụng')
out=dict(version=1,date='2026-10-10',sourceSha256='997bf386ba8344e19c644c3cbd6ae2d40760bfb32ed882db999ad8e17068aa54',sourceBytesHashRecomputed=True,runtimeSha256=hashlib.sha256((R/'src/data/kaigo/atomic-supplements.json').read_bytes()).hexdigest(),scopePrintedPages=list(range(152,170)),visualPagesChecked=list(range(152,170)),visualInspectionMethod='PDF text layer and three six-page contact sheets; not independently certified',atoms=rows,openVisualItems=[],fullScopeAtomInventoryCertified=False,allSourceKnowledgeFullyCovered=False,wholeDocumentCoveragePercent=None,humanReviewed=False,domainReviewed=False,releaseReady=False,primaryChecks=['https://www.niddk.nih.gov/health-information/digestive-diseases/constipation/definition-facts','https://www.cdc.gov/clean-hands/hcp/clinical-safety/'])
(R/'docs/ssw-workspace/kaigo/reviews/excretion-source-atoms-2026-10-10.json').write_text(json.dumps(out,ensure_ascii=False,indent=2)+'\n')
print(json.dumps(dict(atoms=len(rows),pages=18,fullScopeAtomInventoryCertified=False)))
