"""Independent concept inventory of communication; not a source transcript."""
import json,hashlib
from pathlib import Path
R=Path(__file__).resolve().parents[1]
rt=json.loads((R/'src/data/kaigo/atomic-supplements.json').read_text())
points={p['id']:p['explanationVi'] for u in rt['units'] for p in u['points']}
days={i:d['day'] for d in rt['days'] for i in d['unitIds']}
rows=[]
def atoms(page,kind,key,n,concepts,qualification=None):
 pid=f'kaigo-atomic-{key}-{n}';assert pid in points
 for concept in concepts.split(';'):
  rows.append(dict(id=f'communication-atom-{len(rows)+1:03}',printedPage=page,pdfPage=page+2,kind=kind,conceptVi=concept.strip(),runtimePointId=pid,runtimeDay=days['kaigo-atomic-'+key],appEquivalentVi=points[pid],visualPageChecked=True,qualificationVi=qualification,humanReviewed=False))
atoms(98,'prose-and-arrow','communication',5,'Gửi thông tin;Nhận thông tin;Phản hồi hai chiều;Suy nghĩ;Cảm xúc;Tin cậy;Gia đình;Chuyên môn')
atoms(98,'prose','communication',1,'Trao đổi ý nghĩa;Hiểu nhu cầu;Không chỉ nói hết lời')
atoms(99,'figure-label','communication',2,'Lời nói;Chữ;Ngôn ngữ ký hiệu;Giao tiếp ngôn ngữ')
atoms(100,'prose-and-figure','communication',2,'Cử chỉ;Động tác tay;Biểu cảm;Tư thế;Phi ngôn ngữ','Ký hiệu không chỉ động tác tùy ý.')
atoms(101,'prose-and-figure','communication',3,'Lắng nghe kỹ;Hiểu chính xác;Đồng cảm;Nhìn từ vị trí người kia;Tiếp nhận;Tôn trọng cảm xúc')
atoms(102,'prose','communication',5,'Giao tiếp người dùng;Giao tiếp gia đình;Giao tiếp chuyên môn')
atoms(102,'prose-and-greeting-meaning','communication',6,'Giá trị riêng;Thời đại lớn lên;Môi trường sống;Cảm xúc;Suy nghĩ;Lời lịch sự','Không sao lại lời thoại chào trong hình.')
atoms(103,'prose-and-comparison','communication',4,'Câu đóng;Trả lời đơn giản;Xác nhận;Lựa chọn;Chỉ câu đóng dễ một chiều;Câu mở;Trả lời rộng;Hỏi dồn tại sao có thể gây cảm giác bị buộc tội')
atoms(103,'figure-example-meaning','communication',4,'Hai loại câu hỏi khác mục đích','Không tái tạo câu hỏi về món ăn trong nguồn.')
atoms(104,'prose-and-example-meaning','listening-consent',1,'Lặp ý;Thể hiện đang nghe;Giữ thời gian;Giữ vùng đau;Không tự kết luận','Ca nguồn không được tái tạo.')
atoms(104,'prose','nonverbal-dialogue',1,'Quan sát động tác;Quan sát nét mặt;Chọn cách giao tiếp;Kiểm ý nghĩa')
atoms(104,'prose','nonverbal-dialogue',2,'Hướng nhìn;Thể hiện lắng nghe','Không ép nhìn mắt mọi người.')
atoms(105,'figure-arrow','nonverbal-dialogue',2,'Ngang tầm mắt;Nhìn từ trên xuống có thể gây áp lực')
atoms(105,'prose','nonverbal-dialogue',3,'Giọng nhẹ;Nhịp chậm;Khoảng chờ;Gật đầu;Hưởng ứng;Theo dõi câu chuyện','Gật không tự là đồng ý hoặc hiểu.')
atoms(105,'prose-and-gesture-meaning','nonverbal-dialogue',4,'Đối diện;Khoanh tay;Bắt chéo chân;Ngả xa;Quốc gia;Văn hóa;Ý nghĩa thay đổi','Không xếp tư thế thành tính cách.')
atoms(106,'figure-posture','nonverbal-dialogue',4,'Hướng tới người dùng;Tư thế đóng có thể tạo cảm giác không lắng nghe','Hình thuận/không thuận là gợi ý theo bối cảnh.')
atoms(106,'prose','nonverbal-dialogue',5,'Khoảng cách gần;Cảm giác thân mật;Khoảng cách dễ chịu;Khác biệt văn hóa','Không dùng xu hướng Nhật hoặc quốc gia khác thay sở thích cá nhân.')
atoms(106,'prose-and-figure','nonverbal-dialogue',6,'Tiếp xúc;Thời điểm;Lực;Tần suất;Nắm tay nhẹ;Phản ứng;Hỏi trước','Không mặc định tiếp xúc được chấp nhận.')
atoms(107,'prose-and-numbered-items','listening-consent',4,'Các lựa chọn;Ích lợi;Bất lợi;Giải thích hiểu được;Người dùng quyết định;Tôn trọng lựa chọn')
atoms(107,'prose','accessible-talk',10,'Khó khăn do bệnh;Khó khăn do khuyết tật;Chọn phương thức;CNTT-TT;Kỹ năng;Mong muốn;Kiểm hiểu')
atoms(108,'prose','accessible-talk',7,'Thông tin nhìn không đủ;Khó xác định khoảng cách;Khó xác định vị trí;Đặc điểm cụ thể;Mốc âm thanh;Sờ nhận biết','Có đồng ý và an toàn.')
atoms(108,'prose-and-callout','accessible-talk',1,'Gọi tên người dùng;Giới thiệu nhân viên;Nói trước khi chạm;Biết người đang nói;Tránh làm giật mình')
atoms(108,'prose','accessible-talk',3,'Âm lượng phù hợp;Cách nói rõ')
atoms(109,'prose','accessible-talk',7,'Mốc phía người dùng;Mốc tiếng nói;Mô tả cụ thể')
atoms(109,'prose-and-figure-label','accessible-talk',2,'Vị trí đồng hồ;Chữ nổi;Đường lát xúc giác;Công cụ theo nhu cầu','Không mặc định ai cũng đọc chữ nổi.')
atoms(110,'prose','accessible-talk',9,'Có thể cô đơn;Có thể mất mát;Hỗ trợ tâm lý;Cơ hội tham gia','Không quy cảm xúc cho mọi người khó nghe.')
atoms(110,'prose-and-mouth-figure','accessible-talk',3,'Phía trước;Thấy mặt;Thấy miệng;Tai nghe tốt hơn;Nói rõ;Âm lượng vừa;Môi trường yên')
atoms(110,'figure-meaning','accessible-talk',4,'Khẩu hình','Theo kỹ năng người dùng; không tự bảo đảm hiểu.')
atoms(111,'prose-and-figure','accessible-talk',4,'Viết;Giấy;Thiết bị;CNTT;Phương thức khác âm thanh')
atoms(111,'prose-and-figure','accessible-talk',8,'Tay;Ngón tay;Mặt;Đầu và cổ;Ngôn ngữ ký hiệu;Micro;Xử lý hoặc khuếch đại;Âm tới tai','Ngôn ngữ ký hiệu có hệ riêng; trợ thính không tự chứng minh hiểu.')
atoms(112,'prose','aphasia',1,'Tổn thương hệ ngôn ngữ;Nghe hiểu;Đọc hiểu;Nói;Viết')
atoms(112,'care','accessible-talk',5,'Lời ngắn;Dễ hiểu;Câu đóng;Tranh;Cử chỉ;Không bắt bẻ lỗi nhỏ')
atoms(112,'figure-meaning','aphasia',3,'Bảng hình;Hỗ trợ khả năng còn lại','Không tái tạo bộ hình nguồn.')
atoms(113,'prose-and-figure','accessible-talk',6,'Lặp lời;Trao đổi có thể không khớp;Câu ngắn;Nói chậm;Tiếp nhận lo;Đồng cảm','Không xác nhận điều chưa có căn cứ là thật.')
atoms(114,'prose','shared-care-records',1,'Nhóm chăm sóc;Chuyên môn y tế;Thông tin chăm sóc;Thông tin y tế;Chất lượng;Phối hợp')
atoms(114,'figure-and-prose','shared-care-records',2,'Kế hoạch;Hồ sơ trường hợp;Sổ bàn giao;Họp;Trao đổi trực tiếp;Xem xét chăm sóc')
atoms(115,'prose','shared-care-records',1,'Hai mục đích: chất lượng;Hai mục đích: theo nhóm')
atoms(115,'prose','shared-care-records',3,'Ghi kịp trong ngày;Ngày giờ;Tình trạng;Hỗ trợ thực hiện;Phản ứng sau hỗ trợ','Không đợi hết ngày nếu cần báo khẩn.')
atoms(115,'comparison-table','record-handover',2,'Dữ kiện chủ quan;Trải nghiệm người dùng;Yêu cầu;Dữ kiện khách quan;Quan sát;Huyết áp;Nhiệt độ;Xét nghiệm','Số đo cần thật; chủ quan không đồng nghĩa không có giá trị.')
atoms(115,'annotated-example-meaning','shared-care-records',4,'Tách lời kể;Tách quan sát;Ghi nguồn kết luận chuyên môn','Không tái tạo ca đỏ vùng xương cùng trong nguồn.')
atoms(116,'numbered-table-and-label','record-handover',3,'When;Khi nào;Where;Ở đâu;Who;Ai;What;Việc gì;Why;Lý do;How;Cách nào','Lý do chưa biết giữ chưa biết; không sao lại ví dụ nhặt đồ tại ga.')
atoms(117,'prose','record-handover',7,'Bảo vệ dữ liệu;Giữ bí mật;Đạo đức;Mục đích;Phạm vi;Đồng ý hoặc căn cứ phù hợp','Nội dung đào tạo không thay quy trình pháp lý cụ thể.')
atoms(117,'list','record-handover',4,'Tên;Địa chỉ;Điện thoại;Ảnh')
atoms(117,'figure-warning-meaning','record-handover',7,'Không kể tùy tiện ngoài nơi làm;Không đăng Internet;Không đăng mạng xã hội;Thông tin nơi làm việc','Không tái tạo hình nguồn.')
atoms(118,'prose','record-handover',8,'Điều nhận thấy khi tiếp xúc;Tình trạng công việc;Thời gian;Địa điểm;Báo ngay khi khẩn')
atoms(118,'sender-list','record-handover',5,'Ngắn gọn;Sự thật;Suy đoán;Mức khẩn')
atoms(118,'receiver-list','shared-care-records',4,'Ghi chú;Nghe dữ kiện;Nhắc lại;Hỏi chưa rõ')
atoms(118,'prose','record-handover',9,'Xin lời khuyên;Đồng nghiệp;Chuyên môn;Chưa hiểu;Không vượt phạm vi')
review=R/'docs/ssw-workspace/kaigo/reviews'
out=dict(version=1,sourceSha256='997bf386ba8344e19c644c3cbd6ae2d40760bfb32ed882db999ad8e17068aa54',runtimeSha256=hashlib.sha256((R/'src/data/kaigo/atomic-supplements.json').read_bytes()).hexdigest(),scopePrintedPages=list(range(98,119)),visualPagesChecked=list(range(98,119)),atoms=rows,openVisualItems=[],fullScopeAtomInventoryCertified=False,allSourceKnowledgeFullyCovered=False,wholeDocumentCoveragePercent=None,humanReviewed=False,domainReviewed=False,releaseReady=False)
(review/'communication-source-atoms-2026-10-09.json').write_text(json.dumps(out,ensure_ascii=False,indent=2)+'\n')
print(json.dumps(dict(atoms=len(rows),pages=21,wholeDocumentCoveragePercent=None)))
