"""Bathing traceability: factual concepts and relations, never source prose/assets."""
import json,hashlib
from pathlib import Path
R=Path(__file__).resolve().parents[1];rt=json.loads((R/'src/data/kaigo/atomic-supplements.json').read_text());points={p['id']:p['explanationVi'] for u in rt['units'] for p in u['points']};days={i:d['day'] for d in rt['days'] for i in d['unitIds']};rows=[]
def atoms(page,kind,key,n,concepts,qualification=None):
 pid=f'kaigo-atomic-{key}-{n}';assert pid in points
 for c in concepts.split(';'):
  rows.append(dict(id=f'bathing-atom-{len(rows)+1:03}',printedPage=page,pdfPage=page+2,kind=kind,conceptVi=c,runtimePointId=pid,runtimeDay=days['kaigo-atomic-'+key],appEquivalentVi=points[pid],visualPageChecked=True,qualificationVi=qualification,mappingStatus='qualified-independent-equivalent' if qualification else 'independent-concept-equivalent',humanReviewed=False))
atoms(186,'meaning','bath-environment',1,'Loại chất bẩn;Giữ sạch;Dễ chịu;Hài lòng;Thư giãn;Nhịp sinh hoạt')
atoms(186,'effects','bath-environment',5,'Mạch giãn;Tuần hoàn thay đổi;Chuyển hóa;Cảm giác đau khớp;Cảm giác đau cơ;Vận động khớp;Chức năng tiêu hóa;Cảm giác muốn ăn','Lợi ích có điều kiện; không hứa điều trị đau hoặc cải thiện dạ dày/chuyển hóa cho mọi người.')
atoms(186,'effects','bath-environment',1,'Làm sạch da;Phòng nhiễm có giới hạn;Giảm căng thẳng;Sảng khoái','Vệ sinh không bảo đảm không nhiễm, không thay phòng ngừa chuẩn.')
atoms(187,'skin-functions','skin-structure',3,'Hàng rào;Bảo vệ phần bên trong;Chất có hại;Nhận kích thích;Bã nhờn bảo vệ bề mặt')
atoms(187,'temperature','skin-structure',2,'Giữ nhiệt;Mồ hôi;Điều hòa nhiệt','Không coi mọi độ ẩm là dưỡng ẩm có lợi.')
atoms(187,'gland-types','skin-structure',2,'Ngoại tiết;Phân bố rộng;Đầu tiết;Nách;Mùi có vi sinh','Không gán mùi chỉ cho một tên tuyến hoặc xem đầu tiết luôn có mùi tự thân.')
atoms(187,'diagram-labels','skin-structure',1,'Biểu bì;Lớp bì;Mô mỡ;Chân tóc;Tuyến bã;Tuyến mồ hôi ngoại tiết;Tuyến đầu tiết')
atoms(187,'diagram-relations','skin-structure',5,'Ngoài và dưới bề mặt;Mỡ ở sâu;Tuyến và nang tóc;Cuộn tuyến;Đường dẫn;Chất tiết ra ngoài')
atoms(188,'causes','skin-structure',6,'Mồ hôi trên da;Bã nhờn trên da;Chất bẩn;Ẩm kéo dài')
atoms(188,'folds','skin-structure',4,'Da áp nhau;Nếp gấp;Giữ ẩm;Quan sát')
atoms(188,'highlighted-body-regions','bath-sequence',1,'Cổ;Nách trái;Nách phải;Bẹn và vùng sinh dục;Bàn chân trái;Bàn chân phải','Các vùng tô trong hình là ví dụ, không danh sách đóng hoặc mọi người đều giống nhau.')
atoms(189,'care-principles','bath-environment',6,'Xấu hổ;Giữ riêng tư;Hỏi sức khỏe;Quan sát da;Bất thường;Báo chuyên môn')
atoms(189,'environment','bath-environment',2,'Chênh nhiệt phòng;Phòng thay đồ;Phòng tắm;Gánh tuần hoàn;Nước quá nóng;Tải lên cơ thể','Heat shock không đồng nghĩa mọi trường hợp đều là sốc do nắng nóng.')
atoms(189,'environment-labels','bath-environment',3,'Dụng cụ hỗ trợ;Kiểm trước dùng;Sàn trượt;Nguy cơ ngã;Bậc giữa phòng;Lối tiếp cận')
atoms(190,'before-bath','bath-environment',6,'Kiểm sức khỏe;Giải thích mục đích;Giải thích phạm vi;Đồng ý')
atoms(190,'preparation','bath-environment',7,'Quần áo thay;Sở thích người dùng;Khăn sẵn;Đi vệ sinh trước;Nhu cầu trong khi tắm;Không ép bài tiết;Chỗ ngồi vững')
atoms(190,'environment','bath-environment',2,'Nhiệt độ phòng trước tắm')
atoms(190,'food-water-callout','bath-environment',4,'Đói;Sát bữa;Nước trước tắm;Theo kế hoạch cá nhân','Không lập giờ bắt buộc hoặc tự đổi hạn chế dịch; lý giải tiêu hóa trong nguồn không là chỉ định phổ quát.')
atoms(190,'undressing','clothing-seated',2,'Cởi khỏe trước;Mặc yếu trước','Chỉ dùng phương án đã đánh giá, không tự thử chuyển người.')
atoms(190,'chair-example','bath-environment',7,'Cởi trong tư thế ngồi;An toàn và khả năng')
atoms(191,'walking','bath-sequence',2,'Đi cùng;Ngăn ngã;Che vùng riêng tư;Khăn che vùng sinh dục')
atoms(191,'side-selection','bath-sequence',7,'Nhân viên phía yếu;Bắt đầu nước phía khỏe;Hai quyết định khác nhau','Theo kiểu hỗ trợ/thiết bị và huấn luyện, không mọi cách chuyển đều cùng phía.')
atoms(191,'water-check','bath-sequence',2,'Nhân viên thử nhiệt;Người dùng cảm nhận;Kiểm lại','Tay nhân viên một mình không bảo đảm nhiệt an toàn.')
atoms(191,'showering','bath-sequence',3,'Phần xa trước;Tới thân;Khỏe trước trong mẫu;Xà phòng tạo bọt;Không chà mạnh;Kiểm vùng dễ bẩn','Trình tự ví dụ cần điều chỉnh theo dung nạp và thiết bị.')
atoms(191,'entering-bath','bath-sequence',4,'Bên khỏe vào trước trong mẫu;Tư thế và trợ giúp','Không hình hướng dẫn thao tác phổ quát.')
atoms(192,'in-bath','bath-sequence',4,'Tư thế vững;Bên yếu;Lực nổi;Hỗ trợ bên yếu;Theo dõi biểu hiện;Sức khỏe')
atoms(192,'exit-and-rinse','bath-sequence',5,'Không đứng đột ngột;Hạ huyết áp tư thế;Choáng;Hỗ trợ ra bồn;Xả sạch')
atoms(193,'shampoo-preparation','bath-sequence',8,'Làm ướt tóc;Dầu gội;Tạo/phân bố bọt;Làm sạch;Xả phần dư')
atoms(193,'shampoo-care','bath-sequence',6,'Đầu ngón tay mềm;Không cào móng;Tổn thương da đầu')
atoms(193,'after-bath','bath-sequence',5,'Khăn khô;Giữ ấm;Thấm nhẹ;Không chà xát;Nếp da;Mặc đồ')
atoms(193,'moisturizing','bath-sequence',9,'Khô da;Sản phẩm giữ ẩm;Theo kế hoạch;Khác nước đọng')
atoms(193,'dryer-callout','bath-sequence',6,'Sấy tóc;Luồng khí;Nhiệt;Tay nhân viên kiểm;Tránh bỏng;Nghỉ;Nước sau tắm','Tay không đủ chứng minh an toàn; khoảng cách/sản phẩm và nước uống theo kế hoạch.')
atoms(194,'hand-foot-examples','partial-perineal-wash',6,'Phạm vi tay;Phạm vi chân;Chậu tay;Đồ chứa chân;Tầm với;Tư thế ngồi;Tại giường;Phần tự làm')
atoms(194,'partial-wash','partial-perineal-wash',1,'Nước phù hợp;Rửa;Xả cuối;Thấm khô;Móng mềm;Dễ cắt trong ví dụ','Móng mềm không cho phép tự cắt móng có nguy cơ.')
atoms(195,'meaning','partial-perineal-wash',2,'Bài tiết;Mồ hôi;Vùng dễ bẩn;Mùi;Nguy cơ nhiễm;Đồng ý;Riêng tư;Da nhạy nhiệt')
atoms(195,'care','partial-perineal-wash',5,'Găng dùng một lần;Thấm khô nhẹ;Quan sát da;Đỏ;Báo y tế;Vệ sinh tay','Găng không thay vệ sinh tay hoặc đổi dụng cụ đúng ranh giới công việc.')
atoms(195,'female-arrows-and-prose','partial-perineal-wash',3,'Vùng niệu đạo trước;Vùng hậu môn sau;Hướng sạch tới bẩn;Không đưa bẩn trở lại;Không cùng mặt khăn')
atoms(195,'male-example-and-arrows','partial-perineal-wash',4,'Da quanh bìu;Phía dưới bìu;Vùng được che;Hỗ trợ nhẹ;Không kéo mô','Câu Việt về phía sau tinh hoàn chưa diễn đạt rõ thao tác. Giữ mục tiêu làm sạch vùng da; không suy thành phép kéo tinh hoàn hoặc thao tác xâm lấn. Cần thẩm định chuyên môn trước hướng dẫn thực hành.')
atoms(196,'bed-wash-definition','bed-wash-figures',5,'Chưa tắm bồn được;Chưa tắm vòi sen được;Lau tại giường;Toàn thân;Một phần;Phạm vi đồng ý;Khăn;Chất làm sạch;Quần áo thay')
atoms(196,'effects','bath-environment',5,'Sạch da;Tác động tuần hoàn;Cảm giác cơ','Không coi lau thay điều trị hoặc mọi lực xoa đều có lợi.')
atoms(196,'example-order','bed-wash-figures',1,'Mặt;Tay;Ngực;Bụng;Lưng;Chân;Sinh dục riêng;Sạch tới bẩn','Trình tự ví dụ; không bắt buộc sao chép khi kế hoạch cần điều chỉnh.')
atoms(196,'water-preparation','bed-wash-figures',7,'Nước chuẩn bị;Nguội nhanh;Dự trữ nước nóng;Nhiệt khăn;Nhiệt tiếp xúc','Nước chuẩn bị nóng hơn không có nghĩa nước nóng trực tiếp lên da.')
atoms(196,'face-figure','bed-wash-figures',2,'Quanh mắt;Sau tai;Cổ;Lực nhẹ')
atoms(196,'face-arrow-groups','bed-wash-figures',6,'Vùng mắt riêng;Tai riêng;Cổ riêng','Mũi tên chỉ phạm vi/hướng minh họa, không lực hay chỉ định phổ quát.')
atoms(197,'privacy-callout','bed-wash-figures',1,'Che phần chưa lau;Giữ ấm;Tránh lộ da')
atoms(197,'chest-abdomen-and-back-arrows','bed-wash-figures',6,'Nét ngang vai;Tròn ngực;Tròn bụng;Tròn mông;Nét dài lưng;Nét dọc cạnh thân;Hướng theo vùng','Đọc ý nghĩa các nhóm hướng; không suy lực/số lượt hoặc quyền thực hiện từ mũi tên.')
atoms(197,'limb-callout','bed-wash-figures',3,'Từng vùng quanh khớp;Lực phù hợp;Không lực cố định','Nguồn ghi một mức áp lực, nhưng tình trạng da/đau cần đánh giá cá nhân.')
atoms(197,'soap-and-dry','bed-wash-figures',4,'Loại xà phòng dư;Ngứa nếu còn dư;Khăn ướt;Khăn khô;Khô ngay;Ẩm và mất nhiệt')
out=dict(version=1,date='2026-10-10',sourceSha256='997bf386ba8344e19c644c3cbd6ae2d40760bfb32ed882db999ad8e17068aa54',sourceBytesHashRecomputed=True,runtimeSha256=hashlib.sha256((R/'src/data/kaigo/atomic-supplements.json').read_bytes()).hexdigest(),scopePrintedPages=list(range(186,198)),visualPagesChecked=list(range(186,198)),visualInspectionMethod='text layer and four three-page contact sheets; source diagrams viewed',atoms=rows,openVisualItems=[],openClinicalInterpretations=[dict(printedPage=195,issueVi='Chữ Việt về thao tác nam chưa rõ; app giữ mục tiêu vệ sinh nhẹ và giới hạn, chưa xác nhận thao tác thực hành.')],fullScopeAtomInventoryCertified=False,allSourceKnowledgeFullyCovered=False,wholeDocumentCoveragePercent=None,humanReviewed=False,domainReviewed=False,nativeDeviceTested=False,releaseReady=False,primaryChecks=['https://www.caa.go.jp/policies/policy/consumer_safety/caution/caution_055/index.html','https://www.bdct.nhs.uk/skin-damage-from-moisture/','https://www.nhs.uk/social-care-and-support/practical-tips-if-you-care-for-someone/how-to-help-someone-you-care-for-keep-clean/','https://www.aad.org/public/everyday-care/skin-care-secrets/routine/whole-body-deodorant'])
(R/'docs/ssw-workspace/kaigo/reviews/bathing-source-atoms-2026-10-10.json').write_text(json.dumps(out,ensure_ascii=False,indent=2)+'\n');print(json.dumps(dict(atoms=len(rows),pages=12)))
