"""Independent concept inventory of aging/disability/dementia; not a source transcript."""
import json,hashlib
from pathlib import Path
R=Path(__file__).resolve().parents[1]
rt=json.loads((R/'src/data/kaigo/atomic-supplements.json').read_text())
points={p['id']:p['explanationVi'] for u in rt['units'] for p in u['points']}
days={i:d['day'] for d in rt['days'] for i in d['unitIds']}
rows=[]
def atoms(page,kind,key,n,concepts,qualification=None):
 pid=f'kaigo-atomic-{key}-{n}';assert pid in points
 for concept in concepts.split(';'):
  rows.append(dict(id=f'aging-atom-{len(rows)+1:03}',printedPage=page,pdfPage=page+2,kind=kind,conceptVi=concept.strip(),runtimePointId=pid,runtimeDay=days['kaigo-atomic-'+key],appEquivalentVi=points[pid],visualPageChecked=True,qualificationVi=qualification,humanReviewed=False))
atoms(68,'prose-and-stage-label','aging',6,'Lão hóa mọi người;Khác biệt cá nhân;Lối sống liên quan;Trẻ nhỏ;Tuổi học đường;Trưởng thành;Trung niên;Tuổi cao','Giai đoạn không quyết định khả năng cá nhân.')
atoms(69,'prose','aging',7,'Thời đại sống;Môi trường sống;Lịch sử riêng;Khó làm việc từng quen;Buồn;Sốt ruột;Bất lực;Mất bạn đời;Mất bạn bè;Thay đổi vai trò;Nguy cơ tâm trạng trầm','Không mặc định trầm cảm ở mọi người cao tuổi.')
atoms(70,'figure-label-and-relation','aging',2,'Khó nghe âm cao;Thị lực giảm;Trường nhìn thay đổi')
atoms(70,'figure-label-and-relation','aging',3,'Giảm sức cơ;Nguy cơ ngã;Khả năng nhai;Khả năng nuốt;Cảm nhận vị')
atoms(70,'figure-label-and-relation','aging',9,'Hô hấp;Bảo vệ miễn dịch;Chức năng thận;Đi tiểu nhiều lần;Thành mạch;Huyết áp;Ruột vận động;Táo bón','Xu hướng không loại trừ bệnh mới cần đánh giá.')
atoms(70,'prose','aging',5,'Nhiều bệnh đồng thời;Mạn tính;Biểu hiện không điển hình')
atoms(70,'prose','aging',10,'Biến chứng;Tương tác điều trị')
atoms(70,'list-and-cross-reference','aging',8,'Mất nước;Sốt;Táo bón;Phù;Mất ngủ;Suy giảm do ít hoạt động;Tổn thương do tì đè')
atoms(71,'prose','dehydration',1,'Thiếu nước so nhu cầu;Ít uống;Tiêu chảy;Nôn;Sốt;Mồ hôi')
atoms(71,'prose','dehydration',2,'Khô da;Khô miệng;Khô môi;Tiểu ít;Mạch nhanh;Huyết áp thấp','Mạch và áp lực cần số đo thật.')
atoms(71,'prose','dehydration',5,'Nhiệt tăng có thể đi cùng;Nặng nguy hiểm tính mạng;Cần hỗ trợ y tế')
atoms(71,'balance-figure','dehydration',3,'Nước từ thức ăn;Nước từ đồ uống;Ra qua nước tiểu;Ra qua mồ hôi;Cân bằng vào ra;Ít cảm giác khát')
atoms(71,'care-callout','dehydration',6,'Nhiệt độ môi trường;Trước tắm;Sau tắm;Trước vận động;Sau vận động;Cơ hội uống','Theo kế hoạch khi hạn dịch hoặc khó nuốt.')
atoms(72,'prose','fever-constipation',1,'Vùng dưới đồi điều hòa;So với nhiệt thường ngày;Nhiễm trùng;Viêm;Đo và xét hoàn cảnh')
atoms(72,'prose','dehydration',5,'Mất nước liên quan tăng nhiệt')
atoms(72,'prose-and-care','fever-constipation',2,'Mệt;Ăn ít;Mặt đỏ;Không cần đủ mọi biểu hiện;Nước theo kế hoạch')
atoms(72,'prose','fever-constipation',3,'Khó đại tiện;Ít đại tiện;Phân cứng;Cảm giác chưa hết;Nhu động;Sức cơ;Nhịn nhu cầu')
atoms(72,'numeric-reference','fever-constipation',4,'Tham khảo vận chuyển24–72giờ;Không là ngưỡng chẩn đoán','Không áp một mốc cho mọi người.')
atoms(72,'prose','fever-constipation',5,'Ăn kém;Đau bụng;Buồn nôn;Báo bất thường')
atoms(72,'care-callout','fever-constipation',7,'Chất xơ;Hoạt động theo khả năng;Nước theo kế hoạch;Thời điểm sau bữa ăn')
atoms(72,'figure-action','fever-constipation',6,'Hình xoa vùng bụng;Quan hệ với đại tràng','Không là hướng dẫn tự xoa hay chỉ định cho mọi người; chiều thao tác cụ thể chưa được tái tạo.')
atoms(73,'prose','edema-itch',1,'Dịch ở mô;Sức cơ giảm;Ngồi lâu;Tim;Thận;Dinh dưỡng;Tăng cân')
atoms(73,'care-and-figure','edema-itch',2,'Vị trí;Mức phù;Vận động;Nâng chân','Theo đánh giá và kế hoạch.')
atoms(73,'prose','edema-itch',5,'Bên liệt dễ phù;So hai bên;Theo dõi cân nặng','Không gán mọi sưng một bên cho liệt.')
atoms(73,'prose','edema-itch',3,'Da khô;Nhiệt độ;Độ ẩm;Chất liệu áo;Đỏ;Phát ban')
atoms(73,'care-callout','edema-itch',4,'Giữ ẩm;Nguyên nhân có thể lây;Báo thay đổi')
atoms(74,'prose','insomnia',1,'Khó vào giấc;Thức giữa đêm;Ngủ không hồi phục;Ảnh hưởng ban ngày')
atoms(74,'prose-and-care','insomnia',2,'Mệt;Bực;Uể oải;Nhịp hoạt động;Ánh sáng;Tiếng ồn;Đau;Bài tiết')
atoms(74,'care','insomnia',3,'Môi trường ngủ;Ngủ trưa;Đánh giá khó ngủ ảnh hưởng cuộc sống','Không cấm ngủ trưa mọi người.')
atoms(74,'prose-and-care','pressure-organs',5,'Huyết áp cao kéo dài;Tim;Thận;Mạch;Lối sống;Đau đầu có thể;Hồi hộp có thể;Muối;Vận động;Thuốc','Không có triệu chứng vẫn cần đánh giá; không tự dừng thuốc.')
atoms(74,'prose','pressure-organs',3,'Xơ vữa;Nguy cơ tim')
atoms(74,'prose','pressure-organs',2,'Nguy cơ mạch não')
atoms(75,'prose-and-figure','heart-diseases',1,'Tắc mạch não;Vỡ mạch não;Vùng tổn thương;Di chứng')
atoms(75,'prose','heart-diseases',6,'Đau đầu;Chóng mặt;Buồn nôn;Nôn;Ý thức;Hô hấp;Cảm giác;Gọi hỗ trợ khi cấp;Ăn và vận động sau đánh giá','Triệu chứng không riêng một bệnh.')
atoms(76,'prose','heart-diseases',2,'Thiếu máu cơ tim;Hẹp mạch vành;Đau thắt ngực;Tắc mạch;Nhồi máu')
atoms(76,'definition','heart-diseases',5,'Hoại tử;Tế bào chết;Tổn thương mô','Không phân biệt chắc nhồi máu chỉ qua mức đau.')
atoms(76,'prose','heart-diseases',3,'Sức bơm giảm;Khó thở;Hồi hộp;Mệt;Phù;Tăng cân;Tiểu ít')
atoms(76,'care','heart-diseases',4,'Nước theo điều trị;Muối theo điều trị;Không tự điều chỉnh')
atoms(76,'figure-posture','heart-diseases',7,'Ngồi nghiêng về trước;Mục đích giảm khó chịu hô hấp','Không ép tư thế cho mọi người; khó thở cần báo.')
atoms(77,'prose','pneumonia',1,'Viêm phổi;Triệu chứng có thể không điển hình')
atoms(77,'prose','pneumonia',5,'Vi khuẩn;Virus;Nước bọt mang vi khuẩn;Chất từ miệng vào đường thở;Viêm phổi do hít sặc')
atoms(77,'distinction','pneumonia',2,'Hít sặc khác khó nuốt')
atoms(77,'care','pneumonia',3,'Vệ sinh miệng;Tư thế phù hợp;Giảm nguy cơ')
atoms(77,'care','pneumonia',4,'Không nằm ngay sau ăn;Dừng ăn khi bất thường;Hỗ trợ y tế','Theo khả năng và kế hoạch.')
atoms(78,'prose','diabetes-types',1,'Type1;Tế bào beta;Insulin thiếu do tổn thương miễn dịch','Không giới hạn type1 vào trẻ em.')
atoms(78,'prose','diabetes-types',2,'Type2;Đề kháng insulin;Tiết insulin không đủ','Không quy chỉ cho tuổi hoặc lỗi lối sống.')
atoms(78,'prose','diabetes-types',3,'Đường máu cao;Khát;Khô miệng;Tiểu nhiều;Sụt cân;Mệt;Kế hoạch cá nhân')
atoms(78,'prose','diabetes-complications',1,'Võng mạc;Thận;Thần kinh')
atoms(78,'prose','diabetes-complications',2,'Vết thương lâu lành;Đau có thể ít;Quan sát da')
atoms(78,'care','diabetes-complications',3,'Ăn;Vận động;Thuốc;Niềm vui bữa ăn','Không tự áp hạn calo cho mọi người.')
atoms(79,'prose','skeleton-labels',5,'Xương dễ gãy;Ít vận động kéo dài;Dinh dưỡng;Hormone;Nguy cơ sau mãn kinh','Nam giới cũng có thể mắc.')
atoms(79,'prose-and-care','skeleton-labels',6,'Lưng cong;Chiều cao giảm;Đau lưng;Canxi;Hoạt động;Ánh sáng phù hợp;Phòng ngã','Dữ kiện không tự đủ để chẩn đoán.')
atoms(79,'figure-label','skeleton-labels',3,'Xương cánh tay;Xương quay;Cột sống;Cổ xương đùi')
atoms(80,'prose','icf',1,'Tên ICF;Chức năng;Khuyết tật;Sức khỏe;Tình trạng sức khỏe')
atoms(80,'figure-label','icf',2,'Chức năng cơ thể;Cấu trúc cơ thể;Hoạt động;ADL;IADL;Tham gia;Làm việc;Cộng đồng')
atoms(80,'figure-label','icf',3,'Yếu tố môi trường;Nhà;Người hỗ trợ;Cộng đồng;Dịch vụ;Thái độ;Yếu tố cá nhân;Tuổi;Trải nghiệm;Tính cách;Giá trị')
atoms(80,'figure-label','icf',6,'Giới tính;Không gán sở thích theo giới hoặc tuổi')
atoms(80,'figure-arrow','icf',4,'Tương tác hai chiều;Sức khỏe và hoạt động;Cơ thể và tham gia;Môi trường và thực hiện việc','Không dùng mũi tên như nhân quả tuyến tính.')
atoms(80,'figure-meaning','icf',5,'Lối tiếp cận dốc;Phương tiện hỗ trợ;Tiếp cận giao thông;Rào cản môi trường')
atoms(81,'prose','icf',5,'Khả năng hiện có;Mục tiêu riêng;Hỗ trợ tham gia')
atoms(81,'prose','motor-disability',1,'Tay chân;Thân mình;Bệnh;Tai nạn;Não;Tủy sống;Biến dạng xương khớp;Co rút')
atoms(81,'prose','motor-disability',2,'Mức độ khác nhau;Vùng khác nhau;Có thể kèm khó nhận thức','Khó vận động không tự có nghĩa giảm hiểu.')
atoms(81,'prose','motor-disability',3,'Gậy;Xe lăn;Bộ phận giả;Lựa chọn phù hợp')
atoms(82,'prose','visual-patterns',4,'Thị lực;Trường nhìn;Có từ sớm;Bệnh;Tai nạn;Tuổi;Mất nhìn;Chỉ còn nhận sáng;Trường thu hẹp')
atoms(82,'figure-pattern','visual-patterns',1,'Khuyết vùng trung tâm')
atoms(82,'figure-pattern','visual-patterns',2,'Trường nhìn hẹp')
atoms(82,'figure-pattern','visual-patterns',3,'Bỏ quên nửa không gian','Khác khiếm khuyết trường thị giác; không suy chỉ phóng chữ là đủ.')
atoms(83,'prose','hearing-disability',1,'Đường tiếp nhận âm;Đường truyền;Xử lý;Vị trí ảnh hưởng;Mức độ;Thời điểm xuất hiện')
atoms(83,'care','hearing-disability',2,'Máy trợ thính;Kiểm môi trường;Xác nhận hiểu','Không bảo đảm nghe rõ mọi âm.')
atoms(83,'care-and-cross-reference','hearing-disability',3,'Viết;Ký hiệu;Khẩu hình;Lựa chọn phương thức','Không mặc định mọi người biết ký hiệu hoặc đọc khẩu hình.')
atoms(84,'prose','aphasia',1,'Ngôn ngữ đã phát triển;Tổn thương não;Hiểu lời;Nói;Đọc;Viết')
atoms(84,'figure-meaning','aphasia',2,'Muốn nói nhưng khó đáp;Không suy không hiểu;Không chỉ là cơ phát âm')
atoms(84,'care','aphasia',3,'Hình;Cử chỉ;Bảng chọn;Viết;Thiết bị;Khả năng còn lại','Viết có thể cũng khó.')
atoms(84,'care','aphasia',4,'Chờ trả lời;Hỏi từng ý;Xác nhận;Giữ sự tham gia')
atoms(85,'prose-and-figure','internal-disability',1,'Chức năng tim;Máy tạo nhịp;Tránh va vùng cấy','Chỉ cho một số rối loạn nhịp.')
atoms(85,'prose','internal-disability',2,'Thận;Chất thải;Dịch dư;Đường vào mạch;Không tải tay tùy tiện')
atoms(85,'figure-arrow','internal-disability',5,'Máu ra;Bộ lọc;Loại chất thải;Loại nước dư;Máu về;Tắm;Muối;Nước','Tắm và dịch theo kế hoạch, không áp cấm chung theo hình.')
atoms(86,'figure-label','internal-disability',6,'Bình oxy mang theo;Máy tạo oxy cá nhân;Không là máy thông khí','Không tự chỉnh lưu lượng.')
atoms(86,'care','internal-disability',3,'Nguy cơ cháy;Nguồn dự phòng;Phòng nhiễm trùng')
atoms(86,'figure-and-care','internal-disability',7,'Lỗ mở phân;Lỗ mở nước tiểu;Vị trí thành bụng thay đổi;Túi thu;Đỏ;Loét;Rò','Không phải mọi khó bài tiết cần lỗ mở; thao tác cần huấn luyện.')
atoms(87,'prose','mental-health',4,'Khả năng thích nghi;Tôn trọng tuổi trưởng thành;Phán đoán có thể khó;Kiểm soát có thể khó','Không mặc định nguy hiểm hay luôn thiếu năng lực.')
atoms(87,'prose','mental-health',5,'Tâm thần phân liệt;Rối loạn khí sắc')
atoms(87,'prose','mental-health',1,'Phát triển trí tuệ;Khả năng thích nghi;Khác bệnh tâm thần','Tôn trọng tuổi trưởng thành; không trẻ hóa người dùng.')
atoms(87,'prose','mental-health',2,'Trầm cảm;Hưng cảm;Thay đổi tâm trạng','Không chẩn đoán qua một biểu hiện.')
atoms(87,'prose','mental-health',3,'Ảo giác;Hoang tưởng;Lắng nghe cảm xúc','Không xác nhận niềm tin chưa có căn cứ là sự thật.')
atoms(88,'definition','brain-lobes',6,'Suy giảm nhận thức;Ảnh hưởng sinh hoạt;Ảnh hưởng tham gia xã hội;Nhiều nguyên nhân')
atoms(88,'figure-label-and-function','brain-lobes',1,'Thùy trán;Vận động;Điều hành;Thùy đỉnh;Cảm giác;Không gian')
atoms(88,'figure-label-and-function','brain-lobes',2,'Thùy thái dương;Âm thanh;Ngôn ngữ;Trí nhớ;Thùy chẩm;Thị giác')
atoms(88,'figure-callout','brain-lobes',4,'Hành vi;Cảm xúc;Động lực;Ý định;Mùi;Vị','Khứu/vị xử lý bằng mạng nhiều vùng, không chỉ vị trí nhãn giản lược.')
atoms(89,'figure-function','brain-lobes',5,'Ghi nhớ;Ngôn ngữ;Hành động;Nhận biết;Lập kế hoạch theo thứ tự')
atoms(90,'comparison-table','forgetting',1,'Chi tiết so sự việc;Tiến triển;Nhận biết khó khăn;Ảnh hưởng sinh hoạt')
atoms(90,'comparison-qualification','forgetting',2,'Không là quy tắc tuyệt đối;Có thể có nhận biết;Tiến triển theo nguyên nhân')
atoms(90,'care','forgetting',4,'Cách sống quen;Khả năng còn lại;Động lực;Làm cùng;Nhịp ngày')
atoms(91,'care-and-room-figure','forgetting',4,'Môi trường quen;Không đổi phòng chỉ tiện nhân viên')
atoms(91,'care','forgetting',5,'Lắng nghe;Trấn an;Lời ngắn;Thời gian;Không tranh cãi;Thấu cảm','Không xác nhận điều chưa có căn cứ là thật.')
atoms(92,'table','dementia-types',6,'Mạch não và liệt một bên;Mạch não và mất ngôn ngữ;Khả năng không đồng đều;Thay đổi bệnh lý Alzheimer;Thoái hóa trán và thái dương')
atoms(92,'table','dementia-types',1,'Alzheimer;Nhớ mới;Tiến triển dần;Mạch máu;Tổn thương mạch;Theo đợt;Biểu hiện khu trú')
atoms(92,'table','dementia-types',2,'Lewy;Ảo giác thị giác;Dao động;Parkinson;Hành vi REM')
atoms(92,'qualified-mechanism','dementia-types',4,'Protein alpha-synuclein;Thể Lewy','Không giảng cơ chế chỉ là teo vùng chẩm.')
atoms(92,'table','dementia-types',3,'Trán–thái dương;Hành vi;Ngôn ngữ;Lặp hành động')
atoms(92,'qualified-table','dementia-types',5,'Khác biệt biểu hiện;Khác biệt điều trị;Không định kiến vui hoặc hung hăng','Thuốc không bảo đảm làm chậm mọi dạng bệnh.')
atoms(93,'figure-label','dementia-symptoms',1,'Trí nhớ;Định hướng;Trình tự;Hiểu và phán đoán')
atoms(93,'figure-label','dementia-symptoms',2,'BPSD;Lo âu;Ảo giác;Hoang tưởng;Kích động;Đi lại nhiều')
atoms(93,'figure-arrow','dementia-symptoms',5,'Bệnh;Nhận thức;Sức khỏe cơ thể;Môi trường;Quan hệ;Tương tác nhiều yếu tố','Không quy mọi biểu hiện cho môi trường hoặc tính cách; không xếp BPSD là ít quan trọng.')
atoms(94,'prose-and-example-meaning','dementia-symptoms',6,'Giờ;Nơi;Người;Chuỗi thao tác;Quyết định tiền bạc','Không tái tạo ca bếp/tiền trong tài liệu.')
atoms(94,'prose','dementia-symptoms',3,'Sợ;Đau;Nhu cầu bài tiết;Đi lại có mục đích')
atoms(94,'care','dementia-symptoms',4,'Hỏi nhu cầu;Quan sát thay đổi;Phối hợp;Không tự dùng thuốc hoặc kiềm chế')
atoms(95,'prose','dementia-symptoms',2,'Lo âu;Nhận thức gây bối rối')
atoms(95,'prose-and-figure-meaning','mental-health',3,'Tri giác khi không có kích thích;Niềm tin sai chắc;Phân biệt ảo giác và hoang tưởng','Không tái tạo cảnh vật hoặc vụ mất đồ của tài liệu.')
review=R/'docs/ssw-workspace/kaigo/reviews'
out=dict(version=1,sourceSha256='997bf386ba8344e19c644c3cbd6ae2d40760bfb32ed882db999ad8e17068aa54',runtimeSha256=hashlib.sha256((R/'src/data/kaigo/atomic-supplements.json').read_bytes()).hexdigest(),scopePrintedPages=list(range(68,96)),visualPagesChecked=list(range(68,96)),atoms=rows,openVisualItems=[dict(printedPage=72,itemVi='Chiều thao tác xoa bụng trong hình chưa tái tạo thành hướng dẫn; chỉ liên kết mục đích với giới hạn chuyên môn.')],fullScopeAtomInventoryCertified=False,allSourceKnowledgeFullyCovered=False,wholeDocumentCoveragePercent=None,humanReviewed=False,domainReviewed=False,releaseReady=False,primaryChecks=['https://www.who.int/Standards/Classifications/International-Classification-of-Functioning-Disability-and-Health','https://www.nidcd.nih.gov/health/aphasia','https://www.niddk.nih.gov/health-information/kidney-disease/kidney-failure/hemodialysis','https://www.nia.nih.gov/health/lewy-body-dementia/lewy-body-dementia-causes-symptoms-and-diagnosis'])
(review/'aging-source-atoms-2026-10-09.json').write_text(json.dumps(out,ensure_ascii=False,indent=2)+'\n')
print(json.dumps(dict(atoms=len(rows),pages=28,openVisualItems=len(out['openVisualItems']),wholeDocumentCoveragePercent=None)))
