"""Manual meaning inventory of body chapter; source expression is not reproduced."""
import json,hashlib
from pathlib import Path
R=Path(__file__).resolve().parents[1]
rt=json.loads((R/'src/data/kaigo/atomic-supplements.json').read_text())
points={p['id']:p['explanationVi'] for u in rt['units'] for p in u['points']}
days={i:d['day'] for d in rt['days'] for i in d['unitIds']}
rows=[]
def atoms(page,kind,key,n,concepts,qualification=None):
    pid=f'kaigo-atomic-{key}-{n}';assert pid in points
    for concept in concepts.split(';'):
        rows.append(dict(id=f'body-atom-{len(rows)+1:03}',printedPage=page,pdfPage=page+2,kind=kind,conceptVi=concept.strip(),runtimePointId=pid,runtimeDay=days['kaigo-atomic-'+key],appEquivalentVi=points[pid],visualPageChecked=True,qualificationVi=qualification,humanReviewed=False))
atoms(42,'prose','stress',1,'Cảm xúc riêng;Suy nghĩ riêng;Cách thể hiện riêng;Biểu hiện và thái độ gợi thông tin;Người chăm sóc tìm hiểu cảm xúc','Biểu hiện không đủ để suy chắc cảm xúc.')
atoms(42,'prose','stress',6,'Trải nghiệm và lối sống liên quan tính cách;Giáo dục liên quan tính cách;Thay đổi theo tuổi có khác biệt cá nhân')
atoms(42,'figure-caption','stress',7,'Vui;Giận;Buồn;Thích thú')
atoms(43,'prose-and-figure-meaning','stress',2,'Mong muốn chủ động;Hỗ trợ động lực;Hình lựa chọn hoạt động của người dùng')
atoms(43,'prose','stress',7,'Căng thẳng ở tinh thần;Căng thẳng ở cơ thể;Phấn khích là một tác động')
atoms(43,'prose-and-figure','stress',3,'Tiếng ồn;Nhiệt độ;Tác động môi trường')
atoms(43,'prose','stress',4,'Mệt;Thiếu ngủ;Đói;Tác động cơ thể')
atoms(43,'prose-and-figure','stress',5,'Lo âu;Sợ;Quan hệ;Tác động tâm lý xã hội')
atoms(44,'figure-arrow','memory',1,'Tiếp nhận thông tin mới;Duy trì thông tin;Gọi lại;Trình tự tiếp nhận rồi giữ rồi gọi lại')
atoms(44,'table','memory',2,'Ngắn hạn;Dài hạn;Khác biệt thời gian duy trì')
atoms(44,'table','memory',3,'Sự kiện và trải nghiệm;Ngữ nghĩa và hiểu biết')
atoms(44,'table','memory',4,'Gợi mồi không cần nhớ có ý thức;Kỹ năng quy trình','Gợi mồi không đồng nghĩa mọi trí nhớ vô thức.')
atoms(45,'prose','needs',4,'Khái niệm nhu cầu;Hai nhóm cơ bản;Ba nhóm xã hội')
atoms(45,'figure-label','needs',1,'Sinh lý;Ăn;Uống;Ngủ;An toàn')
atoms(45,'figure-label','needs',2,'Gắn bó;Được yêu thương hoặc tiếp xúc;Được công nhận')
atoms(45,'figure-label-and-relation','needs',3,'Tự thực hiện;Phát triển khả năng;Mô hình năm nhóm','Tháp là mô hình, không bắt mọi người đi qua các tầng theo một thứ tự cứng.')
atoms(46,'prose-and-figure','temperature',1,'Nội môi ổn định tương đối;Thích ứng môi trường;Nóng rồi mồ hôi giúp tỏa nhiệt')
atoms(46,'prose','temperature',5,'Dấu hiệu sinh tồn phản ánh trạng thái;Nhiệt độ;Hô hấp;Mạch;Huyết áp')
atoms(46,'prose','temperature',6,'Biến thiên theo ngày đêm;Thường thấp lúc ngủ đêm;Thường cao hơn ban ngày','Xu hướng không phải một giờ hay mức cố định cho mọi người.')
atoms(46,'prose','temperature',2,'Khác biệt cá nhân;Ghi điều kiện đo')
atoms(47,'figure-action-and-callout','temperature',3,'Đầu cảm biến ở nách;Cánh tay khép;Ví dụ dùng bên không liệt','Áp dụng theo kế hoạch và thiết bị; không chỉ là đặt gần nách.')
atoms(47,'figure-and-prose','temperature',4,'Đo ở trán;Đo ở tai;Thiết bị và vị trí khác nhau')
atoms(48,'prose','breathing',5,'Oxy vào;Carbon dioxide ra;Thường tự động;Điều hòa nhịp')
atoms(48,'prose-and-callout','breathing',2,'Ảnh hưởng tuổi;Ảnh hưởng hoạt động;Ảnh hưởng tâm trạng;Ảnh hưởng sức khỏe hoặc bệnh;Công thở;Âm thanh;Đờm')
atoms(48,'prose','breathing',3,'Môi tím xanh;Móng tím xanh;Dấu hiệu thiếu oxy','Khó thở có thể chưa tím; không đợi đổi màu để gọi hỗ trợ.')
atoms(49,'prose','pulse',1,'Sóng từ nhịp tim tới động mạch;Tần số;Đều hay không;Mạnh hay yếu')
atoms(49,'prose','pulse',6,'Tuổi liên quan nhịp;Trẻ nhỏ thường nhanh hơn người trưởng thành','Không dạy nhịp luôn giảm đơn điệu theo tuổi; sức khỏe và thuốc ảnh hưởng.')
atoms(49,'prose','pulse',4,'Ảnh hưởng hoạt động;Ảnh hưởng tâm trạng;Ảnh hưởng bệnh')
atoms(49,'figure-label','pulse',2,'Động mạch quay;Động mạch cánh tay;Động mạch cảnh;Vị trí vùng khuỷu')
atoms(49,'figure-label-and-callout','pulse',5,'Động mạch thái dương nông;Mặt trong cổ tay')
atoms(49,'callout','pulse',3,'Vùng bẹn;Mu chân','Nhận diện không cấp quyền thực hiện mọi kỹ thuật.')
atoms(50,'prose','pressure-context',1,'Áp lực lên thành động mạch;Tim co và tim giãn')
atoms(50,'figure-label-and-arrow','pressure-context',5,'Tâm thu;Mức tối đa;Tâm trương;Mức tối thiểu;Hai pha chu kỳ','Cao/thấp trên hình là hai mức chu kỳ, không phải tự chẩn đoán tăng/hạ huyết áp.')
atoms(50,'prose','pressure-context',6,'Biến đổi trong ngày;Tư thế;Hoạt động;Tâm trạng')
atoms(50,'prose','pressure-context',3,'Bệnh ảnh hưởng số đo')
atoms(50,'prose','pressure-organs',1,'Cao kéo dài liên quan nguy cơ não và tim')
atoms(51,'figure-caption','pressure-context',2,'Phấn khích;Thiếu ngủ;Hồi hộp')
atoms(51,'figure-caption','pressure-context',3,'Đổi nhiệt độ đột ngột;Vận động đột ngột')
atoms(51,'figure-caption','pressure-context',4,'Rặn đại tiện;Nhịn tiểu;Nhịn đại tiện')
atoms(51,'figure-label','pressure-organs',2,'Nhồi máu não;Xuất huyết não;Xuất huyết dưới nhện')
atoms(51,'figure-label','pressure-organs',3,'Đau thắt ngực;Nhồi máu cơ tim;Xơ vữa')
atoms(51,'figure-label','pressure-organs',4,'Tổn thương võng mạc liên quan tăng huyết áp')
atoms(52,'figure-label','body-regions',1,'Đầu;Cổ;Thân;Ngực;Bụng')
atoms(52,'figure-label','body-regions',2,'Chi trên;Chi dưới')
atoms(52,'figure-label','body-regions',3,'Lòng bàn tay;Lòng bàn chân')
atoms(53,'prose-and-figure-group','nerves',1,'Trung ương;Não;Tủy sống;Ngoại biên')
atoms(53,'prose','nerves',4,'Thu nhận;Phân tích;Nhận định;Điều khiển;Thông tin vào và lệnh ra')
atoms(53,'prose-and-figure-label','nerves',2,'Dây sọ;12 đôi;Dây tủy;31 đôi')
atoms(53,'prose','nerves',3,'Truyền giữa tủy và não;Truyền giữa trung ương và cơ thể')
atoms(53,'figure-region','nerves',5,'Vùng đầu;Vùng ngực;Vùng eo','Tên vùng trong hình không được dùng thay tên đoạn/dây thần kinh.')
atoms(53,'figure-label','brain-parts',1,'Đại não;Tiểu não')
atoms(53,'figure-label','brain-parts',2,'Trung não;Cầu não;Hành não')
atoms(53,'figure-label','brain-parts',3,'Gian não')
atoms(54,'figure-label-and-function','brain-parts',1,'Tiểu não và cân bằng;Tiểu não và phối hợp vận động')
atoms(54,'figure-bracket-and-function','brain-parts',2,'Ba phần thuộc thân não;Điều hòa nhịp tim;Điều hòa thở;Nuốt')
atoms(54,'figure-label-and-function','brain-parts',3,'Đồi thị;Vùng dưới đồi;Điều hòa tự chủ;Nhiệt;Nhịp ngủ')
atoms(54,'cross-reference','brain-parts',1,'Đại não nối kiến thức các vùng chức năng','Bốn thùy được học riêng ở thẻ brain-lobes của khối sa sút trí tuệ, không coi liên kết này chứng nhận toàn trang 88.')
atoms(55,'prose','autonomic-heart',1,'Điều hòa không cần ý thức;Giao cảm;Đối giao cảm')
atoms(55,'prose-and-callout','autonomic-heart',5,'Hoạt động;Lo;Giận;Căng thẳng;Nghỉ;Ngủ;Rối loạn điều hòa ảnh hưởng thể chất và tâm trạng')
atoms(55,'table','autonomic-heart',2,'Tim nhanh hơn với giao cảm;Tim chậm hơn với đối giao cảm')
atoms(55,'table','autonomic-heart',3,'Co mạch ngoại biên;Giãn mạch được mô tả phía nghỉ','Không đối xứng trực tiếp cho mọi mạch; xét điều hòa tổng thể.')
atoms(55,'table','autonomic-heart',4,'Xu hướng huyết áp tăng;Xu hướng giảm lúc nghỉ','Không suy số đo từ tên hệ; đối giao cảm không trực tiếp chi phối mọi mạch.')
atoms(55,'table','autonomic-other',1,'Đồng tử giãn;Đồng tử co')
atoms(55,'table','autonomic-other',2,'Vận động ruột giảm;Vận động ruột tăng')
atoms(55,'table','autonomic-other',3,'Phế quản giãn;Phế quản co')
atoms(55,'table','autonomic-other',4,'Mồ hôi tăng với giao cảm;Hình mô tả giảm phía nghỉ','Không dạy đối giao cảm trực tiếp tắt tuyến mồ hôi.')
atoms(56,'prose','skeleton-functions',4,'Xương lớn;Xương nhỏ;Khung xương phối hợp')
atoms(56,'prose','skeleton-functions',3,'Đường cong sinh lý chữ S')
atoms(56,'list','skeleton-functions',1,'Nâng đỡ;Tham gia vận động')
atoms(56,'list','skeleton-functions',2,'Bảo vệ;Dự trữ canxi;Tạo máu')
atoms(56,'figure-label','skeleton-labels',1,'Xương sọ;Xương ức;Xương sườn;Cột sống;Đốt ngực;Đốt thắt lưng')
atoms(56,'figure-label','skeleton-labels',2,'Xương cánh tay;Xương quay;Xương trụ;Xương đùi')
atoms(57,'prose-and-view','muscle-labels',3,'Giữ tư thế;Tạo vận động;Cơ ở nội tạng;Nhìn trước;Nhìn sau')
atoms(57,'figure-label','muscle-labels',1,'Cơ delta;Cơ ngực lớn;Cơ nhị đầu cánh tay;Cơ tam đầu cánh tay')
atoms(57,'figure-label','muscle-labels',2,'Cơ thắt lưng chậu;Cơ mông lớn;Cơ tứ đầu đùi;Cơ nhị đầu đùi')
atoms(57,'prose','senses',1,'Thị giác;Thính giác;Khứu giác;Vị giác;Xúc giác;Kích thích được truyền qua thần kinh')
atoms(57,'figure-label-and-arrow','senses',2,'Thủy tinh thể hội tụ;Võng mạc nhận ánh sáng;Thần kinh thị giác dẫn về não')
atoms(57,'figure-caption','senses',4,'Thủy tinh thể trong suốt;Dạng cong;Võng mạc là lớp mô phía sau','Mô tả hình cắt và chức năng, không sao hình hoặc coi võng mạc là màn chiếu thụ động.')
atoms(58,'figure-label-and-arrow','senses',3,'Màng nhĩ rung;Xương con khuếch đại rung;Ốc tai chuyển tín hiệu;Thần kinh thính giác truyền')
atoms(58,'figure-caption','senses',5,'Vỏ não thính giác;Phân biệt truyền rung và truyền tín hiệu')
atoms(59,'figure-label','breathing',1,'Khoang mũi;Hầu;Thanh quản;Khí quản;Phế quản;Phổi;Đường không khí tới phổi')
atoms(59,'prose','breathing',5,'Nhận oxy;Thải carbon dioxide')
atoms(60,'prose-and-callout','breathing',4,'Bụi hoặc tác nhân kích thích;Ho bảo vệ;Đờm;Ho kéo dài;Đờm đổi màu')
atoms(60,'prose','circulation',4,'Máu vận chuyển khí;Máu vận chuyển dinh dưỡng;Máu vận chuyển chất thải;Bạch huyết tham gia vận chuyển')
atoms(60,'prose','circulation',5,'Bốn buồng tim;Nhĩ nhận;Thất đẩy')
atoms(60,'prose','circulation',1,'Tim hoạt động như bơm')
atoms(60,'prose','circulation',3,'Động mạch ra;Tĩnh mạch về;Mao mạch nhỏ trao đổi')
atoms(60,'prose','circulation',8,'Máu giàu oxy ở động mạch hệ thống;Máu ít oxy ở tĩnh mạch hệ thống','Không áp phân loại oxy cho mạch phổi.')
atoms(61,'figure-label-and-arrow','circulation',6,'Thân trên;Thân dưới;Tĩnh mạch chủ trên;Tĩnh mạch chủ dưới;Tâm nhĩ phải;Tâm thất phải;Động mạch phổi;Máu về rồi tới phổi')
atoms(61,'figure-label-and-arrow','circulation',7,'Phổi;Tĩnh mạch phổi;Tâm nhĩ trái;Tâm thất trái;Động mạch chủ;Các nhánh;Máu từ phổi đi tới mô')
atoms(61,'prose-and-loop','circulation',2,'Vòng phổi;Vòng hệ thống')
atoms(61,'prose','breathing',5,'Trao đổi oxy và carbon dioxide ở phổi')
atoms(62,'prose','digestive',5,'Ống từ miệng tới hậu môn;Cơ quan tiết dịch hoặc enzyme;Tiêu hóa;Hấp thu;Thải phần còn lại')
atoms(62,'figure-caption-and-route','digestive',1,'Miệng;Thực quản vận chuyển;Dạ dày;Nhu động;Dịch tiêu hóa')
atoms(62,'figure-caption','digestive',2,'Ruột non hấp thu dinh dưỡng;Ruột non hấp thu nước;Đại tràng thu hồi nước;Hình thành phân','Đại tràng không thay ruột non hấp thu phần lớn dinh dưỡng.')
atoms(62,'figure-caption','digestive',3,'Trực tràng nhận phân;Căng thành gợi nhu cầu')
atoms(62,'figure-caption','digestive',4,'Hậu môn;Phối hợp cơ thắt khi thải')
atoms(63,'prose-and-figure','urination-volume',5,'Thải chất cần loại qua nước tiểu;Thận tạo;Bàng quang chứa tạm')
atoms(63,'figure-label-and-route','urination-volume',4,'Bể thận;Niệu quản;Bàng quang;Niệu đạo;Thứ tự từ thận tới ngoài')
atoms(63,'prose','endocrine',1,'Tuyến tiết hormone;Điều hòa chức năng')
atoms(63,'figure-label','endocrine',2,'Tuyến yên;Tuyến tùng;Tuyến giáp;Tuyến cận giáp')
atoms(63,'figure-label','endocrine',3,'Tuyến ức;Tuyến thượng thận;Tuyến tụy')
atoms(63,'figure-label','endocrine',4,'Buồng trứng;Tinh hoàn')
atoms(64,'prose','immunity',1,'Phòng vệ trước tác nhân;Vi khuẩn;Virus')
atoms(64,'prose-and-table','immunity',2,'Thói quen ảnh hưởng sức khỏe;Tâm trạng và stress;Ăn cân đối;Vận động vừa sức;Thiếu ngủ;Quá sức;Vận động quá mức')
atoms(64,'table','immunity',3,'Lão hóa;Cười;Giữ ấm','Không coi cười hay làm ấm là biện pháp bảo đảm tăng miễn dịch hoặc ngừa nhiễm.')
atoms(65,'prose-and-figure','sleep',5,'Dừng hoặc giảm hoạt động;Thư giãn cơ thể;Thư giãn tinh thần;Phục hồi mệt mỏi;Trí nhớ;Cảm xúc;Chức năng miễn dịch','Hỗ trợ chức năng, không cam kết tăng miễn dịch cho mọi người.')
atoms(65,'prose','sleep',2,'Đồng hồ ngày đêm;Ánh sáng buổi sáng;Đồng bộ nhịp')
atoms(66,'prose-and-figure','sleep',3,'NREM;REM;Các giai đoạn lặp','NREM gồm nhiều độ sâu; REM không đồng nghĩa ngủ nông.')
atoms(66,'prose-and-figure-caption','sleep',6,'Hoạt động não REM tương tự thức;Mơ thường gặp REM;Não vẫn đang ngủ','Giấc mơ cũng có thể xảy ra ngoài REM; không diễn giải REM là não tỉnh.')
atoms(66,'prose','sleep',4,'Có thể giảm ngủ sâu;Có thể ngủ ngắn;Có thể thức nhiều','Xu hướng không áp cho mọi người cao tuổi.')
atoms(66,'prose','sleep',7,'Thức vì đi tiểu;Thức vì tiếng động;Cần tìm hiểu gián đoạn')
out=dict(scopePrintedPages=list(range(42,67)),visualPagesChecked=list(range(42,67)),sourceSha256='997bf386ba8344e19c644c3cbd6ae2d40760bfb32ed882db999ad8e17068aa54',runtimeSha256=hashlib.sha256((R/'src/data/kaigo/atomic-supplements.json').read_bytes()).hexdigest(),atoms=rows,fullScopeAtomInventoryCertified=False,allSourceKnowledgeFullyCovered=False,wholeDocumentCoveragePercent=None,humanReviewed=False,scopeVi='Danh mục AI biên tập sau đọc toàn văn và xem hình 42–66, chưa chứng nhận độc lập tính đầy đủ.',referenceUrls=['https://www.nei.nih.gov/eye-health-information/healthy-vision/how-eyes-work','https://www.nhlbi.nih.gov/health/sleep/stages-of-sleep','https://medlineplus.gov/ency/article/004019.htm'])
(R/'docs/ssw-workspace/kaigo/reviews/body-source-atoms-2026-10-09.json').write_text(json.dumps(out,ensure_ascii=False,indent=2)+'\n')
print(json.dumps(dict(bodyAtoms=len(rows),pages=25,qualified=sum(bool(x['qualificationVi']) for x in rows))))
