"""Independent concept inventory of movement; not a source transcript."""
import json,hashlib
from pathlib import Path
R=Path(__file__).resolve().parents[1]
rt=json.loads((R/'src/data/kaigo/atomic-supplements.json').read_text())
points={p['id']:p['explanationVi'] for u in rt['units'] for p in u['points']}
days={i:d['day'] for d in rt['days'] for i in d['unitIds']}
rows=[]
def atoms(page,kind,key,n,concepts,qualification=None):
 pid=f'kaigo-atomic-{key}-{n}';assert pid in points
 for concept in concepts.split(';'):
  rows.append(dict(id=f'movement-atom-{len(rows)+1:03}',printedPage=page,pdfPage=page+2,kind=kind,conceptVi=concept.strip(),runtimePointId=pid,runtimeDay=days['kaigo-atomic-'+key],appEquivalentVi=points[pid],visualPageChecked=True,qualificationVi=qualification,humanReviewed=False))
atoms(120,'prose','adl-iadl',1,'Mở phạm vi hoạt động;Thể chất;Tinh thần;Tới nơi ăn;Tới nơi bài tiết;Tới nơi tắm;Liên quan mọi sinh hoạt')
atoms(121,'figure-label-and-explanation','adl-iadl',2,'ADL;Activities of Daily Living;IADL;Instrumental Activities of Daily Living;Ăn;Mặc;Tắm;Bài tiết;Di chuyển;Quản lý tiền;Mua sắm;Giặt;Phương tiện;Liên lạc')
atoms(121,'figure-relation','adl-iadl',3,'Khả năng cơ bản và tổ chức cuộc sống khác nhau','Không suy mọi IADL từ một ADL.')
atoms(122,'prose-and-figure-label','movement-body-labels',1,'Cơ;Xương;Khớp;Đầu;Cổ;Ngực;Bụng;Lưng;Eo;Mông')
atoms(122,'figure-label','movement-body-labels',2,'Vai;Cánh tay;Khuỷu;Cổ tay;Lòng bàn tay;Mu bàn tay')
atoms(122,'figure-label','movement-body-labels',3,'Chân;Đầu gối;Cổ chân;Gót;Lòng bàn chân;Mặt dưới bàn chân')
atoms(123,'group-label','posture-names',4,'Đứng;Ngồi;Nằm')
atoms(123,'figure-label','posture-names',1,'Ngồi ghế;Ngồi thả chân;Ngồi duỗi chân;Nửa nằm nửa ngồi;Fowler;Semi Fowler')
atoms(124,'figure-label','posture-names',2,'Nằm ngửa;Nằm nghiêng;Nằm sấp;Bên phải là bên ở dưới')
atoms(125,'figure-and-qualified-callout','posture-names',4,'Mẫu nằm ngửa;Vùng tựa rộng','Không học tuyệt đối là ổn định nhất/phù hợp nhất mọi người.')
atoms(125,'figure-support-label','posture-names',5,'Đệm trước ngực;Đệm dưới chân phải;Đệm giữa chân;Nâng phần chân giường;Đệm dưới gối','Theo cơ thể, da và kế hoạch.')
atoms(126,'definition-and-figure','disuse',1,'Nghỉ dài;Hoạt động ít;Tinh thần;Cảm giác;Cơ teo;Xương giảm sức bền;Cứng khớp')
atoms(126,'figure-label','disuse',2,'Điều hòa huyết áp;Tim phổi;Nội tạng;Dinh dưỡng')
atoms(126,'figure-label','disuse',5,'Hạ áp khi đứng;Hồi hộp;Hụt hơi;Dinh dưỡng kém;Năng lực hoạt động giảm','Triệu chứng mới cần đánh giá, không mặc định do khiếm dụng.')
atoms(126,'figure-action-and-definition','disuse',6,'Sau nâng đầu giường;Giảm kéo hoặc trượt lưng;Mục đích giảm lực lên da','Không chỉ dẫn tự nhấc người; cần phương án và huấn luyện.')
atoms(127,'definition','disuse',4,'Áp lực;Vùng xương nhô;Ma sát;Nếp ga;Trượt;Dinh dưỡng;Đổi tư thế;Giảm áp','Cơ chế không chỉ người nằm giường; phòng ngừa theo cá nhân.')
atoms(127,'figure-label','disuse',3,'Sau đầu;Vai;Khuỷu;Xương cùng;Mông;Gót;Vị trí theo tư thế')
atoms(127,'care-callout','disuse',7,'Quan sát khi thay áo;Quan sát khi tắm;Da đỏ;Báo chuyên môn;Không đợi loét;Rời giường theo khả năng')
atoms(128,'figure-label-and-comparison','movement-devices',1,'Gậy chữ T;Nhẹ;Gậy nhiều chân;Vùng tựa rộng;Khung tập đi;So vùng tựa','Vững hơn trong mô tả không bảo đảm không ngã.')
atoms(128,'figure-label','movement-devices',2,'Máy nâng trần;Máy nâng sàn;Giảm tải nhân viên','Chọn và dùng cần đào tạo.')
atoms(129,'numbered-prose','turning-sitting',1,'Sức khỏe trước hỗ trợ;Giải thích;Đồng ý;Giường phù hợp;Tự làm phần có thể')
atoms(129,'callout','turning-sitting',6,'Sức khỏe không phù hợp thì báo;Không miễn cưỡng;Giảm tải lưng;Mục tiêu chân có tựa;Hỗ trợ tự lập')
atoms(130,'example-action','turning-sitting',2,'Mẫu liệt trái;Bên yếu ở trên;Gập gối;Chỉnh chân thoải mái','Mẫu không là chỉ định cho mọi người.')
atoms(130,'figure-arrow-and-relation','turning-sitting',5,'Thu gọn trước chuyển;Hông ra sau;Ổn định khi nghiêng;Diện tựa rộng sau chuyển','Hai thời điểm khác mục đích.')
atoms(131,'numbered-prose','turning-sitting',3,'Nghiêng phải;Hai chân tới mép;Đưa chân xuống;Dùng khuỷu bên khỏe;Nâng thân;Độ cao cho chân có tựa')
atoms(131,'care-prerequisite','turning-sitting',1,'Kiểm sức khỏe;Giải thích và đồng ý')
atoms(132,'care-follow-up','turning-sitting',4,'Kiểm cảm giác;Kiểm sức khỏe;Hai bàn chân chạm sàn;Chóng mặt')
atoms(132,'figure-and-callout','standing-cane',5,'Tiến gần mép;Chân khỏe lùi;Nhận trọng lượng;Người hỗ trợ phía yếu','Không ép khớp/sức chịu tải theo mẫu.')
atoms(133,'figure-action','standing-cane',1,'Bảo vệ gối yếu;Thân nghiêng trước;Trọng tâm tới vùng tựa')
atoms(133,'definition-and-callout','standing-cane',2,'Gối mất giữ tải;Nguy cơ té;Đổi đầu hoặc thân;Chóng mặt;Kiểm sức khỏe')
atoms(134,'comparison-table-and-numbered-figure','standing-cane',3,'Hai nhịp;Gậy và chân yếu cùng nhịp;Chân khỏe nhịp sau;Ba nhịp;Gậy trước;Chân yếu tiếp;Chân khỏe sau;So ổn định','Không đổi nhịp chỉ để nhanh; khả năng thật quyết định.')
atoms(134,'position-and-rationale','standing-cane',6,'Sau bên yếu;Hỗ trợ thân khi cần;Hỗ trợ eo khi cần;Chân khỏe nhận tải khi bắt đầu','Theo kế hoạch và huấn luyện.')
atoms(135,'numbered-figure-and-callout','standing-cane',4,'Lên: gậy trước;Lên: khỏe tiếp;Lên: yếu sau;Xuống: gậy trước;Xuống: yếu tiếp;Xuống: khỏe sau;Hỗ trợ một bậc thấp hơn;Lên hỗ trợ phía sau;Xuống hỗ trợ phía trước;Tay vịn','Trình tự nhận diện hình, không thay đánh giá cầu thang.')
atoms(136,'prose','visual-guided-walking',1,'Tốc độ theo người dùng;Thỏa thuận cách hỗ trợ;Đánh giá đường')
atoms(136,'prose','visual-guided-walking',2,'Báo trước bậc;Báo trước góc rẽ;Báo trước thay đổi')
atoms(136,'figure-meaning','visual-guided-walking',3,'Tư thế dẫn mẫu;Tiếp xúc có thỏa thuận;Phản hồi người dùng','Không ép một mẫu cho mọi người.')
atoms(136,'figure-label','movement-devices',3,'Vành đẩy;Tay đẩy;Bàn để chân')
atoms(136,'figure-label','movement-devices',5,'Tựa lưng;Đệm ngồi;Gác tay;Tựa cẳng chân;Bánh trước;Bánh sau;Phân biệt bàn để chân và tựa cẳng chân')
atoms(136,'figure-label','movement-devices',6,'Phanh dừng;Phanh hỗ trợ;Thanh nâng cân bằng','Dùng theo thiết kế, không tự thử nâng bánh.')
atoms(137,'prose','movement-devices',4,'Kiểm áp suất lốp;Kiểm phanh;Lốp mềm nguy cơ giữ kém;Phanh khi dừng;Cả xe trống')
atoms(137,'prerequisite','turning-sitting',6,'Sức khỏe;Đồng ý;Giường cho hai chân chạm sàn')
atoms(137,'figure-and-callout','wheelchair-transfer',1,'Xe phía khỏe;Cố định phanh;Điểm vịn khỏe;Bảo vệ gối yếu','Mẫu liệt một bên không là nguyên tắc cho mọi chuyển người.')
atoms(137,'figure-action','wheelchair-transfer',4,'Gác tay xa;Tay khỏe vịn')
atoms(138,'numbered-action','wheelchair-transfer',4,'Nghiêng thân;Đứng;Xoay về xe;Ngồi sâu;Nâng đỡ chân;Kiểm cảm giác','Chỉ theo đánh giá và đào tạo, không tự làm khi không chịu tải.')
atoms(139,'numbered-prose','wheelchair-transfer',3,'Kiểm trước đẩy;Nói trước di chuyển;Nhả phanh đúng lúc;Chân ở bàn;Tránh kẹt tay')
atoms(139,'figure-callout','wheelchair-transfer',5,'Tay khỏe vịn gác tay;Tay yếu phía trong;Tránh bánh sau;Quần áo;Chân')
atoms(140,'figure-arrow-and-order','wheelchair-curb',1,'Dừng trước bậc;Giải thích;Tay đẩy nghiêng xuống;Bánh trước lên trước;Bánh sau lên sau')
atoms(140,'figure-callout','wheelchair-curb',5,'Chân chắc thanh nâng;Kiểm soát nghiêng xe;Không tăng lực để vượt bậc không phù hợp','Không là chỉ dẫn tự thử.')
atoms(141,'figure-arrow-and-order','wheelchair-curb',2,'Dừng và giải thích;Quay về sau;Bánh sau hạ trước;Bánh trước hạ sau;Từ từ')
atoms(141,'figure-callout','wheelchair-curb',5,'Tay đẩy nghiêng xuống;Chân trên thanh nâng;Kiểm soát hạ')
atoms(142,'figure-and-rationale','wheelchair-curb',3,'Dốc đứng;Giải thích đi lùi;Kiểm phía sau;Chân đế trước sau;Giảm trượt khỏi ghế','Xe, dốc, người dùng và năng lực quyết định phương án.')
atoms(142,'scope-limit','wheelchair-curb',4,'Hiểu trình tự không thay huấn luyện')
review=R/'docs/ssw-workspace/kaigo/reviews'
out=dict(version=1,sourceSha256='997bf386ba8344e19c644c3cbd6ae2d40760bfb32ed882db999ad8e17068aa54',runtimeSha256=hashlib.sha256((R/'src/data/kaigo/atomic-supplements.json').read_bytes()).hexdigest(),scopePrintedPages=list(range(120,143)),visualPagesChecked=list(range(120,143)),atoms=rows,openVisualItems=[],fullScopeAtomInventoryCertified=False,allSourceKnowledgeFullyCovered=False,wholeDocumentCoveragePercent=None,humanReviewed=False,domainReviewed=False,releaseReady=False,primaryChecks=['https://www.nice.org.uk/guidance/cg179/chapter/Recommendations','https://www.who.int/publications/i/item/9789240074521'])
(review/'movement-source-atoms-2026-10-09.json').write_text(json.dumps(out,ensure_ascii=False,indent=2)+'\n')
print(json.dumps(dict(atoms=len(rows),pages=23,wholeDocumentCoveragePercent=None)))
