"""Map grooming source concepts to independent authored explanations."""
import json,hashlib
from pathlib import Path
R=Path(__file__).resolve().parents[1];rt=json.loads((R/'src/data/kaigo/atomic-supplements.json').read_text());points={p['id']:p['explanationVi'] for u in rt['units'] for p in u['points']};days={i:d['day'] for d in rt['days'] for i in d['unitIds']};rows=[]
def atoms(page,kind,key,n,concepts,qualification=None):
 pid=f'kaigo-atomic-{key}-{n}';assert pid in points
 for c in concepts.split(';'):rows.append(dict(id=f'grooming-atom-{len(rows)+1:03}',printedPage=page,pdfPage=page+2,kind=kind,conceptVi=c,runtimePointId=pid,runtimeDay=days['kaigo-atomic-'+key],appEquivalentVi=points[pid],visualPageChecked=True,qualificationVi=qualification,humanReviewed=False))
atoms(170,'prose-and-figure','grooming-purpose',4,'Chỉnh diện mạo;Rửa mặt;Làm tóc;Mặc quần áo;Chăm râu;Chăm móng;Chăm miệng')
atoms(170,'prose','grooming-purpose',1,'Sạch;Cá tính;Tự tin;Tham gia xã hội;Quan hệ xã hội')
atoms(171,'prose-and-bullets','grooming-purpose',2,'Thói quen;Giá trị;Sở thích;Theo mùa;Hoạt động ngày;Khả năng tinh thần và cơ thể')
atoms(171,'benefits-and-season-figure','grooming-purpose',5,'Điều chỉnh nhiệt;Bảo vệ da;Duy trì chức năng;Thoải mái;An toàn hoạt động;Nhịp sống;Động lực;Quần áo hè;Quần áo đông','Lợi ích có điều kiện; không bảo đảm cải thiện mọi chức năng.')
atoms(172,'care-prose-and-callout','clothing-seated',1,'Giữ kín da;Xấu hổ;Kiểm sức khỏe;Giải thích;Đồng ý;Môi trường;Nhiệt độ phòng;Chuẩn bị đồ;Chọn theo sở thích;Người khó nhìn;Chạm chất liệu;Mô tả hình dạng')
atoms(172,'care-principle','clothing-seated',2,'Cởi khỏe trước;Mặc yếu trước')
atoms(173,'example-prose-figure-callout','clothing-seated',2,'Ngồi vững;Hỗ trợ phía yếu;Bên yếu dễ mất thăng bằng;Giảm đòi hỏi vận động bên yếu;Cởi khỏe trước','Ví dụ, không phương án chuyển người phổ quát.')
atoms(173,'example-prose','clothing-seated',3,'Tay khó cử động;Tay không với tới;Hỗ trợ phần cần')
atoms(174,'example-prose','clothing-seated',2,'Luồn tay áo phía yếu')
atoms(174,'example-prose-and-callout','clothing-seated',3,'Cảm giác mặc;Nếp đồ lót;Đồ xộc xệch;Khó chịu;Sức khỏe;Đau')
atoms(175,'pants-example-and-callout','clothing-seated',4,'Điểm bám chắc;Đứng khi được phép;Khó đứng;Phương án khi ngồi;Nhấc chân gây mất thăng bằng;Theo năng lực;Phòng ngã','Không hướng dẫn tự nâng eo hoặc thử đứng khi chưa đánh giá.')
atoms(175,'pants-principle','clothing-seated',2,'Cởi phía khỏe')
atoms(176,'pants-example','clothing-seated',5,'Luồn chân yếu;Luồn chân khỏe;Kéo trong ngồi;Chuyển đứng nếu phù hợp;Hoàn tất;Cảm giác;Sức khỏe;Đau')
atoms(176,'bed-example-and-callout','clothing-bed',1,'Cởi phía khỏe;Cuộn áo vào trong;Phần áo dưới thân;Giảm vận động phía yếu')
atoms(176,'bed-example','clothing-bed',6,'Nhân viên phía khỏe;Nút áo;Khác phía tiếp cận theo mẫu ngồi và nằm')
atoms(177,'bed-example-and-callout','clothing-bed',2,'Nghiêng;Phía khỏe dưới trong mẫu;Lấy phần áo;Bảo vệ phía yếu;Tháo tay áo yếu','Không biến bên khỏe dưới thành chỉ định mọi bệnh lý.')
atoms(178,'bed-example-and-figure','clothing-bed',3,'Mặc phía yếu;Sắp áo dưới thân;Chuyển tư thế phù hợp;Trải áo;Đường may lưng;Đường may hai bên;Mặc phía khỏe')
atoms(179,'pants-bed-example','clothing-bed',4,'Cởi khỏe;Mặc yếu;Nâng hông khi có khả năng và được phép')
atoms(179,'finish-example','clothing-bed',5,'Hỏi cảm giác;Sức khỏe thay đổi;Đau')
atoms(180,'face-care','face-hair-makeup',4,'Buổi sáng;Làm sạch da;Tỉnh táo;Khăn ấm;Kiểm nhiệt')
atoms(180,'face-care','face-hair-makeup',1,'Giữ ẩm;Da khô;Hỗ trợ khi chưa tự rửa')
atoms(180,'hair-care-and-figure','face-hair-makeup',2,'Sở thích tóc;Tình trạng tóc;Da đầu;Chọn dụng cụ;Lược tay cầm phù hợp;Khó nâng tay;Chú thích tuần hoàn','Không dùng lời nguồn thành chỉ định chà mạnh hoặc hứa cải thiện tuần hoàn.')
atoms(181,'shaving-prose-and-figure','grooming-figure',1,'Máy cạo điện;Hướng tiếp xúc;Gần vuông góc trong mẫu;Lực;Nếp da','Theo loại máy và da, không mọi máy cùng góc.')
atoms(181,'shaving-care','grooming-figure',4,'Sở thích râu;Giữ kiểu râu;Không bỏ sót;Không lặp gây kích ứng;Dưỡng da;Nước hoa hồng minh họa','Không một sản phẩm bắt buộc.')
atoms(181,'nail-care','grooming-figure',5,'Chất bẩn ở móng;Móng dài;Xước da;Sức khỏe và móng;Móng mềm sau tắm;Kiểm móng;Kiểm da quanh;Báo bất thường')
atoms(181,'nail-label-and-symbol','grooming-figure',2,'Bờ đều;Mẫu đầu vuông;Cắt sâu;Khoét góc;Dụng cụ cắt;Dụng cụ giũa;Làm nhẵn bờ','Nhận diện ý hình, không tự xử lý móng có nguy cơ.')
atoms(182,'makeup-care','face-hair-makeup',3,'Cá tính;Nguyện vọng;Sở thích;Tẩy trước ngủ;Chăm da;Giúp phần chưa tự làm')
atoms(182,'mouth-care-purpose','oral-details',1,'Mảng bám;Sâu răng;Nướu;Mùi;Vi khuẩn;Nguy cơ viêm phổi;Nước bọt;Khô miệng;Vị giác;Ăn uống','Giảm nguy cơ, không hứa phòng toàn bộ viêm phổi.')
atoms(182,'mouth-care-bullets','oral-details',2,'Súc khi phù hợp;Chải nhẹ;Từng vùng;Không bỏ sót;Quan sát miệng;Thức ăn bên yếu')
atoms(182,'mouth-care-report','oral-details',6,'Chảy máu;Sưng nướu;Báo chuyên môn')
atoms(182,'front-care-figure','oral-details',8,'Ngang tầm;Mục tiêu hỗ trợ tư thế;Không bảo đảm phòng rối loạn nuốt')
atoms(183,'back-care-figure-callout','oral-details',3,'Giữ đầu ổn định;Tư thế;Tránh ngửa cằm;Phía trước và phía sau là ví dụ')
atoms(183,'grip-figure-and-callout','oral-details',4,'Cầm như bút;Kiểm lực;Nhẹ;Tránh tổn thương nướu và răng')
atoms(183,'sponge-example','oral-details',8,'Dụng cụ mút;Theo khả năng miệng nuốt;Theo đào tạo;Kiểm nguyên vẹn','Không tương đương chải răng mặc định.')
atoms(184,'denture-labels','oral-details',5,'Bổ sung răng mất;Toàn phần;Một phần;Hàm trên;Hàm dưới')
atoms(184,'denture-prose','oral-details',7,'Thức ăn lưu;Mảng bám;Làm sạch sau ăn;Tháo theo kế hoạch;Bàn chải;Nước;Răng còn lại;Mô miệng')
atoms(184,'storage-prose','oral-details',6,'Khô có thể ảnh hưởng vật liệu;Bình chứa;Dung dịch phù hợp;Hướng dẫn nha khoa','Sửa mệnh đề không để khô tuyệt đối; hướng dẫn phụ thuộc vật liệu.')
out=dict(version=1,date='2026-10-10',sourceSha256='997bf386ba8344e19c644c3cbd6ae2d40760bfb32ed882db999ad8e17068aa54',sourceBytesHashRecomputed=True,runtimeSha256=hashlib.sha256((R/'src/data/kaigo/atomic-supplements.json').read_bytes()).hexdigest(),scopePrintedPages=list(range(170,185)),visualPagesChecked=list(range(170,185)),visualInspectionMethod='text layer and three five-page contact sheets',atoms=rows,openVisualItems=[],fullScopeAtomInventoryCertified=False,allSourceKnowledgeFullyCovered=False,wholeDocumentCoveragePercent=None,humanReviewed=False,domainReviewed=False,releaseReady=False,primaryChecks=['https://www.nice.org.uk/guidance/ng48/chapter/Recommendations','https://www.nhs.uk/tests-and-treatments/dentures/'])
(R/'docs/ssw-workspace/kaigo/reviews/grooming-source-atoms-2026-10-10.json').write_text(json.dumps(out,ensure_ascii=False,indent=2)+'\n');print(json.dumps(dict(atoms=len(rows),pages=15)))
