import { useMemo, useState } from 'react';
import { ScrollView, StyleSheet, Text, View } from 'react-native';
import * as Speech from 'expo-speech';

import { JlptActionButton, JlptAnswerOption, JlptExamHeader, JlptPaper, JlptProgressBar, JlptQuestionText, JlptReadingPassage, JlptReviewFeedback, JlptSectionHeading, JlptSubmitConfirmation } from '@/components/jlpt/ui/JlptExamUI';
import type { JlptLevel } from '@/data/jlpt-learning';
import { sampleExamFor } from '@/data/jlpt-mock/sample-exams';
import { JLPT_EXAM } from '@/theme/jlpt-exam-design-system';

export default function ApprovedMockExam({ level, onExit }: { level: JlptLevel; onExit: () => void }) {
  const exam = useMemo(() => sampleExamFor(level), [level]);
  const [started, setStarted] = useState(false);
  const [answers, setAnswers] = useState<Record<string, string>>({});
  const [submitted, setSubmitted] = useState(false);
  const [confirming, setConfirming] = useState(false);
  const correct = exam.questions.filter((q) => answers[q.id] === q.correctOptionId).length;
  const answered = Object.keys(answers).length;
  const restart = () => { setStarted(false); setSubmitted(false); setAnswers({}); };

  if (!started) return <View style={styles.screen}><JlptExamHeader title={`${level} · JLPT模擬試験`} subtitle="日本語能力試験" onBack={onExit} /><ScrollView contentContainerStyle={styles.start}><JlptPaper><Text style={styles.title}>模擬試験 · 第1回</Text><Text style={styles.copy}>全{exam.questions.length}問。正答、解説、聴解スクリプトは提出後に表示されます。</Text><JlptActionButton label="試験を始める" onPress={() => setStarted(true)} style={styles.action} /></JlptPaper></ScrollView></View>;
  if (submitted) return <View style={styles.screen}><JlptExamHeader title={`${level} · 試験結果`} subtitle="模擬試験 · 第1回" onBack={onExit} /><ScrollView contentContainerStyle={styles.content}><JlptPaper><Text style={styles.resultTitle}>試験結果</Text><Text style={styles.score}>{correct}/{exam.questions.length}</Text>{exam.questions.map((q, index) => <View key={q.id} style={styles.question}><JlptSectionHeading problem={`問題 ${index + 1}`} detail={q.section} />{q.passage ? <JlptReadingPassage scale={1}>{q.passage}</JlptReadingPassage> : null}<JlptQuestionText scale={1}>{q.prompt}</JlptQuestionText><JlptReviewFeedback correct={answers[q.id] === q.correctOptionId} answer={q.correctOptionId} sourcePage={index + 1} /><Text style={styles.explanation}>{q.explanation}</Text>{q.audioTranscript ? <View style={styles.transcript}><Text style={styles.transcriptTitle}>聴解スクリプト</Text><Text style={styles.transcriptText}>{q.audioTranscript}</Text></View> : null}</View>)}<JlptActionButton kind="secondary" label="もう一度受験する" onPress={restart} style={styles.action} /></JlptPaper></ScrollView></View>;
  return <View style={styles.screen}><JlptExamHeader title={`${level} · 模擬試験`} subtitle="第1回" onBack={onExit} /><View style={styles.progressCopy}><Text style={styles.progressText}>{answered}/{exam.questions.length} 回答済み</Text></View><JlptProgressBar answered={answered} total={exam.questions.length} /><ScrollView contentContainerStyle={styles.content}><JlptPaper>{exam.questions.map((q, index) => <View key={q.id} style={styles.question}><JlptSectionHeading problem={`問題 ${index + 1}`} detail={q.section} />{q.passage ? <JlptReadingPassage scale={1}>{q.passage}</JlptReadingPassage> : null}{q.audioScript ? <JlptActionButton kind="secondary" label="▶ 問題音声" onPress={() => Speech.speak(q.audioScript ?? '', { language: 'ja-JP', rate: 0.75 })} style={styles.audio} /> : null}<JlptQuestionText scale={1}>{q.prompt}</JlptQuestionText><View>{q.options.map((option) => <JlptAnswerOption key={option.id} number={option.id} selected={answers[q.id] === option.id} scale={1} onPress={() => setAnswers((current) => ({ ...current, [q.id]: option.id }))}>{option.text}</JlptAnswerOption>)}</View></View>)}<JlptActionButton label="答案を提出する" onPress={() => setConfirming(true)} style={styles.action} /></JlptPaper></ScrollView><JlptSubmitConfirmation visible={confirming} total={exam.questions.length} answered={answered} onCancel={() => setConfirming(false)} onSubmit={() => { setConfirming(false); setSubmitted(true); }} /></View>;
}

const styles = StyleSheet.create({screen:{flex:1,backgroundColor:JLPT_EXAM.color.page},start:{flexGrow:1,justifyContent:'center',padding:16,backgroundColor:JLPT_EXAM.color.page},content:{paddingVertical:12,paddingHorizontal:8,backgroundColor:JLPT_EXAM.color.page},title:{fontFamily:JLPT_EXAM.font.content,fontSize:24,lineHeight:34,color:JLPT_EXAM.color.ink,textAlign:'center'},copy:{fontFamily:JLPT_EXAM.font.interface,fontSize:15,lineHeight:24,color:JLPT_EXAM.color.secondaryInk,textAlign:'center',marginTop:10},action:{marginTop:14},progressCopy:{paddingHorizontal:12,paddingVertical:8,backgroundColor:JLPT_EXAM.color.paper},progressText:{fontFamily:JLPT_EXAM.font.interface,fontSize:14,color:JLPT_EXAM.color.ink},question:{paddingBottom:28,marginBottom:26,borderBottomWidth:1,borderBottomColor:JLPT_EXAM.color.divider},audio:{marginBottom:12},resultTitle:{fontFamily:JLPT_EXAM.font.content,fontSize:28,lineHeight:38,color:JLPT_EXAM.color.ink,textAlign:'center'},score:{fontFamily:JLPT_EXAM.font.content,fontSize:42,lineHeight:54,color:JLPT_EXAM.color.correct,textAlign:'center',marginVertical:10},explanation:{fontFamily:JLPT_EXAM.font.interface,fontSize:14,lineHeight:22,color:JLPT_EXAM.color.secondaryInk,marginTop:10},transcript:{borderWidth:1,borderColor:JLPT_EXAM.color.divider,padding:14,marginTop:12},transcriptTitle:{fontFamily:JLPT_EXAM.font.interface,fontSize:16,color:JLPT_EXAM.color.ink,marginBottom:8},transcriptText:{fontFamily:JLPT_EXAM.font.content,lineHeight:25,color:JLPT_EXAM.color.ink}});
