import type { AppLanguageCode } from '@/i18n/languages';
import type { LifePlayerTurn } from '@/types/life-conversation';

// The generated city dialogue corpus reuses this finite answer set. Vietnamese
// meanings are kept locally so the learner sees the intended meaning immediately
// without a network translation request. Other languages can be supplied by the
// content pipeline through player.translations.
const VI: Record<string, string> = {
  'Lサイズをお願いします。':'Cho tôi cỡ L.',
  'ありがとうございます。':'Cảm ơn bạn.',
  'ありがとうございます。レジはどこですか。':'Cảm ơn bạn. Quầy tính tiền ở đâu?',
  'ありがとうございます。大丈夫です。':'Cảm ơn bạn. Tôi ổn rồi.',
  'いいえ、そのままでいいです。':'Không, cứ để như vậy là được.',
  'いいえ、大丈夫です。ありがとうございました。':'Không, tôi ổn rồi. Xin cảm ơn.',
  'おすすめのラーメンは何ですか。':'Món ramen nào được đề xuất?',
  'おはようございます。今日の作業は何ですか。':'Chào buổi sáng. Công việc hôm nay là gì?',
  'お参りの仕方を教えてください。':'Xin hãy chỉ cho tôi cách viếng lễ.',
  'お腹が痛いです。':'Tôi bị đau bụng.',
  'お茶をお願いします。':'Cho tôi trà.',
  'きっぷを買いたいです。':'Tôi muốn mua vé.',
  'ここでお弁当を食べてもいいですか。':'Tôi có thể ăn cơm hộp ở đây không?',
  'ここを見学したいです。':'Tôi muốn tham quan nơi này.',
  'このホームでいいですか。':'Sân ga này có đúng không?',
  'この乗り物に乗りたいです。':'Tôi muốn đi phương tiện này.',
  'この商品を探しています。':'Tôi đang tìm sản phẩm này.',
  'この場所のルールを教えてください。':'Xin hãy cho tôi biết quy định của nơi này.',
  'この場所への行き方を教えてください。':'Xin hãy chỉ đường đến nơi này.',
  'この料理に卵が入っていますか。':'Món này có trứng không?',
  'この書類を出したいです。':'Tôi muốn nộp giấy tờ này.',
  'この町の中心までお願いします。':'Xin hãy đưa tôi đến trung tâm thành phố.',
  'この荷物を送りたいです。':'Tôi muốn gửi kiện hàng này.',
  'これはどうやって使いますか。':'Cái này sử dụng như thế nào?',
  'これをお願いします。':'Cho tôi cái này.',
  'ごみ箱はどこですか。':'Thùng rác ở đâu?',
  'では、それをお願いします。':'Vậy cho tôi món đó.',
  'では、それを一つお願いします。':'Vậy cho tôi một cái đó.',
  'どこでお守りを買えますか。':'Tôi có thể mua bùa hộ mệnh ở đâu?',
  'どのくらいかかりますか。':'Mất khoảng bao lâu?',
  'どのくらい待ちますか。':'Phải đợi khoảng bao lâu?',
  'ねぎを探しています。':'Tôi đang tìm hành lá.',
  'はい、お願いします。':'Vâng, xin nhờ bạn.',
  'はい、ここから始めます。':'Vâng, tôi sẽ bắt đầu từ đây.',
  'はい、これです。':'Vâng, chính là cái này.',
  'はい、これをします。':'Vâng, tôi sẽ làm việc này.',
  'はい、それです。':'Vâng, đúng là cái đó.',
  'はい、一枚お願いします。':'Vâng, cho tôi một vé.',
  'はい、分かりました。ありがとうございます。':'Vâng, tôi đã hiểu. Xin cảm ơn.',
  'はい、受け取りました。':'Vâng, tôi đã nhận được.',
  'はい、同じ色がいいです。':'Vâng, tôi muốn cùng màu.',
  'はい、安全確認をします。':'Vâng, tôi sẽ kiểm tra an toàn.',
  'はい、待ちます。':'Vâng, tôi sẽ đợi.',
  'はい、持っています。':'Vâng, tôi có mang theo.',
  'はい、普通でお願いします。':'Vâng, cho tôi mức bình thường.',
  'はい、歩いて行きたいです。':'Vâng, tôi muốn đi bộ.',
  'はい、行きたいです。':'Vâng, tôi muốn đi.',
  'もう少し大きいサイズはありますか。':'Có cỡ lớn hơn một chút không?',
  'わかりました。わからない時は聞きます。':'Tôi hiểu rồi. Khi không hiểu tôi sẽ hỏi.',
  'タオルをお湯に入れてもいいですか。':'Tôi có thể cho khăn vào nước nóng không?',
  'チケットを一枚お願いします。':'Cho tôi một vé.',
  'パスワードはどこですか。':'Mật khẩu ở đâu?',
  '一人です。':'Một người.',
  '一階だけ撮ることができます。':'Chỉ có thể chụp ảnh ở tầng một.',
  '三十分ぐらいです。':'Khoảng ba mươi phút.',
  '中を見学したいです。':'Tôi muốn tham quan bên trong.',
  '今日から働くグエンです。':'Tôi là Nguyễn, bắt đầu làm việc từ hôm nay.',
  '住所の手続きをしたいです。':'Tôi muốn làm thủ tục địa chỉ.',
  '何分ぐらいかかりますか。':'Mất khoảng bao nhiêu phút?',
  '何時までですか。':'Đến mấy giờ?',
  '何時まで入れますか。':'Có thể vào đến mấy giờ?',
  '何番線ですか。':'Là sân ga số mấy?',
  '入場券を一枚お願いします。':'Cho tôi một vé vào cửa.',
  '公園は何時までですか。':'Công viên mở đến mấy giờ?',
  '写真を撮ってもいいですか。':'Tôi có thể chụp ảnh không?',
  '分かりました。':'Tôi đã hiểu.',
  '分かりました。ありがとうございます。':'Tôi đã hiểu. Xin cảm ơn.',
  '切符はいくらですか。':'Vé giá bao nhiêu?',
  '切符はどこで買えますか。':'Tôi có thể mua vé ở đâu?',
  '初めてですが、入り方を教えてください。':'Đây là lần đầu của tôi, xin hãy chỉ cách vào.',
  '初心者でも歩ける道はありますか。':'Có tuyến đường người mới cũng đi bộ được không?',
  '卵が入っていない料理はありますか。':'Có món nào không có trứng không?',
  '国内です。':'Gửi trong nước.',
  '小さくて、青い物です。':'Đó là món nhỏ màu xanh.',
  '少し気持ちが悪いです。':'Tôi hơi khó chịu trong người.',
  '必要な情報はこれです。':'Thông tin cần thiết là đây.',
  '日本語の案内はありますか。':'Có hướng dẫn bằng tiếng Nhật không?',
  '明日の午後に着く予定です。':'Dự kiến sẽ đến vào chiều mai.',
  '昨日の夜からです。':'Từ tối hôm qua.',
  '朝礼はどこですか。':'Buổi họp sáng ở đâu?',
  '東京まで行きたいです。':'Tôi muốn đi đến Tokyo.',
  '水を持って行ったほうがいいですか。':'Tôi có nên mang theo nước không?',
  '注文をお願いします。':'Tôi muốn gọi món.',
  '片道を一枚お願いします。':'Cho tôi một vé một chiều.',
  '現金で払います。':'Tôi sẽ trả bằng tiền mặt.',
  '締め切りはいつですか。':'Hạn chót là khi nào?',
  '見学は何時までですか。':'Có thể tham quan đến mấy giờ?',
  '部屋のWi-Fiについて聞きたいです。':'Tôi muốn hỏi về Wi-Fi trong phòng.',
  '野菜売り場はどこですか。':'Quầy rau ở đâu?',
  '電車の乗り換えを教えてください。':'Xin hãy chỉ cho tôi cách chuyển tàu.',
  '駅前の博物館へ行きたいです。':'Tôi muốn đến bảo tàng trước ga.',
  '魚の定食をお願いします。':'Cho tôi suất cơm cá.',
};

export function getPlayerAnswerGuidance(player: LifePlayerTurn, language: AppLanguageCode) {
  const answer = player.recommendedAnswerJa ?? '';
  const supplied = player.translations?.[language];
  if (supplied) return supplied;
  if (language === 'vi' && VI[answer]) return VI[answer];
  if (language === 'ja') return player.hint || answer;
  return player.hint || answer;
}
