import { router, useLocalSearchParams } from 'expo-router';
import { ImageBackground, SafeAreaView, ScrollView, StyleSheet, Text, View } from 'react-native';
import Animated, { FadeInDown } from 'react-native-reanimated';
import { sceneForCategory } from '@/components/world/life-assets';
import { categoryLabelJa } from '@/components/world/world-ja';
import { DepthPressable } from '@/components/world/WorldSurface';
import { RoyalBackButton, RoyalButton, RoyalInfoPanel, ROYAL, ROYAL_CONTENT_GROUP, ROYAL_FONT, ROYAL_PLACEMENT, ROYAL_TEXT_FIT, ROYAL_TYPE, useRoyalPositioning } from '@/components/ui/RoyalSurface';
import { scenarioMission } from '@/components/world/scenario-mission';
import { getLifeLocationById, getLifeScenariosByLocation, hasLifeDialogue } from '@/services/life-content-repository';

export default function LocationScreen(){
 const raw=useLocalSearchParams<{locationId:string}>().locationId,id=Array.isArray(raw)?raw[0]:raw,location=id?getLifeLocationById(id):null,royalPosition=useRoyalPositioning();
 if(!location)return <SafeAreaView style={s.empty}><Text>ロケーションが見つかりません。</Text></SafeAreaView>;
 const scenarios=getLifeScenariosByLocation(location.id).filter(x=>hasLifeDialogue(x.id)),bg=sceneForCategory(location.category),wide=royalPosition.isWide,mission=scenarioMission(scenarios[0],location.category);
 return <ImageBackground source={bg} resizeMode="cover" style={s.screen}><View style={s.shade}/><SafeAreaView style={s.safe}>
  <View style={s.header}><RoyalBackButton onPress={()=>router.back()}/><View style={s.heading}><Text {...ROYAL_TEXT_FIT} numberOfLines={1} style={s.kicker}>会話練習・{categoryLabelJa(location.category)}</Text><Text {...ROYAL_TEXT_FIT} numberOfLines={2} style={s.title}>{location.nameJa}</Text><Text {...ROYAL_TEXT_FIT} numberOfLines={1} style={s.subtitle}>全{scenarios.length}課題</Text></View></View>
  <ScrollView contentContainerStyle={[s.content,wide&&s.contentWide]} showsVerticalScrollIndicator={false}>
   <RoyalInfoPanel sizingGroup={ROYAL_CONTENT_GROUP.worldLocationSummary} label="会話トレーニング" style={[s.summary,wide&&s.summaryWide]} innerStyle={s.summaryInner}><Text maxFontSizeMultiplier={1} style={s.summaryTitle}>{mission}</Text></RoyalInfoPanel>
   <View style={[s.scenarioGrid,wide&&s.scenarioGridWide]}>{scenarios.map((scenario,index)=><Animated.View key={scenario.id} entering={FadeInDown.delay(Math.min(index,8)*55).duration(220)} style={wide?s.wideItem:undefined}><DepthPressable onPress={()=>router.push(`/world/dialogue/${scenario.id}`)} style={s.scenarioDepth}><RoyalInfoPanel sizingGroup={ROYAL_CONTENT_GROUP.worldScenario} label={`第${index+1}課題`} style={s.scenario}><View style={s.scenarioContent}><Text maxFontSizeMultiplier={1} style={s.objective}>{scenarioMission(scenario,location.category)}</Text><RoyalButton onPress={()=>router.push(`/world/dialogue/${scenario.id}`)} style={s.play} compact><Text maxFontSizeMultiplier={1} style={s.playText}>開始</Text></RoyalButton></View></RoyalInfoPanel></DepthPressable></Animated.View>)}</View>
  </ScrollView>
 </SafeAreaView></ImageBackground>
}
const s=StyleSheet.create({screen:{flex:1,backgroundColor:'#173747'},shade:{...StyleSheet.absoluteFillObject,backgroundColor:'rgba(11,31,42,.38)'},safe:{flex:1},header:{flexDirection:'row',alignItems:'center',gap:ROYAL_PLACEMENT.headerGap,paddingHorizontal:ROYAL_PLACEMENT.headerHorizontal,paddingTop:ROYAL_PLACEMENT.headerTop},heading:{flex:1},kicker:{color:ROYAL.paleGold,fontFamily:ROYAL_FONT.body,fontSize:15,letterSpacing:1.8},title:{color:'#fff',fontFamily:ROYAL_FONT.heading,fontSize:27,lineHeight:38,textShadowColor:'rgba(0,0,0,.55)',textShadowOffset:{width:0,height:2},textShadowRadius:4},subtitle:{color:'#e6f7fb',fontFamily:ROYAL_FONT.body,fontSize:16,marginTop:1},content:{flexGrow:1,justifyContent:'flex-end',padding:16,paddingTop:110,paddingBottom:42},contentWide:{paddingHorizontal:'8%',paddingTop:75},summary:{marginBottom:14},summaryInner:{padding:17},summaryWide:{maxWidth:760},summaryLabel:{color:ROYAL.paleGold,fontFamily:ROYAL_FONT.body,fontSize:ROYAL_TYPE.fieldLabel,letterSpacing:1.5},summaryTitle:{color:ROYAL.lacquer,fontFamily:ROYAL_FONT.body,fontSize:ROYAL_TYPE.explanation,lineHeight:ROYAL_TYPE.explanationLine,marginTop:6,textAlign:'center'},scenarioGrid:{gap:11},scenarioGridWide:{flexDirection:'row',flexWrap:'wrap'},wideItem:{width:'49%'},scenarioDepth:{borderRadius:21},scenario:{minHeight:146},scenarioContent:{minHeight:100,flexDirection:'row',alignItems:'center',paddingTop:9},objective:{flex:1,color:ROYAL.lacquer,fontFamily:ROYAL_FONT.body,fontSize:ROYAL_TYPE.optionSecondary,lineHeight:20,textAlign:'center'},play:{minWidth:76,height:52,marginLeft:6},playText:{color:ROYAL.paleGold,fontFamily:ROYAL_FONT.heading,fontSize:12,letterSpacing:.8},empty:{flex:1,alignItems:'center',justifyContent:'center'}});
