import React from 'react';import {createRoot} from 'react-dom/client';import {Image,StyleSheet} from 'react-native-web';
(Image as any).resolveAssetSource=(s:any)=>({uri:s.uri,width:s.__qaWidth,height:s.__qaHeight});
import {QuestionBlock} from '../../../src/components/jlpt/N1OfficialTrial';
import {N1_ORIGINAL_01_TRIAL,N1_ORIGINAL_01_VISUALS} from '../../../src/data/jlpt-original/n1/01/formal-trial';
import {N1_ORIGINAL_02_TRIAL,N1_ORIGINAL_02_VISUALS} from '../../../src/data/jlpt-original/n1/02/formal-trial';
import {N1_ORIGINAL_03_TRIAL,N1_ORIGINAL_03_VISUALS} from '../../../src/data/jlpt-original/n1/03/formal-trial';
import {N1_ORIGINAL_04_TRIAL,N1_ORIGINAL_04_VISUALS} from '../../../src/data/jlpt-original/n1/04/formal-trial';
import {N1_ORIGINAL_05_TRIAL,N1_ORIGINAL_05_VISUALS} from '../../../src/data/jlpt-original/n1/05/formal-trial';
import {N1_ORIGINAL_06_TRIAL,N1_ORIGINAL_06_VISUALS} from '../../../src/data/jlpt-original/n1/06/formal-trial';
import {N2_ORIGINAL_01_TRIAL,N2_ORIGINAL_01_VISUALS} from '../../../src/data/jlpt-original/n2/01/formal-trial';
import {N2_ORIGINAL_02_TRIAL,N2_ORIGINAL_02_VISUALS} from '../../../src/data/jlpt-original/n2/02/formal-trial';
import {N2_ORIGINAL_03_TRIAL,N2_ORIGINAL_03_VISUALS} from '../../../src/data/jlpt-original/n2/03/formal-trial';
import {N2_ORIGINAL_04_TRIAL,N2_ORIGINAL_04_VISUALS} from '../../../src/data/jlpt-original/n2/04/formal-trial';
import {N2_ORIGINAL_05_TRIAL,N2_ORIGINAL_05_VISUALS} from '../../../src/data/jlpt-original/n2/05/formal-trial';
import {N2_ORIGINAL_06_TRIAL,N2_ORIGINAL_06_VISUALS} from '../../../src/data/jlpt-original/n2/06/formal-trial';
import {N3_ORIGINAL_01_TRIAL,N3_ORIGINAL_01_VISUALS} from '../../../src/data/jlpt-original/n3/01/formal-trial';
import {N3_ORIGINAL_02_TRIAL,N3_ORIGINAL_02_VISUALS} from '../../../src/data/jlpt-original/n3/02/formal-trial';
import {N3_ORIGINAL_03_TRIAL,N3_ORIGINAL_03_VISUALS} from '../../../src/data/jlpt-original/n3/03/formal-trial';
import {N3_ORIGINAL_04_TRIAL,N3_ORIGINAL_04_VISUALS} from '../../../src/data/jlpt-original/n3/04/formal-trial';
import {N3_ORIGINAL_05_TRIAL,N3_ORIGINAL_05_VISUALS} from '../../../src/data/jlpt-original/n3/05/formal-trial';
import {N3_ORIGINAL_06_TRIAL,N3_ORIGINAL_06_VISUALS} from '../../../src/data/jlpt-original/n3/06/formal-trial';
import {N4_ORIGINAL_01_TRIAL,N4_ORIGINAL_01_VISUALS} from '../../../src/data/jlpt-original/n4/01/formal-trial';
import {N4_ORIGINAL_02_TRIAL,N4_ORIGINAL_02_VISUALS} from '../../../src/data/jlpt-original/n4/02/formal-trial';
import {N4_ORIGINAL_03_TRIAL,N4_ORIGINAL_03_VISUALS} from '../../../src/data/jlpt-original/n4/03/formal-trial';
import {N4_ORIGINAL_04_TRIAL,N4_ORIGINAL_04_VISUALS} from '../../../src/data/jlpt-original/n4/04/formal-trial';
import {N4_ORIGINAL_05_TRIAL,N4_ORIGINAL_05_VISUALS} from '../../../src/data/jlpt-original/n4/05/formal-trial';
import {N4_ORIGINAL_06_TRIAL,N4_ORIGINAL_06_VISUALS} from '../../../src/data/jlpt-original/n4/06/formal-trial';
import {N5_ORIGINAL_01_TRIAL,N5_ORIGINAL_01_VISUALS} from '../../../src/data/jlpt-original/n5/01/formal-trial';
import {N5_ORIGINAL_02_TRIAL,N5_ORIGINAL_02_VISUALS} from '../../../src/data/jlpt-original/n5/02/formal-trial';
import {N5_ORIGINAL_03_TRIAL,N5_ORIGINAL_03_VISUALS} from '../../../src/data/jlpt-original/n5/03/formal-trial';
import {N5_ORIGINAL_04_TRIAL,N5_ORIGINAL_04_VISUALS} from '../../../src/data/jlpt-original/n5/04/formal-trial';
import {N5_ORIGINAL_05_TRIAL,N5_ORIGINAL_05_VISUALS} from '../../../src/data/jlpt-original/n5/05/formal-trial';
import {N5_ORIGINAL_06_TRIAL,N5_ORIGINAL_06_VISUALS} from '../../../src/data/jlpt-original/n5/06/formal-trial';
const exams=[{id:'n1-01',questions:N1_ORIGINAL_01_TRIAL,visuals:N1_ORIGINAL_01_VISUALS},{id:'n1-02',questions:N1_ORIGINAL_02_TRIAL,visuals:N1_ORIGINAL_02_VISUALS},{id:'n1-03',questions:N1_ORIGINAL_03_TRIAL,visuals:N1_ORIGINAL_03_VISUALS},{id:'n1-04',questions:N1_ORIGINAL_04_TRIAL,visuals:N1_ORIGINAL_04_VISUALS},{id:'n1-05',questions:N1_ORIGINAL_05_TRIAL,visuals:N1_ORIGINAL_05_VISUALS},{id:'n1-06',questions:N1_ORIGINAL_06_TRIAL,visuals:N1_ORIGINAL_06_VISUALS},{id:'n2-01',questions:N2_ORIGINAL_01_TRIAL,visuals:N2_ORIGINAL_01_VISUALS},{id:'n2-02',questions:N2_ORIGINAL_02_TRIAL,visuals:N2_ORIGINAL_02_VISUALS},{id:'n2-03',questions:N2_ORIGINAL_03_TRIAL,visuals:N2_ORIGINAL_03_VISUALS},{id:'n2-04',questions:N2_ORIGINAL_04_TRIAL,visuals:N2_ORIGINAL_04_VISUALS},{id:'n2-05',questions:N2_ORIGINAL_05_TRIAL,visuals:N2_ORIGINAL_05_VISUALS},{id:'n2-06',questions:N2_ORIGINAL_06_TRIAL,visuals:N2_ORIGINAL_06_VISUALS},{id:'n3-01',questions:N3_ORIGINAL_01_TRIAL,visuals:N3_ORIGINAL_01_VISUALS},{id:'n3-02',questions:N3_ORIGINAL_02_TRIAL,visuals:N3_ORIGINAL_02_VISUALS},{id:'n3-03',questions:N3_ORIGINAL_03_TRIAL,visuals:N3_ORIGINAL_03_VISUALS},{id:'n3-04',questions:N3_ORIGINAL_04_TRIAL,visuals:N3_ORIGINAL_04_VISUALS},{id:'n3-05',questions:N3_ORIGINAL_05_TRIAL,visuals:N3_ORIGINAL_05_VISUALS},{id:'n3-06',questions:N3_ORIGINAL_06_TRIAL,visuals:N3_ORIGINAL_06_VISUALS},{id:'n4-01',questions:N4_ORIGINAL_01_TRIAL,visuals:N4_ORIGINAL_01_VISUALS},{id:'n4-02',questions:N4_ORIGINAL_02_TRIAL,visuals:N4_ORIGINAL_02_VISUALS},{id:'n4-03',questions:N4_ORIGINAL_03_TRIAL,visuals:N4_ORIGINAL_03_VISUALS},{id:'n4-04',questions:N4_ORIGINAL_04_TRIAL,visuals:N4_ORIGINAL_04_VISUALS},{id:'n4-05',questions:N4_ORIGINAL_05_TRIAL,visuals:N4_ORIGINAL_05_VISUALS},{id:'n4-06',questions:N4_ORIGINAL_06_TRIAL,visuals:N4_ORIGINAL_06_VISUALS},{id:'n5-01',questions:N5_ORIGINAL_01_TRIAL,visuals:N5_ORIGINAL_01_VISUALS},{id:'n5-02',questions:N5_ORIGINAL_02_TRIAL,visuals:N5_ORIGINAL_02_VISUALS},{id:'n5-03',questions:N5_ORIGINAL_03_TRIAL,visuals:N5_ORIGINAL_03_VISUALS},{id:'n5-04',questions:N5_ORIGINAL_04_TRIAL,visuals:N5_ORIGINAL_04_VISUALS},{id:'n5-05',questions:N5_ORIGINAL_05_TRIAL,visuals:N5_ORIGINAL_05_VISUALS},{id:'n5-06',questions:N5_ORIGINAL_06_TRIAL,visuals:N5_ORIGINAL_06_VISUALS}];
const p=new URLSearchParams(location.search),exam=exams.find(e=>e.id===p.get('exam'))||exams[0];const images=exam.questions.filter(q=>q.visualOptionPage);(window as any).qa={exams:exams.map(e=>({id:e.id,images:e.questions.filter(q=>q.visualOptionPage).length})),images:images.map(q=>q.id)};
function App(){return <div style={{maxWidth:744,margin:'0 auto',padding:18}}>{(images.length?images:exam.questions.filter(q=>q.family==='listening').slice(0,4)).map(q=><QuestionBlock key={q.id} question={q} scale={1} submitted={false} visualOptions={exam.visuals} onChoose={()=>{}} onLayout={()=>{}} onFocus={()=>{}}/>)}</div>}createRoot(document.getElementById('root')!).render(<App/>);
