// Static images already referenced by each screen. No render behavior changes.
export const ROUTE_ARTWORK: Record<string, number[]> = {
  '/portal': [require('../../../assets/app/registration/registration-bg.jpg')],
  '/npc-starter': [require('../../../assets/app/life/rewards/npc-card-frame-royal.png')],
  '/home': [require('../../../assets/app/home-cards/conversation-three.png'),require('../../../assets/app/home-cards/study-man.png'),require('../../../assets/app/home-cards/tokutei-engine-safety.png'),require('../../../assets/app/welcome/welcome-japan-landscape-v2.png')],
  '/learn': [require('../../../assets/app/ui/royal-af/rank-n1-v1.png'),require('../../../assets/app/ui/royal-af/rank-n2-v1.png'),require('../../../assets/app/ui/royal-af/rank-n3-v1.png'),require('../../../assets/app/ui/royal-af/rank-n4-v1.png'),require('../../../assets/app/ui/royal-af/rank-n5-v1.png')],
  '/': [require('../../../assets/app/ui/royal-af/button-wide-v2.png'),require('../../../assets/app/welcome/sakura-petal-welcome-v2.png'),require('../../../assets/app/welcome/welcome-japan-landscape-v2.png'),require('../../../assets/app/welcome/welcome-japan-portrait-v2.png')],
  '/profile': [require('../../../assets/app/backgrounds/profile-details.png'),require('../../../assets/app/backgrounds/profile-light.png'),require('../../../assets/app/ui/royal-af/hud-player-medallion-v1.png'),require('../../../assets/app/ui/royal-af/learning-grammar-v1.png'),require('../../../assets/app/ui/royal-af/lock-grape-v2.png'),require('../../../assets/app/ui/royal-af/map-marker-fill-v1.png'),require('../../../assets/app/ui/royal-af/mission-key-v1.png'),require('../../../assets/app/ui/royal-af/mission-trophy-v1.png'),require('../../../assets/app/ui/royal-af/mission-work-v1.png')],
  '/[level]/[section]': [require('../../../assets/app/ui/royal-af/learning-characters-v1.png'),require('../../../assets/app/ui/royal-af/learning-grammar-v1.png')],
  '/[level]': [require('../../../assets/app/ui/royal-af/learning-characters-v1.png'),require('../../../assets/app/ui/royal-af/learning-exam-v1.png'),require('../../../assets/app/ui/royal-af/learning-grammar-v1.png'),require('../../../assets/app/ui/royal-af/learning-vocabulary-v1.png')],
  '/register/work': [require('../../../assets/app/backgrounds/registration-work.png')],
  '/tasks': [require('../../../assets/app/ui/royal-af/checkmark-v2.png'),require('../../../assets/app/ui/royal-af/hud-coin-v1.png'),require('../../../assets/app/ui/royal-af/lock-grape-v2.png'),require('../../../assets/app/ui/royal-af/mission-key-v1.png'),require('../../../assets/app/ui/royal-af/mission-trophy-v1.png'),require('../../../assets/app/ui/royal-af/mission-work-v1.png'),require('../../../assets/app/ui/royal-af/nav-mission-v1.png')],
  '/specified-skills': [require('../../../assets/app/home-cards/tokutei-engine-safety.png'),require('../../../assets/app/industries/agriculture-v1.png'),require('../../../assets/app/industries/caregiving-v1.png'),require('../../../assets/app/industries/construction-v1.png'),require('../../../assets/app/industries/food-manufacturing-v1.png'),require('../../../assets/app/industries/food-service-v1.png'),require('../../../assets/app/industries/hospitality-v1.png')],
  '/game': [require('../../../assets/app/ui/royal-af/game-restaurant-v1.png'),require('../../../assets/game/farm/background/chicken_coop_background.png'),require('../../../assets/game/farm/background/chicken_coop_landscape_v1.png'),require('../../../assets/game/farm/background/cow_barn_background.png'),require('../../../assets/game/farm/background/cow_barn_landscape_v1.png'),require('../../../assets/game/farm/background/orchard_map_background.png'),require('../../../assets/game/farm/background/orchard_map_landscape_v1.png'),require('../../../assets/game/farm/background/vegetable_map_background_v2.png'),require('../../../assets/game/farm/background/vegetable_map_landscape_v1.png')],
  '/world/dialogue/[scenarioId]': [require('../../../assets/app/backgrounds/profile-details.png'),require('../../../assets/app/ui/royal-af/microphone-v2.png')],
  '/game/work/[operationCode]': [require('../../../assets/app/backgrounds/profile-details.png'),require('../../../assets/app/life/location-backgrounds/construction-site/01-clear-morning.jpg'),require('../../../assets/app/life/npcs/construction-site.png'),require('../../../assets/app/ui/royal-af/hint-gold-grape-v1.png'),require('../../../assets/app/ui/royal-af/hint-red-lantern-v2.png'),require('../../../assets/app/ui/royal-af/hud-coin-v1.png'),require('../../../assets/app/ui/royal-af/learning-grammar-v1.png'),require('../../../assets/app/ui/royal-af/microphone-v2.png'),require('../../../assets/app/ui/royal-af/mission-trophy-v1.png'),require('../../../assets/app/ui/royal-af/work-farm-supervisor-v1.png'),require('../../../assets/game/farm/background/vegetable_map_background_v2.png')],
};
