import type { ImageSourcePropType } from 'react-native';
import metadataJson from '@/data/location-place-artwork.json';

const metadata = metadataJson as Record<string, { category: string }>;
const artwork: Record<string, ImageSourcePropType> = {
  'LOC-008-01': require('../../../assets/app/life/location-backgrounds/places/mito-station-hitachi.png'),
  'LOC-008-18': require('../../../assets/app/life/location-backgrounds/places/mito-kairakuen-seasonal-station.png'),
  'LOC-008-08': require('../../../assets/app/life/location-backgrounds/places/mito-kairakuen-kobuntei.png'),
  'LOC-008-09': require('../../../assets/app/life/location-backgrounds/places/mito-tokiwa-shrine.png'),
  'LOC-008-13': require('../../../assets/app/life/location-backgrounds/places/mito-uchihara-aeon-mall.png'),
  'LOC-008-15': require('../../../assets/app/life/location-backgrounds/places/mito-history-mitsukaido-school.png'),
  'LOC-008-17': require('../../../assets/app/life/location-backgrounds/places/bando-ibaraki-nature-museum.png'),
  'LOC-007-18': require('../../../assets/app/life/location-backgrounds/places/fukushima-iizaka-station.png'),
  'LOC-007-01': require('../../../assets/app/life/location-backgrounds/places/fukushima-station-yamabiko.png'),
  'LOC-007-13': require('../../../assets/app/life/location-backgrounds/places/fukushima-aeon-food-court.png'),
  'LOC-007-16': require('../../../assets/app/life/location-backgrounds/places/fukushima-nakacho-yamada.png'),
  'LOC-007-08': require('../../../assets/app/life/location-backgrounds/places/fukushima-hanamiyama.png'),
  'LOC-007-10': require('../../../assets/app/life/location-backgrounds/places/fukushima-inari-shrine.png'),
  'LOC-007-09': require('../../../assets/app/life/location-backgrounds/places/fukushima-iizaka-sabakoyu.png'),
  'LOC-007-15': require('../../../assets/app/life/location-backgrounds/places/aizuwakamatsu-tsurugajo.png'),
  'LOC-007-17': require('../../../assets/app/life/location-backgrounds/places/aizuwakamatsu-fukushima-museum.png'),
  'LOC-FKS-AIZUWAKAMATSU-01': require('../../../assets/app/life/location-backgrounds/places/aizuwakamatsu-tsurugajo.png'),
  'LOC-006-01': require('../../../assets/app/life/location-backgrounds/places/yamagata-station-tsubasa.png'),
  'LOC-006-13': require('../../../assets/app/life/location-backgrounds/places/yamagata-spal-entrance.png'),
  'LOC-006-08': require('../../../assets/app/life/location-backgrounds/places/yamagata-yamadera-godaido.png'),
  'LOC-006-09': require('../../../assets/app/life/location-backgrounds/places/yamagata-kajo-moat.png'),
  'LOC-006-10': require('../../../assets/app/life/location-backgrounds/places/yamagata-zao-onsen.png'),
  'LOC-006-16': require('../../../assets/app/life/location-backgrounds/places/yamagata-nanokamachi-gotenzeki.png'),
  'LOC-006-17': require('../../../assets/app/life/location-backgrounds/places/yamagata-prefectural-museum.png'),
  'LOC-006-18': require('../../../assets/app/life/location-backgrounds/places/yamagata-yamako-bus-terminal.png'),
  'LOC-006-15': require('../../../assets/app/life/location-backgrounds/places/yamagata-zao-juhyo.png'),
  'LOC-005-13': require('../../../assets/app/life/location-backgrounds/places/akita-aeon-mall.png'),
  'LOC-005-10': require('../../../assets/app/life/location-backgrounds/places/akita-neburi-nagashi.png'),
  'LOC-005-01': require('../../../assets/app/life/location-backgrounds/places/akita-komachi-platform.png'),
  'LOC-005-18': require('../../../assets/app/life/location-backgrounds/places/akita-komachi-platform.png'),
  'LOC-005-17': require('../../../assets/app/life/location-backgrounds/places/akita-museum-water-garden.png'),
  'LOC-005-16': require('../../../assets/app/life/location-backgrounds/places/akita-kawabata.png'),
  'LOC-005-15': require('../../../assets/app/life/location-backgrounds/places/akita-kanto-avenue.png'),
  'LOC-005-09': require('../../../assets/app/life/location-backgrounds/places/oga-namahage-museum.png'),
  'LOC-005-08': require('../../../assets/app/life/location-backgrounds/places/akita-senshu-kubota-gate.png'),
  'LOC-001-15': require('../../../assets/app/life/location-backgrounds/places/sapporo-maruyama-zoo.png'),
  'LOC-001-07': require('../../../assets/app/life/location-backgrounds/places/sapporo-hassamu-mall.png'),
  'LOC-001-01': require('../../../assets/app/life/location-backgrounds/places/sapporo-station-south.png'),
  'LOC-001-09': require('../../../assets/app/life/location-backgrounds/places/sapporo-ramen-alley.png'),
  'LOC-001-10': require('../../../assets/app/life/location-backgrounds/places/sapporo-susukino.png'),
  'LOC-001-11': require('../../../assets/app/life/location-backgrounds/places/sapporo-nijo-market.png'),
  'LOC-001-17': require('../../../assets/app/life/location-backgrounds/places/sapporo-jozankei-futami.png'),
  'LOC-001-14': require('../../../assets/app/life/location-backgrounds/places/sapporo-hokkaido-shrine.png'),
  'LOC-001-02': require('../../../assets/app/life/location-backgrounds/places/sapporo-odori-tv-tower.png'),
  'LOC-001-04': require('../../../assets/app/life/location-backgrounds/places/sapporo-odori-tv-tower.png'),
  'LOC-001-03': require('../../../assets/app/life/location-backgrounds/places/sapporo-clock-tower.png'),
  'LOC-027-02': require('../../../assets/app/life/location-backgrounds/places/osaka-tsutenkaku.png'),
  'LOC-027-03': require('../../../assets/app/life/location-backgrounds/places/osaka-dotonbori.png'),
  'LOC-002-02': require('../../../assets/app/life/location-backgrounds/places/aomori-warasse.png'),
  'LOC-002-03': require('../../../assets/app/life/location-backgrounds/places/aomori-a-factory.png'),
  'LOC-002-06': require('../../../assets/app/life/location-backgrounds/places/aomori-sunroad.png'),
  'LOC-002-10': require('../../../assets/app/life/location-backgrounds/places/aomori-gyosai-center.png'),
  'LOC-002-11': require('../../../assets/app/life/location-backgrounds/places/aomori-aspam.png'),
  'LOC-002-12': require('../../../assets/app/life/location-backgrounds/places/aomori-asamushi.png'),
  'LOC-002-13': require('../../../assets/app/life/location-backgrounds/places/aomori-hakkoda.png'),
  'LOC-002-14': require('../../../assets/app/life/location-backgrounds/places/aomori-gappo-park.png'),
  'LOC-002-19': require('../../../assets/app/life/location-backgrounds/places/aomori-showa-daibutsu.png'),
  'LOC-002-01': require('../../../assets/app/life/location-backgrounds/places/aomori-station-east.png'),
  'LOC-003-01': require('../../../assets/app/life/location-backgrounds/places/morioka-station-east.png'),
  'LOC-003-02': require('../../../assets/app/life/location-backgrounds/places/morioka-castle-ruins.png'),
  'LOC-003-05': require('../../../assets/app/life/location-backgrounds/places/morioka-maegata-aeon.png'),
  'LOC-003-11': require('../../../assets/app/life/location-backgrounds/places/morioka-redbrick-bank.png'),
  'LOC-003-12': require('../../../assets/app/life/location-backgrounds/places/morioka-stone-splitting-cherry.png'),
  'LOC-003-13': require('../../../assets/app/life/location-backgrounds/places/morioka-hoonji-rakan.png'),
  'LOC-003-14': require('../../../assets/app/life/location-backgrounds/places/morioka-tsunagi-gosho.png'),
  'LOC-003-15': require('../../../assets/app/life/location-backgrounds/places/koiwai-farm-iwate.png'),
  'LOC-003-16': require('../../../assets/app/life/location-backgrounds/places/morioka-iwayama-parkland.png'),
  'LOC-003-19': require('../../../assets/app/life/location-backgrounds/places/morioka-odori.png'),
  'LOC-004-01': require('../../../assets/app/life/location-backgrounds/places/sendai-station-west.png'),
  'LOC-004-02': require('../../../assets/app/life/location-backgrounds/places/sendai-jozenji-dori.png'),
  'LOC-004-03': require('../../../assets/app/life/location-backgrounds/places/sendai-aoba-castle-ruins.png'),
  'LOC-004-04': require('../../../assets/app/life/location-backgrounds/places/sendai-zuihoden.png'),
  'LOC-004-07': require('../../../assets/app/life/location-backgrounds/places/sendai-nagamachi-mall.png'),
  'LOC-004-08': require('../../../assets/app/life/location-backgrounds/places/sendai-asaichi.png'),
  'LOC-004-13': require('../../../assets/app/life/location-backgrounds/places/sendai-kokubuncho.png'),
  'LOC-004-15': require('../../../assets/app/life/location-backgrounds/places/sendai-uminomori.png'),
  'LOC-004-17': require('../../../assets/app/life/location-backgrounds/places/sendai-akiu-rairaikyo.png'),
  'LOC-004-18': require('../../../assets/app/life/location-backgrounds/places/sendai-akiu-great-falls.png'),
  'LOC-004-19': require('../../../assets/app/life/location-backgrounds/places/sendai-mediatheque.png'),
  'LOC-008-10': require('../../../assets/app/life/location-backgrounds/places/mito-art-tower.png'),
  'LOC-008-16': require('../../../assets/app/life/location-backgrounds/places/mito-izumicho-keisei.png'),
  'LOC-009-01': require('../../../assets/app/life/location-backgrounds/places/utsu-station-west.png'),
  'LOC-009-02': require('../../../assets/app/life/location-backgrounds/places/utsu-gyoza-statue.png'),
  'LOC-009-03': require('../../../assets/app/life/location-backgrounds/places/utsu-futaarayama-shrine.png'),
  'LOC-009-06': require('../../../assets/app/life/location-backgrounds/places/utsu-bell-mall.png'),
  'LOC-009-14': require('../../../assets/app/life/location-backgrounds/places/utsu-oya-history.png'),
  'LOC-009-15': require('../../../assets/app/life/location-backgrounds/places/utsu-hachimanyama.png'),
  'LOC-009-17': require('../../../assets/app/life/location-backgrounds/places/utsu-zoo-giraffe.png'),
  'LOC-009-11': require('../../../assets/app/life/location-backgrounds/places/utsu-orion-arcade.png'),
  'LOC-009-13': require('../../../assets/app/life/location-backgrounds/places/utsu-castle-ruins.png'),
  'LOC-009-18': require('../../../assets/app/life/location-backgrounds/places/nikko-kinugawa-tateiwa.png'),
};

// Geography belongs to the stable location ID, never a category or round-robin slot.
export function placeBackground(locationId: string, category?: string | null) {
  const entry = metadata[locationId];
  if (!entry || (category && entry.category !== category)) return undefined;
  return artwork[locationId];
}
